### ISSUE TITLE
[SHARE] map scaleDenominator error after mapnik upgrade (4.5.9→4.6.1)

### ISSUE THREAD

**Issue by JaylanChen** [mapnik/node-mapnik#1002]
What HAPPENS:

After Mapnik is upgraded (4.5.9 → 4.6.1), the visibility range of map tiles becomes abnormal and the correct content fails to be displayed. If the tile display level range is set from level 1 to level 24, the tile actually turns into a blank tile at level 7.

```xml
<MaxScaleDenominator>279541132.0782576</MaxScaleDenominator>
<MinScaleDenominator>136494.6333503862</MinScaleDenominator>
```

After conducting tests and comparisons, it has been discovered that it is associated with the project version upgrade subsequent to the Mapnik upgrade.

Test code
```javascript
const mapnik = require('@mapnik/mapnik');

const map = new mapnik.Map(256, 256);

map.load('./map4326.xml', function (err, _map) {
  if (err) throw err;
  _map.zoomToBox([112.5, 22.5, 118.125, 28.125]);
  console.log(`\r\n${_map.srs}\r\n`, _map.scale(), _map.scaleDenominator());
});
```

old proj string (epsg:4326)
```xml
<Map srs="+proj=longlat +datum=WGS84 +no_defs +type=crs">
  <Style name="My Style">
    <Rule>
      <PolygonSymbolizer fill="#f2eff9" />
      <LineSymbolizer stroke="rgb(50%,50%,50%)" stroke-width="0.1" />
    </Rule>
  </Style>
  <Layer name="world" srs="+proj=longlat +datum=WGS84 +no_defs">
    <StyleName>My Style</StyleName>
  </Layer>
</Map>
```
```bash
+proj=longlat +datum=WGS84 +no_defs
 0.02197265625 78.47377232142858
```

new proj string (epsg:4326)
```xml
<Map background-color="blue" srs="+proj=longlat +datum=WGS84 +no_defs +type=crs">
  <Style name="My Style">
    <Rule>
      <PolygonSymbolizer fill="#f2eff9" />
      <LineSymbolizer stroke="rgb(50%,50%,50%)" stroke-width="0.1" />
    </Rule>
  </Style>
  <Layer name="world" srs="+proj=longlat +datum=WGS84 +no_defs +type=crs">
    <StyleName>My Style</StyleName>
  </Layer>
</Map>
```

```bash
+proj=longlat +datum=WGS84 +no_defs +type=crs
 0.02197265625 8735660.375448717
```

The main difference is the last part of the proj string `+type=crs`

`+proj=longlat +datum=WGS84 +no_defs`
`+proj=longlat +datum=WGS84 +no_defs +type=crs`

After upgrading maonik v4.6.1, it is also correct to use 'epsg:4326';

For those who encounter similar errors subsequent to upgrading Mapnik, it is hoped to be helpful.

**Comment by artemp** [comment]
> "If a proj-string contains a +type=crs option, then it is interpreted as a CRS definition. In particular geographic CRS are assumed to have axis in the longitude, latitude order and with degree angular unit. **The use of proj-string to describe a CRS is discouraged. It is a legacy means of conveying CRS descriptions: use of object codes (EPSG:XXXX typically) or WKT description is recommended for better expressivity.***

> If a proj-string does not contain +type=crs, then it is interpreted as a coordination operation / transformation."

ref https://proj.org/en/9.5/development/reference/functions.html#c.proj_create
