### ISSUE TITLE
Memory leakage after mapnik `map.render` ?

### ISSUE THREAD

**Issue by JaylanChen** [mapnik/node-mapnik#1004]
os:                              ubuntu:22.04
nodejs:                       v22
@mapnik/mapik:       v4.6.5
pm2                           v5.4.2

Based on pg database test, data count: 182104; geom type: multipolygon, 353MB

When generating a thumbnail with the following code:
Service memory will increase a lot, and not released, continue to increase.

map.xml
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Map srs="+proj=longlat +ellps=GRS80 +no_defs +type=crs">
  <Style name="default">
    <Rule>
      <PolygonSymbolizer fill="#d5f001" fill-opacity="1"/>
      <LineSymbolizer stroke="rgb(76, 161, 45)" stroke-opacity="1" stroke-width="0.5" stroke-dasharray="5,0"/>
      <MaxScaleDenominator>279541132.0782576</MaxScaleDenominator>
      <MinScaleDenominator>33.303899743746626</MinScaleDenominator>
    </Rule>
  </Style>
  <Layer name="default" srs="+proj=longlat +datum=WGS84 +no_defs +type=crs">
    <StyleName>default</StyleName>
    <Datasource>
      <Parameter name="type">postgis</Parameter>
      <Parameter name="application_name">map-node</Parameter>
      <Parameter name="connect_timeout">30</Parameter>
      <Parameter name="host">127.0.0.1</Parameter>
      <Parameter name="port">5432</Parameter>
      <Parameter name="dbname">test</Parameter>
      <Parameter name="user">postgres</Parameter>
      <Parameter name="password">postgres</Parameter>
      <Parameter name="table">(select * from "geodata"."test_py") as mztable</Parameter>
    </Datasource>
  </Layer>
</Map>
```
generate the thumbnail code
```javascript
  const mapnik = require("@mapnik/mapnik");
  const fs = require("fs");

  mapnik.register_default_fonts();
  mapnik.register_default_input_plugins();

  const map = new mapnik.Map(256, 256);
  const xmlPath = path.resolve("map.xml");
  map.load(xmlPath, function (err, map) {
    console.log(err);
    map.zoomAll();
    const im = new mapnik.Image(256, 256);
    map.render(im, function (err, im) {
      im.encode("png", function (err, buffer) {
        fs.writeFileSync("map.png", buffer);
      });
    });
  });
```

1. Start the service with the PM2
http://localhost:3000/

MEM: 84MB
![image](https://github.com/user-attachments/assets/8eeac8fa-6d78-49fb-8d11-99dbdfbd2938)

2. generate map thumbnail
http://localhost:3000/generate
MEM: 84MB → 391MB
![image](https://github.com/user-attachments/assets/dc1603ce-00e6-4cd3-a59e-ce6d897203e6)
![image](https://github.com/user-attachments/assets/3c9588dd-1820-47bd-b707-b81c4925bce6)
![image](https://github.com/user-attachments/assets/a2bb6c56-1fdb-4647-abe5-fc8e739a1aa6)

wait 5 minutes later, MEM: 391MB
![image](https://github.com/user-attachments/assets/a7138522-b6b4-469d-bfa5-bfecaa7d0658)

3. generate map thumbnail again
http://localhost:3000/generate
MEM: 391MB → 690MB
![image](https://github.com/user-attachments/assets/d02fead5-d2ce-4e21-aa5a-723ed890b59b)
![image](https://github.com/user-attachments/assets/186f5824-da5d-4f5e-8d4e-fa6fd921d3b5)
![image](https://github.com/user-attachments/assets/93c475a3-46fc-4639-af0f-f280cb94b0ff)
![image](https://github.com/user-attachments/assets/59828664-0a15-4f38-bda7-dd91b7d4b574)

[test code](https://github.com/JaylanChen/express-mapnik-test), (no pg table data).

**Comment by artemp** [comment]
@JaylanChen - thanks for testing! To try to narrow down the issue, could you try replacing 

```js
im.encode("png", function (err, buffer) {
        fs.writeFileSync("map.png", buffer);
      });
```

with something like 

```js
im.save("map.png", function (err) {
        if (err) throw err;
      });
```

**Comment by JaylanChen** [comment]
test code
```javascript
  map.load(xmlPath, function (err, map) {
    console.log(err);
    map.zoomAll();
    const im = new mapnik.Image(256, 256);
    map.render(im, function (err, im) {
      if (err) throw err;
      const imagePath = path.resolve("test/map.png");
      im.save(imagePath, function (err) {
        if (err) throw err;
      });
    });
  });
```

![image](https://github.com/user-attachments/assets/73b328d3-3b7a-4691-a0de-9753a68f60f7)
![image](https://github.com/user-attachments/assets/b2740d3c-ac51-4fc8-9dcc-6da13e59fb81)
![image](https://github.com/user-attachments/assets/54d2aaf1-972b-4d81-b909-739921b210fe)

test again

![image](https://github.com/user-attachments/assets/8ff8a81a-ce3f-48f5-8178-a2ba1834f5e4)

memory leak persists.

**Comment by JaylanChen** [comment]
test gdal with [natural_earth.tif](https://github.com/mapnik/node-mapnik/blob/master/test/data/vector_tile/natural_earth.tif)

```xml
<Map srs="+proj=longlat +ellps=GRS80 +no_defs +type=crs">
    <Style name="raster">
        <Rule>
            <RasterSymbolizer/>
        </Rule>
    </Style>
    <Layer name="layer" srs="+proj=longlat +ellps=GRS80 +no_defs">
        <StyleName>raster</StyleName>
        <Datasource>
            <Parameter name="type">gdal</Parameter>
            <Parameter name="file">data/natural_earth.tif</Parameter>
        </Datasource>
    </Layer>
</Map>
```
servce started:
![image](https://github.com/user-attachments/assets/53a4d068-727e-4c33-b950-e3bf32543848)

http://localhost:3000/gengdal
once:
![image](https://github.com/user-attachments/assets/35f104a6-4aa5-4d15-a872-00a5178c9f35)
twice:
![image](https://github.com/user-attachments/assets/dae58481-c4d8-4999-b918-81391b0c9e70)

memory leak persists.

**Comment by artemp** [comment]
@JaylanChen - Thanks for great self-contained test cases 👍. I had a chance to run your app. I'm not, yet, convinced there is a memory leak, though. I'm seeing high but stable memory usage with `http://localhost:3000/gengdal`. And GC is reclaiming memory overtime. So far I only tested on macOS. I'll try running on Linux as well. 

But I noticed your code can (should!) be improved. You're creating new `mapnik.Map + load(<xml>)` per request. This is extremely inefficient and is draining OS resources( db connections, file descriptors etc). To make your app scalable and improve performance you should find a way to create bunch of `Map` objects, load XML and re-use them. You can achieve this by using object pool. 
HTH.

**Comment by JaylanChen** [comment]
> @JaylanChen - Thanks for great self-contained test cases 👍. I had a chance to run your app. I'm not, yet, convinced there is a memory leak, though. I'm seeing high but stable memory usage with `http://localhost:3000/gengdal`. And GC is reclaiming memory overtime. ![image](https://private-user-images.githubusercontent.com/59056/386568444-727ab411-fa33-4e6d-9c81-849027c0bddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Njg4MDUsIm5iZiI6MTczMTY2ODUwNSwicGF0aCI6Ii81OTA1Ni8zODY1Njg0NDQtNzI3YWI0MTEtZmEzMy00ZTZkLTljODEtODQ5MDI3YzBiZGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDExMDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZDdjMWRjODQ1ZjRlZDk0ZDBmZWUwMTBmZTg4MDViM2JmOGE4MWYwY2EyYzhmZDk1NzcxM2U4NjdmMTgzOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J4F2iqEYDCAqsWdkwh9wTsfjwwalcgE-1JAyexTFGkE)
> 
> So far I only tested on macOS. I'll try running on Linux as well.
> 
> But I noticed your code can (should!) be improved. You're creating new `mapnik.Map + load(<xml>)` per request. This is extremely inefficient and is draining OS resources( db connections, file descriptors etc). To make your app scalable and improve performance you should find a way to create bunch of `Map` objects, load XML and re-use them. You can achieve this by using object pool. HTH.

Thank you for your advice. Actually I used Pool to cache an instance of mapnik.

this code only for test.

**Comment by JaylanChen** [comment]
I also tested it in the Linux ARM64 environment.
Server: Ubuntu-22.04
Node: v20.18.0

The initial memory is about 67 mb. (Wait 2 minutes after startup)
![image](https://github.com/user-attachments/assets/74adbdab-9ad1-44ed-accf-4ea11941eadb)

curl http://localhost:3000/gengdal
MEM: 67mb → 80.6mb
![image](https://github.com/user-attachments/assets/18f1f650-7595-4f5d-a9d6-5f35af8aa59b)

Wait few minutes, MEM: 80.8mb
![image](https://github.com/user-attachments/assets/b338e98d-9254-463f-97fd-a7fb63c7388c)


curl http://localhost:3000/gengdal     again.
MEM: 84.6mb → 92.3mb
![image](https://github.com/user-attachments/assets/ab1c1d64-1414-4d5a-b779-5ce79890f985)

Wait few minutes, MEM: 92.0mb
![image](https://github.com/user-attachments/assets/f4fcad7c-e75b-4b17-8caf-1703c76d9bc5)

**Comment by artemp** [comment]
@JaylanChen - I did some testing on both macOS and Linux (Ubuntu 24.04) and I'm seeing stable memory usage over time. 

I did some modification to your app.js and settings, see below. 

I'm using OSM data and XML file (mapnik.xml) generated as per 
https://github.com/gravitystorm/openstreetmap-carto
https://github.com/mapbox/carto

For load testing I'm using https://www.artillery.io/  e.g

```bash
DEBUG=http artillery run mapnik-load-test.yml
```

![image](https://github.com/user-attachments/assets/0b10eda9-d552-4d6f-b97e-9b1361db564f)




* mapnik-load-test.yml

```yaml
config:
   target: http://localhost:3000
   phases:
      - duration: 60
        arrivalRate: 1
        rampTo: 5
        maxVusers: 20
        name: Warm up
      - duration: 30m
        arrivalRate: 5
        maxVusers: 50
        name: Ramp up load

   processor: "./location_generator.js"

scenarios:
    - flow:
      - get:
          url: "/generate_map?easting={{ easting }}&northing={{ northing }}"
          beforeRequest: getRandomLocation

```
* location_generator.js
```js
const fs = require('fs');
const mapnik = require("@mapnik/mapnik");
const json = JSON.parse(fs.readFileSync('./data/Trees.geojson', 'utf8'));
const num_features = Object.keys(json.features).length;

const tr = new mapnik.ProjTransform(new mapnik.Projection("epsg:4326"),
                                    new mapnik.Projection("epsg:3857"));

const generateRandomKey = (length) => Math.floor(Math.random() * length);

const getRandomLocation= (requestParams, context, ee, next) => {
  var key = generateRandomKey(num_features);
  const lon = json.features[key].geometry.coordinates[0];
  const lat = json.features[key].geometry.coordinates[1];
  const coord = tr.forward([lon, lat]);
  context.vars.easting = Math.floor(coord[0]);
  context.vars.northing = Math.floor(coord[1]);
  next();
};

module.exports = {
  getRandomLocation,
};
```
* pm2.config.js 

```js
module.exports = {
  apps: [
    {
      name: 'mapnik-test',
      script: './src/app.js',
      instances : "4",
      exec_mode : "cluster"
    },
  ],
};
```
* app.js
```js
const express = require("express");
const mapnik = require("@mapnik/mapnik");
const path = require("path");
const fs = require("fs");
const genericPool = require("generic-pool");
const { pid } = require('node:process');

mapnik.register_default_fonts();
mapnik.register_default_input_plugins();

const app = express();
const port = 3000;

const map_factory = {
  create: function() {
    const map = new mapnik.Map(4*256, 4*256);
    const xmlPath = path.resolve("../openstreetmap-carto/mapnik.xml");
    //const xmlPath = path.resolve("test/gdal_map.xml");
    map.loadSync(xmlPath);
    console.log(`--> Load Map pid:${pid} xml:${xmlPath}`);
    return map;
  },
  destroy: function(map) {
    delete map;
    console.log(`<-- Destroy Map ${pid}`);
  }
};

const opts = {
  max: 6,
  min: 2
};

const pool = genericPool.createPool(map_factory, opts);

app.get("/", (req, res) => {
  res.send("Hello World, express & mapnik!");
});

app.get("/generate_map", (req, res) => {
  const mapPromise = pool.acquire();
  mapPromise
    .then(function(map) {
      var easting = +req.query.easting;
      var northing = +req.query.northing;
      var bbox = [easting - 1000, northing - 1000, easting + 1000, northing + 1000];
      map.zoomToBox(bbox);
      const im = new mapnik.Image(4*256,4*256);
      map.render(im, function(err, im) {
        if (err) throw err;
        im.encode('png256', function (err, buffer) {
          if (err) throw err;
          res.type('png');
          res.send(buffer);
          console.log(`==> pid:${pid} req(x:${easting} y:${northing}) res(size:${buffer.length})`);
          pool.release(map);
        });
      });
    })
    .catch(function(err) {
      res.send(`FAIL:${err}`);
    });
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`);
});


process.on('SIGINT', function() {
  pool.drain().then(function() {
    pool.clear();
  });
});
```

**Comment by JaylanChen** [comment]
Generally, the small amount of data (the amount of data covered by a single tile picture) will not continuously increase in memory; when the amount of data is relatively large (the threshold is not clear), it will not be released.

I use the thumbnail of the entire map to reproduce the scene where a single tile picture contains a large amount of data.


I downloaded the [osm us-pacific data](us-pacific) and imported it into the pg db using [osm2pgsql](https://osm2pgsql.org).
```bash
osm2pgsql -d osm-us-pacific -U postgres -P 5332 -H 192.168.1.121 -U postgres -W -C 25000 us-pacific-latest.osm.pbf
```
I updated the test code adding logic to the pool of the map instance.(This is similar to your test code, and the same as real use).

After the service starts, the memory takes up about 95mb.
![image](https://github.com/user-attachments/assets/146d7f7c-163e-4ab4-84da-9049a30af9e1)


http://localhost:3000/genpg
The first time: 447mb
![image](https://github.com/user-attachments/assets/4ada2410-d607-4f36-9cc9-03aebe24e584)
If requested again, the memory will also be increased.
the second time: 862mb
![image](https://github.com/user-attachments/assets/c712971a-bc95-4090-98d8-cf40008eca09)
the third time: 928.9mb 
the fourth time: 931.6mb
![image](https://github.com/user-attachments/assets/7dbf30a5-99eb-4388-804f-f5a9175b6978)

If there is no concurrency (instances remain minimum 2), the memory stabilizes but is not released. If concurrency occurs, such as 4 requests, two more instances are created and the memory is increased again. (1.7gb)
![image](https://github.com/user-attachments/assets/5e2c888a-13fa-4e42-80e1-a579ac5cb1aa)
![image](https://github.com/user-attachments/assets/55037a4a-3922-4210-af67-2bdd5290706e)

An instance takes up so much memory, is there something wrong?

**Comment by artemp** [comment]
@JaylanChen - I'm wondering if "forking" processes might be related to this issue. Could you try "cluster" mode e.g

```js
module.exports = {
  apps: [
    {
      name: 'mapnik-test',
      script: './src/app.js',
      instances : "4",
      exec_mode : "cluster"
    },
  ],
};
```

**Comment by JaylanChen** [comment]
> @JaylanChen - I'm wondering if "forking" processes might be related to this issue. Could you try "cluster" mode to see if memory usage pattern changes? e.g
> 
> ```js
> module.exports = {
>   apps: [
>     {
>       name: 'mapnik-test',
>       script: './src/app.js',
>       instances : "4",
>       exec_mode : "cluster"
>     },
>   ],
> };
> ```

## full table data
Initial state memory
![image](https://github.com/user-attachments/assets/daf2a3d6-2aab-45e1-9263-1ac681c31b2b)

the first request, the node with id 1 is responsible for processing the request:
![image](https://github.com/user-attachments/assets/3e9b85f3-bcf9-4fb1-8c3e-2580f17ffc88)
![image](https://github.com/user-attachments/assets/8fa7e90b-1d2e-42a9-b408-ce8989593df6)

the second request, the node with id 3 is responsible for processing the request:
![image](https://github.com/user-attachments/assets/78e7d643-e599-475a-9b8f-bbaf707e40a0)
![image](https://github.com/user-attachments/assets/79388037-f308-4195-8286-c434dd4a8f56)

the third request, the node with id 1 is responsible for processing the request: 
![image](https://github.com/user-attachments/assets/cb82fa90-12af-4eb1-b235-7690366b6a96)
![image](https://github.com/user-attachments/assets/ba536308-4ff0-43cf-a296-e21bef231112)


pm2 restart pm2.config.js
![image](https://github.com/user-attachments/assets/28a9e20d-8edc-4e5b-8e46-495fbbd8f871)

### concurrent with 20 requests

![image](https://github.com/user-attachments/assets/c1a4b58b-a5f7-4a10-91d4-1b7dac9d7498)
![image](https://github.com/user-attachments/assets/1797a196-8c25-4f0e-b762-cef260daa846)
![image](https://github.com/user-attachments/assets/ca466a54-ee8a-4ec9-80f4-b54d40c91d1a)
![image](https://github.com/user-attachments/assets/ef28efa6-bd8a-4b91-bcb3-2667be30f7ed)

five mapnik instances were created for each node (two were already created when the pool was initialized). the memory of each node is about the same.
![image](https://github.com/user-attachments/assets/fd8a3e02-a05a-4280-8e70-464d50ae266d)
![image](https://github.com/user-attachments/assets/2a91ee0c-505a-48ed-8152-073a5e2f2e93)

concurrent with 20 requests again. reuse the map instance, with less memory increase.
![image](https://github.com/user-attachments/assets/ce39bb7b-a912-4095-9203-9bf8fccfe24b)
![image](https://github.com/user-attachments/assets/96069b40-b9c2-4017-94cd-4e94d131bb1b)


## 
```
(select * from planet_osm_polygon where way_area < 50) as t1
```
### 3 separate requests.
![image](https://github.com/user-attachments/assets/74171e65-0f75-4baa-b73d-d37661f7fe2d)

pm2 restart pm2.config.js

### concurrent with 20 requests
due to the small amount of data, the single request time is short, with only 3 nodes, and an additional instance is created.
the node with id 1 creates no additional map instance and has a little smaller memory than the other nodes.

![image](https://github.com/user-attachments/assets/44489c88-2daf-4393-a816-0255863f1b6f)
![image](https://github.com/user-attachments/assets/cfb44520-915c-47fb-a315-dd98bff6469b)
![image](https://github.com/user-attachments/assets/fb4f63db-da5f-4002-b18e-6c999bbe0800)
![image](https://github.com/user-attachments/assets/f53b5c06-5eb8-455e-a2ed-1ff3059a46d4)
![image](https://github.com/user-attachments/assets/43949a4c-074f-4962-a1d2-7b156f485bfb)

HTP.

**Comment by artemp** [comment]
@JaylanChen - It looks like defining NAPI_EXPERIMENTAL improves memory management of a running node process. I'm going to do more testing and if everything is OK I'll release development package for you to give it a try. 

ref -> https://github.com/nodejs/node-addon-api/issues/1213

**Comment by JaylanChen** [comment]
When the new development package is released, please let me know that I can help test the validation.

**Comment by JaylanChen** [comment]
> @JaylanChen => `npm install @mapnik/mapnik@4.6.6-dev`
> 
> Give a try and let me know ^

Same as in the previous version.

I have also tested the following code
```
'use strict'
const mapnik  = require("@mapnik/mapnik");

for (var i = 0; i < 10000000; ++i)
{
  var im = new mapnik.Image(256, 256);
  if (i % 10000 == 0)
  {
    const memoryUsage = process.memoryUsage();
    console.log('Memory Usage:', memoryUsage);
    // if (global.gc) {
    //   global.gc();
    // } else {
    //    console.log('Garbage collection unavailable.  Pass --expose-gc '
    //                + 'when launching node to enable forced garbage collection.');
    // }
  }
}
```
![image](https://github.com/user-attachments/assets/61893f3b-894d-4f23-95ea-3c3cd4c8cc8f)

**Comment by artemp** [comment]
@JaylanChen  - my mistake, I built using `node v20` headers on `linux-x64`. I just published new dev package for you to test on linux x86_64  - `npm install @mapnik/mapnik@4.6.6-dev2`

Following script now completes for me (before was running out of memory, including `@mapnik/mapnik@4.6.6-dev`)
RSS is still growing slightly over time, but overall memory usage is significantly better (hoping I published correct prebuilds 🤞) 

```js
const mapnik  = require("@mapnik/mapnik");

for (var i = 0; i < 10000000; ++i)
{ 
  const im = new mapnik.Image(256, 256);
  if (i % 1000 == 0)
  {
    const memoryUsage = process.memoryUsage();
    const json = JSON.stringify(process.memoryUsage())
    console.log(`\nCount=${i} Memory Usage:${json}`);    
  }
}
```

**Comment by artemp** [comment]
@JaylanChen 

Adding missing context here - 

* npm install @mapnik/mapnik@4.6.6-dev2 
`NAPI_EXPERIMENTAL=1`  +  [`AdjustExternalMemory`](https://github.com/nodejs/node-addon-api/blob/main/doc/memory_management.md).
`AdjustExternalMemory` is called every time`mapnik.Image` creation or destruction. Memory usage comparable to [`Buffer.alloc`](https://nodejs.org/api/buffer.html#buffer) but poor performance when allocating many objects in a tight loop (similarly to `Buffer`)

* npm install @mapnik/mapnik@4.6.6-dev3
`NAPI_EXPERIMENTAL=1`  better memory management as finalizers are called more often.

* **SOLUTION!** - cache and reuse `mapnik.Image` together with `mapnik.Map` object in a pool  e.g `[image, map]` - low memory impact + less memory allocations => better performance 

Not accounting for external memory allocations in c++ land is a design choice. The whole issue is easily mitigated with caching/reusing of `mapnik.Image` objects. I'm leaning towards leaving things as the are for the time being. Hope this makes sense, let me know.

**Comment by JaylanChen** [comment]
Sorry for not testing the feedback in time.
In my test, 4.6.6-dev2, 4.6.6-dev3 is the same as before;
node： v22.11.0

Is there something wrong with my test code?

I have a question, why universal code, but different data filter conditions, different memory usage?

- v4.6.6-dev2

| filter conditions | data count | initial mem | once req /genpg | mem increase |
| ----------------- | ---------- | ----------- | --------------- | ------------ |
| None              | 687099     | 102mb       | 454mb           | ≈352mb       |
| way_area < 50     | 21572      | 102mb       | 107mb           | ≈5mb         |
| way_area >= 50    | 665527     | 103mb       | 451mb           | ≈348mb       |
| way_area < 30000  | 496391     | 103mb       | 210mb           | ≈107mb       |
| way_area >= 30000 | 190708     | 102mb       | 350mb           | ≈248mb       |

- v4.6.6-dev3

| filter conditions | data count | initial mem | once req /genpg | mem increase |
| ----------------- | ---------- | ----------- | --------------- | ------------ |
| None              | 687099     | 99mb        | 451mb           | ≈352mb       |
| way_area < 50     | 21572      | 99mb        | 104mb           | ≈5mb         |
| way_area >= 50    | 665527     | 98mb        | 448mb           | ≈350mb       |
| way_area < 30000  | 496391     | 98mb        | 206mb           | ≈108mb       |
| way_area >= 30000 | 190708     | 98mb        | 347mb           | ≈249mb       |

According to the current phenomenon, when rendering the tile image, the corresponding data still occupies the memory. Should the data usage be released?
Is it more reasonable to keep only the memory of the map instance?

**Comment by artemp** [comment]
@JaylanChen  - thanks for helping testing memory usage. I had a chance to look into this again. I loaded `us-pacific-latest.osm.pbf` and used `way_area >= 50`/`way_area < 50` filters in *.xml.  I'm observing increased  memory usage when query returns many features as in your table above ^.  

The issue (as I understand) is that memory allocations in native c++ code are not accounted for by JS GC. This is by design and the only way to trigger more frequent GC sweeps is to use `NAPI::AdjustExternalMemory` which best avoided (performance!). 

It seems consensus is that unless high RSS usage causes OOM it can be ignored and JS GC will do the right job managing process(s) memory e.g 
https://github.com/nodejs/help/issues/4141#issuecomment-2016291166 

I also tested sync and async versions of loading `mapnik.Map`, creating `mapnik.Image` and rendering in a loop in valgrind 
( ref https://github.com/nodejs/node/blob/main/doc/contributing/investigating-native-memory-leaks.md ). 
I'm seeing small amounts (100 bytes-1K) of unaccountable memory on exit. This is expected and I don't see this as an issue.

Can you trigger OOM or you're just concerned about high RSS usage?

**Comment by JaylanChen** [comment]
I have read the above instructions and understood the difference in memory management between node and c + +;

Yes, I am more concerned about high RSS usage; because in previous use, memory increases too fast due to individual tile requests (many features); causing insufficient memory errors.

Next, I will try to set the maximum node memory and see if I can avoid this problem.

Thank you for your help.

I ll close this issue first and create a new issue if there are other issues.
If you can open the sponsor, so I can give you a cup of coffee to express my thanks.

**Comment by elukey** [comment]
@artemp @JaylanChen Hi! Thanks a lot for the above useful discussion, at Wikimedia we have upgraded our [Kartotherian](https://wikitech.wikimedia.org/wiki/Maps/Kartotherian) service to node-mapnik 4.6.1 and mapnik 4.0.2 (from very old versions) while migrating the service to Kubernetes. We are now seeing the same issue, RSS increasing and used heap staying constant. I have a few questions for you if you have time:

1) Do you have any suggestions about how to implement caching for `mapnik.Image`? Is a proper pool need (like https://github.com/coopernurse/node-pool) or something less elaborated works as well? I'd like to understand how much one should "protect" the mapnik.Image object from concurrent access.

2) I noticed in the CHANGELOG that up to version 4.9.x there were multiple performance enhancements, like NAPI_EXPERIMENTAL etc.. Are those going to improve this issue, or did you find out that only a proper pool permanently solves the problem?

Thanks in advance!

**Comment by JaylanChen** [comment]
@elukey 
I haven't tested yet to see if reusing maonik.Image is helpful. 
But looking at another #950, reusing Image should help. 

[ implemented reusing mapnik.Image instances](https://github.com/mapnik/node-mapnik/issues/950#issuecomment-674031716)
