### ISSUE TITLE
WKT Support for Memory Datasource

### ISSUE THREAD

**Issue by rcoup** [mapnik/node-mapnik#134]
Looking to do some memory datasource hacking, but I ran into this:

    if (obj->Has(String::New("wkt")))
        return ThrowException(Exception::Error(
            String::New("wkt not yet supported")));
(at [`MemoryDatasource::add()`](https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_memory_datasource.cpp#L224) )

Being my typical PITA, I need a polygon :) So... just need to implement via `Geometry.fromWKT()` and abstract out the properties handling?

**Comment by springmeyer** [comment]
Added the ability to create a Feature in memory from GeoJSON feature in https://github.com/mapnik/node-mapnik/commit/782eb61e36deccd821851956a1fe82f6d9bc1226#diff-7ff998f9ce37e69f1a22636ba887f66f. That should address some of this need (aka. GeoJSON is better than WKT). Also for completely in member GeoJSON FeatureCollections you can also now do:

```
ds = new mapnik.Datasource({
  'type': 'geojson',
  'inline': <geojson feature collection>
})
```
