### ISSUE TITLE
VectorTile GeoJSON Multipart-polygon issue

### ISSUE THREAD

**Issue by maxprogram** [mapnik/node-mapnik#159]
After converting some PostGIS country data into Vector Tiles using tilelive-bridge, I retrieved the layer as GeoJSON. However this is how the GeoJSON looks rendered through D3 on the browser: ( *vector layer over a simple PNG background* )

![geojson_test](https://f.cloud.github.com/assets/1264406/711626/c5697e3a-de96-11e2-8f07-e6d3aaeda11e.jpg)

I'm thinking this is an issue with the translation to multipart polygons? It doesn't seem to be a problem with the data because the rendered PNGs look fine.

**Comment by springmeyer** [comment]
This is now fixed in latest node-mapnik (>= 3.1.3). The specific commit was https://github.com/mapnik/node-mapnik/commit/fe661045a245c00716683575fb6a4ca81c18bb73#diff-025892f16dfcbfcdb924aa250d278956.
