### ISSUE TITLE
abort rendering

### ISSUE THREAD

**Issue by plepe** [mapnik/node-mapnik#222]
I'm using the [Landspeed WMS](https://github.com/mapbox/landspeed.js) - or rather an improved version which can serve several Mapnik styles. Often it happens that the user moves the map before rendering is complete. Mapnik continues rendering, although the map will never be shown to the user.

When the map moves, the http request is aborted (by Leaflet) which calls the 'close' event on the NodeJS http handler. But how to abort the rendering process? I haven't even found a function in mapnik itself (maybe I should have created the issue there?), though I found some issues which could be related (mapnik/mapnik#2069, mapnik/mapnik#632).

**Comment by BHare1985** [comment]
Whatever became of this? I think this is a great feature.

**Comment by springmeyer** [comment]
@BHare1985 still just an idea. Would need solid concepting both in Mapnik core and node-mapnik (and other bindings). Since we are focused on 3.0.0 release, it is unlikely to get attention in the next month.

**Comment by knutole** [comment]
:+1:

**Comment by zdila** [comment]
@springmeyer 3.x has been released already. So how about next month? ;-)
