### ISSUE TITLE
node-mapnik renders shapefile as a blank screen under x86 windows 7.

### ISSUE THREAD

**Issue by germanjoey** [mapnik/node-mapnik#255]
Hello,

I'm trying to run through this node-mapnik tutorial:

http://build-failed.blogspot.com/2014/04/generating-server-side-tile-maps-with.html

I'm running windows 7, and was able to get node-mapnik to install with the method described in Issue #240; 191 out 196 tests passed when I ran npm test.  Unfortunately, running the example code (after making one small adjustment, changing mercator.xyz_to_envelope to mercator.bbox, which is that method's new name) renders a blank blue tile.  No errors are thrown by node-mapnik, and trying to change around the bbox manually does not help.  Since the author has a working copy on his site that's running the same code off the same database, I assume the only difference is our installation of node-mapnik. (he is on a Mac).  

I was able to get mapnik-v2.2.0 to install manually, and get its c++ and python demos to install, but I don't think node-mapnik uses that.  Is there any way I can figure out what is wrong here? One clue my be that node-mapnik complains about not being able to load the gdap and ogr datasources when the server first starts (at the loadDataSources line), although this tutorial uses a shapefile so I don't see why that would matter.

**Comment by meghmalhar** [comment]
hello BergWerkGIS,
I used  var bbox = mercatorO.bbox(x, y, z, false, '900913'); but m getting below error in command prompt when i run the file

var bbox = mercatorO.bbox(x, y, z, false, '9
                     ^
TypeError: Object function SphericalMercator
    options = options || {};
    this.size = options.size || 256;
    if (!cache[this.size]) {
        var size = this.size;
        var c = cache[this.size] = {};
        c.Bc = [];
        c.Cc = [];
        c.zc = [];
        c.Ac = [];
        for (var d = 0; d < 30; d++) {
            c.Bc.push(size / 360);
            c.Cc.push(size / (2 * Math.PI));
            c.zc.push(size / 2);
            c.Ac.push(size);
            size *= 2;
        }
    }
    this.Bc = cache[this.size].Bc;
    this.Cc = cache[this.size].Cc;
    this.zc = cache[this.size].zc;
    this.Ac = cache[this.size].Ac;
} has no method 'bbox'
    at C:\Program Files\nodejs\tile.js:72:22


please help me

**Comment by BergWerkGIS** [comment]
@meghmalhar 

`C:\Program Files\nodejs\tile.js:72:22` looks a bit strange to me.
Why would you put your code into `Program Files`?

Could you share a bit more of your code?
Like what you are doing before the error occurs?

Or even better, [a perfect test case](https://github.com/mapnik/mapnik/wiki/A-perfect-testcase), which is a self contained, stripped down project that contains everything needed to reproduce the problem?

See [above for an example test case](https://github.com/mapnik/node-mapnik/issues/255#issuecomment-43394750)

**Comment by springmeyer** [comment]
@meghmalhar I think the issue is that you are not instanciating the spherical mercator class correctly. See [this usage](https://github.com/mapnik/node-mapnik/blob/master/test/vector-tile.test.js#L7) for an example. Also, this ticket is closed. If you are still having issues please open a new ticket rather than commenting on an old ticket.

**Comment by meghmalhar** [comment]
@springmeyer 
I have already opened new ticket but i dint get any reply on that so i put my query here.
 yes, there were 2 issues in my code
1. i had not initiated  spherical mercator properly.
2. I had not registered default_font() and default_input_plugins().
           mapnik.register_default_fonts();
            mapnik.register_default_input_plugins();

@BergWerkGIS 
nodejs has been installed by default in my C:\Program Files, no issue regarding that.

Issues rectified
Now it is working like a champ :)
thank you for your help :)
