### ISSUE TITLE
Using buffer-size from options instead of map one

### ISSUE THREAD

**Issue by rochoa** [mapnik/node-mapnik#342]
I'm creating this ticket to discuss the changes introduced for the buffer-size option for label collision detector.

@springmeyer explicitly asked me to create it as the plan is to start relying on options instead of map. See: https://github.com/mapnik/node-mapnik/commit/5b823e0a52010e29a5d0c44adc590f9a28f217be#commitcomment-8024534

**Comment by springmeyer** [comment]
closing, never saw a pull request and the new behavior is more consistent going forward. So rule of thumb is `buffer_size` in options now for all render() functions.
