### ISSUE TITLE
Docs sprint

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#352]
Per chat with @GretaCB we should work on a quick docs sprint.

Main tasks:

  - Make sure data API is documented well: mapnik.Datasource/Featureset/Features
  - In particularly integrate toJSON improvements in docs: https://github.com/mapnik/node-mapnik/issues/308
  - Port markdown docs (https://github.com/mapnik/node-mapnik/tree/master/docs) to new format @brianreavis sketched out in https://github.com/mapnik/node-mapnik/tree/documentation

---

Documentation TODO

* [ ] mapnik.Layer
* [ ] Finish mapnik.Map documentation
* [ ] Add at least one example per class
* [x] Polish up documentation style
* [ ] output throws tags https://github.com/documentationjs/documentation/issues/86
* [ ] output undefined returns https://github.com/documentationjs/documentation/issues/62

**Comment by springmeyer** [comment]
@tmcw - thanks for pushing this ahead. Want to re-iterate that I would love to pull in @GretaCB to hone and add some critical docs. Her experience with the performance aspects of Mapnik in production will help highlight key places to cover - e.g. datasource plugin options like `cache_features`.

**Comment by mapsam** [comment]
@springmeyer @GretaCB think we could close this? Docs have been updated heavily since this issue was created.

**Comment by mapsam** [comment]
Closing, docs have been updated quite a bit since this sprint plan!
