### ISSUE TITLE
Eratic errors on concurrent calls to mapnik.Image.fromBytes

### ISSUE THREAD

**Issue by yohanboniface** [mapnik/node-mapnik#360]
Hi Dane :)

I'm fighting since some days with an erratic error on Kosmtik when one uses big metatiles (like 6x6 or 8x8).

It _may_ be that this comes from Mapnik.

I've narrowed down the code and I'm able to reproduce the behaviour, at least a behaviour that really seems to be the same: I've an error from time to time, and the error message itself varies.

Here is a code to reproduce:

``` javascript
var fs = require('fs'),
    mapnik = require('mapnik');

fs.readFile('path/to/a/valid.png', function (err, buffer) {
    if (err) throw err;
    for (var i = 0; i < 100; i++) {
        mapnik.Image.fromBytes(buffer, function (err, im) {
            if (err) throw err;
            else console.log('ok');
        });
    }
});
```

This code fails with errors like:

```
Error: failed to read invalid png: 'bad adaptive filter value'
```

```
Error: failed to read invalid png: 'IDAT: CRC error'
```

```
Error: failed to read invalid png: 'Not a PNG file'
```

```
Error: image_reader: can't determine type from input data
```

And, just if you are curious, here is the real code in Kosmtik: https://github.com/kosmtik/kosmtik/blob/master/src/back/MetatileBasedTile.js (basically, this is a code to handle metatiles, which creates the metatile if needed, reads it otherwise, and cuts the tiles from it; with metatiles until 4x4 I don't see the issue).

I've tested with both versions `1.4.17` and the last tarball from Github.

I may totally be in a misuse of the `fromBytes` method.

Thanks in advance if you have a bit of time to look at this!

Yohan

**Comment by JaredPotter** [comment]
I solved my issue by specifying BOTH the `responseType` and the `Content-Type` header:

```return axios.get(url, {
    responseType: 'arraybuffer',
    headers: {
      'Content-Type': 'image/png',
    },
});```
