### ISSUE TITLE
Failed to install mapnik via npm

### ISSUE THREAD

**Issue by mohsentaleb** [mapnik/node-mapnik#367]
Installation breaks while getting mapnik binary, with 403 error (Access denied) from address: 
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.1.3/v8-3.11-win32-ia32.tar.gz

**Comment by mohsentaleb** [comment]
I think its because of not placing a so called "bucket policy" in s3 console.

**Comment by yhahn** [comment]
@mohsentaleb there are no windows binaries for the mapnik 3.1.3 release yet -- they are coming soon. A workaround is to install mapnik 3.1.2 on windows instead:

    npm install mapnik@3.1.2

**Comment by mohsentaleb** [comment]
@yhahn Thanks, worked like a charm!
