### ISSUE TITLE
Windows: jshint Can't open */*.js

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#369]
```
jshint */*.js && mocha -R spec --timeout 50000
 
ERROR: Can't open */*.js
child_process: customFds option is deprecated, use stdio instead
```

https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.88/job/7gxg9ojf87kcwb5k#L2234

**Comment by springmeyer** [comment]
@rclark mentioned he's going to try to write a wrapper that will work on windows. Hopefully we can steal his work to get this re-enabled after https://github.com/mapnik/node-mapnik/commit/ec7a9a9efce90916a03ca2ba15de1aa0bc206d35

**Comment by Francisc** [comment]
Any news on this? Still happening.

**Comment by menocomp** [comment]
any update? still the same issues.
The only fix for windows is by using directories instead of files as follows:
"lint": "jshint folder_name"
