### ISSUE TITLE
Add image.isSolid

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#376]
We support `ImageView.isSolid` but are missing `image.isSolid`. It would be a small but still nice optimization to avoid needing an ImageView right here: https://github.com/mapbox/tilelive-bridge/blob/44b9c62373f6408d80c534466c6491a284025f6c/index.js#L126-L127 because then we don't need V8 to have to worry about garbage collecting the view.

**Comment by flippmoke** [comment]
This has been updated [here](https://github.com/mapnik/node-mapnik/blob/fe89896ae53f0e895789c2ff5b2e12a4db36cb50/src/mapnik_image.cpp#L727). However, there are no tests for it yet. After that is done we could probably close this ticket.

**Comment by flippmoke** [comment]
Fixed and merged
