### ISSUE TITLE
Add package.json "bin" scripts for shapeindex, nik2img

### ISSUE THREAD

**Issue by rclark** [mapnik/node-mapnik#378]
As a convenience what if there were executable scripts like `bin/mapnik-shapeindex.js` functions that looked like: https://gist.github.com/rclark/f83262655df797442e95?

This helps the end-user utilize the executable without tracking it down in the file system. Also means that a library that depends on node-mapnik could call the executable via `node_modules/.bin/mapnik-shapeindex`.

What do you think @springmeyer?

**Comment by springmeyer** [comment]
Great idea. Only additional thought is that we'd want tests to validate the command is working (so it does not regress without noticing). Maybe like https://github.com/mapbox/mapnik-omnivore/compare/fix-digest-bin.

**Comment by rclark** [comment]
So I think that the problem is that child_process exec, spawn calls have to be a little different on windows. You can't just `exec('bin/mapnik-shapeindex.js --shape_files mine.shp')`, because windows can't directly interpret that file. npm does trickery to make windows executables that can be used when you install the module with `-g`.

This is my current hypothesis, at least.

**Comment by springmeyer** [comment]
oh right. They need a corresponding .cmd file I think. Gah, my understand of this is murky but I do know I got node-pre-gyp tests calling node-pre-gyp working that use exec: https://github.com/mapbox/node-pre-gyp/blob/master/test/build.test.js#L25. And wattayaknow, I have a .cmd file here: https://github.com/mapbox/node-pre-gyp/blob/master/bin/node-pre-gyp.cmd
