### ISSUE TITLE
Hold on release until postgis regression is resolved

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#388]
There might be a regression in postgis support https://github.com/mojodna/tl/issues/3#issuecomment-73955887. Need to hold on 3.1.5 till this is ruled out.

**Comment by flippmoke** [comment]
I am not certain we need to hold on this @springmeyer it seems to be an issue in the XML file, not in mapnik?

**Comment by springmeyer** [comment]
solved in https://github.com/mapnik/mapnik/issues/2704. @BergWerkGIS - possible for you to regenerate a new Mapnik 3 SDK with this commit? https://github.com/mapnik/mapnik/commit/1ebd6afd9cba1629261b7d7e06473f242b64819b
