### ISSUE TITLE
Build new v3.1.5 binaries

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#390]
All known bugs are now fixed, but they require pulling in latest Mapnik, so we'll need new Mapnik 3 SDK for:

  - [x] linux (@springmeyer)
  - [x] os x  (@springmeyer)
  - [x] windows (@BergWerkGIS)

With at least https://github.com/mapnik/mapnik/commit/1ebd6afd9cba1629261b7d7e06473f242b64819b.

**Comment by BergWerkGIS** [comment]
__x86:__
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x86-v3.0.0-rc1-464-g1ebd6af.7z

__x64:__
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-464-g1ebd6af.7z
