### ISSUE TITLE
mapnik-swoop tests passing

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#392]
To get mapnik-swoop tests passing (https://travis-ci.org/mapbox/mapnik-swoop/jobs/50429625) it looks like we'll need:

  - [x]  New binaries/point to master node-mapnik (#390)
  - [x] mapnik-omnivore master to fix its version to be the latest release which should avoid the duplicate node-gdal and node-srs installs that are happening (https://github.com/mapbox/mapnik-omnivore/issues/86)
  - [x] Update the tests (using `UPDATE=1 npm test` where needed to recreate visual fixtures) and creating new tickets at each app for any changes that might need testing or discussion:
   - [x] tilelive-bridge
   - [x] tilelive-vector
   - [x] geojson-mapnikify
   - [x] mapnik-omnivorew

**Comment by flippmoke** [comment]
Branches to Merge After Release:
- [ ] https://github.com/mapbox/tilelive-vector/pull/92
