### ISSUE TITLE
npm install mapnik failing in freebsd 10.1 as part of Tilemill build

### ISSUE THREAD

**Issue by PeterSprague** [mapnik/node-mapnik#395]
Installed mapnik via ports with no errors.
setenv CXX clang++
setenv CC clang
Now attempting to npm install in tilemill.git

gives error:
----------------------------------------------------------
> mapnik@3.1.5 install /usr/local/tilemill/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

gmake: Entering directory '/usr/local/tilemill/node_modules/mapnik/build'
  ACTION binding_gyp_action_before_build_target_generate_protoc_files Release/obj/gen/vector_tile.pb.cc
  ACTION binding_gyp_action_before_build_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /usr/local/tilemill/node_modules/mapnik/lib/binding/node-v11-freebsd-x64/mapnik_settings.js
  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/mapnik/src/json_proj_transform_grammar.o
../src/json_proj_transform_grammar.cpp:1:10: fatal error: 'mapnik/json/geometry_generator_grammar_impl.hpp' file not found
#include <mapnik/json/geometry_generator_grammar_impl.hpp>

-------------------------------------------------------------
From tilemill/ npm-debug.log
1147 info install tar-pack@2.0.0
1148 info postinstall tar-pack@2.0.0
1149 info install node-pre-gyp@0.6.2
1150 info postinstall node-pre-gyp@0.6.2
1151 info install mapnik@3.1.5
1152 verbose unsafe-perm in lifecycle false
1153 info mapnik@3.1.5 Failed to exec install script
1154 verbose unlock done using /root/.npm/_locks/mapnik-dcdffebe5eb2f992.lock for /usr/local/tilemill/node_modules/mapnik
1155 verbose stack Error: mapnik@3.1.5 install: `node-pre-gyp install --fallback-to-build`
1155 verbose stack Exit status 1
1155 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
1155 verbose stack     at EventEmitter.emit (events.js:98:17)
1155 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
1155 verbose stack     at ChildProcess.emit (events.js:98:17)
1155 verbose stack     at maybeClose (child_process.js:766:16)
1155 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
1156 verbose pkgid mapnik@3.1.5
1157 verbose cwd /usr/local/tilemill
1158 error FreeBSD 10.1-RELEASE-p16
1159 error argv "node" "/usr/local/bin/npm" "install"
1160 error node v0.10.35
1161 error npm  v2.1.18
1162 error code ELIFECYCLE
1163 error mapnik@3.1.5 install: `node-pre-gyp install --fallback-to-build`
1163 error Exit status 1
1164 error Failed at the mapnik@3.1.5 install script 'node-pre-gyp install --fallback-to-build'.
1164 error This is most likely a problem with the mapnik package,
1164 error not with npm itself.
1164 error Tell the author that this fails on your system:
1164 error     node-pre-gyp install --fallback-to-build
1164 error You can get their info via:
1164 error     npm owner ls mapnik
1164 error There is likely additional logging output above.
1165 verbose exit [ 1, true ]
1166 verbose unbuild node_modules/mapnik
1167 info preuninstall mapnik@3.1.5
1168 info uninstall mapnik@3.1.5
1169 verbose unbuild rmStuff mapnik@3.1.5 from /usr/local/tilemill/node_modules

------------------------------------------------------------------------------------------------------------------------------------------

I've built Tilemill on this machine before under FreeBSD/PCBSD 10.0, but won't build under 10.1

Peter

**Comment by springmeyer** [comment]
node-mapnik 3.x only supports mapnik 3.x (current mapnik master). If you want to build node-mapnik from source against Mapnik 2.x, then you need node-mapnik 1.7.x series: https://github.com/mapnik/node-mapnik/tree/v0.7.x.

I would recommend you use tilemill master + mapnik master + node-mapnik 3.1.x.

**Comment by GEInformatics** [comment]
Ah, so I mistakenly have a node-mapnik to mapnik version mismatch?
Thanks for being quick with the feedback.
I'll sort it in the morning, and close this issue.

Peter

**Comment by PeterSprague** [comment]
Mapnik master won't build -> moved to open issue at Mapnik.  See above link.
