### ISSUE TITLE
Windows: Use correct paths when updating to new mapnik-sdk 

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#396]
Note to self:
Paths have changed: `libs` -> `lib`, `includes` -> `include`.

https://github.com/mapnik/node-mapnik/blob/master/scripts/build_against_sdk_02-copy-deps-to-bindingdir.ps1

https://github.com/mapnik/mapnik-gyp/commit/15605f94c060bdf9505f135aaf6b6e493fae82d2#diff-12de9bf95f13935db3eff91909008cc4R42

**Comment by springmeyer** [comment]
Pretty sure we hit all these :) Closing.
