### ISSUE TITLE
Mapnik 3.2.0 Changelog

### ISSUE THREAD

**Issue by flippmoke** [mapnik/node-mapnik#399]
Compiling a list of changes associated with 3.2.0

**Comment by flippmoke** [comment]
@springmeyer What else needs to be in the changelog?

**Comment by springmeyer** [comment]
@flippmoke hmm, what do you see needing to be added? I notice https://github.com/mapnik/node-mapnik/pull/405 needs a mention and we need an brief entry on what changed in mapnik/mapnik-packaging.

**Comment by pnorman** [comment]
> @flippmoke hmm, what do you see needing to be added? I notice #405 needs a mention and we need an brief entry on what changed in mapnik/mapnik-packaging.

aren't the only changes in mapnik-packaging mapnik changes, not node-mapnik?

**Comment by flippmoke** [comment]
Remind me, what changed in mapnik packaging?

**Comment by springmeyer** [comment]
@flippmoke - just added the changes capturing a few deps that I upgraded: e37e1cd

@pnorman - because we package binaries and they include deps this is why mapnik-packaging (which controls dep versions) needs to be documented.
