### ISSUE TITLE
Raster blending renders differently to PDF and SVG than to PNG

### ISSUE THREAD

**Issue by averas** [mapnik/node-mapnik#400]
This is perhaps a known issue, and related to the mapnik output plugins rather than node-mapnik, but anyway...

When I blend two raster layers (either using opacity, or comp-op:grain-merge), I get expected results when producing png's, but the blending does not work for pdf and svg exports; one layer completely covers the other, with full alpha.

Is this expected behaviour?

**Comment by springmeyer** [comment]
Compositing at the "style" level (e.g. `<Style comp-op="..." opacity=".."/>`) is only implemented for the AGG rendering backend. So, it is expected that these options do nothing for PDF output (which uses the "Cairo" backend).

Compositing at the feature level (e.g. `<PolygonSymbolizer comp-op="..." />`) is supported for the Cairo backend. Although it often triggers rasterization of vector features, which may not be desirable.

**Comment by averas** [comment]
Ah, got it! Thanks!
