### ISSUE TITLE
vt.query: restrict results further

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#403]
`vt.query/queryMany` should likely only return results for which the shortest distance is < the tolerance value. Or we could introduce another parameter (`minimum_distance`) which would be used as a cutoff.

refs https://github.com/mapbox/carmen/commit/7bb45fe5794ef34dfc2ad5eaae32a198d9b18f49

/cc @yhahn @bsudekum

**Comment by bsudekum** [comment]
> shortest distance is > the tolerance value

This sounds like the best way forward. Either way, it'd be great if I could do some surface testing prior to merging.

**Comment by springmeyer** [comment]
@bsudekum - excellent. Some surface testing will be good timing as well because #402 opens to door to raster raster queries.

**Comment by yhahn** [comment]
Happy to work on this since it's fresh in my head -- should be easy to pull together a testcase + implement.

**Comment by springmeyer** [comment]
this has landed in v3.2.x
