### ISSUE TITLE
Revisit getPixel API

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#404]
Ticket standing as a reminder to:

  - review all functions that return pixel values like `getPixel` and `isSolid`
  - ensure return types are consistent: numbers (by pixel type) vs mapnik.Color
  - ensure top speed: remove mapnik.Color usage if it still exists anywhere

Potentially small breakages hence `3.2.x` milestone.

refs #402

**Comment by flippmoke** [comment]
It seems that the slowest part is the creation of the new `Color` object in V8 memory space here:

https://github.com/mapnik/node-mapnik/blob/release/image_any/src/mapnik_image.cpp#L288

**Comment by flippmoke** [comment]
After some consideration, I have decided upon to change the interface for getPixel. Rather then by default returning `Color` objects for RGBA8 images,  it will return an integer. However, to still provide a way for color objects to be returned, I have added additional parameter to getPixel. 

```
value_is_int = image.getPixel(0,0);
value_is_int2 = image.getPixel(0,0,false);
value_is_color = image.getPixel(0,0,true);
```

I will be making these changes to the python bindings as well.

**Comment by artemp** [comment]
@flippmoke - good call, getPixel() should return value_type not a color object

**Comment by artemp** [comment]
@flippmoke - see, comment above re: get_color and while we at it lets get rid of 'cAmeL' case names.

**Comment by flippmoke** [comment]
@artemp removing camel case from everything would change a lot of the API, not sure if we want to do this or not?

**Comment by artemp** [comment]
@flippmoke - ok, I was talking about c++!  node-mapnik APIs can stay the way they are but mapnik image c++ and Python apis should use ```lower_case_underscore``` names

**Comment by flippmoke** [comment]
@artemp they are :+1:

**Comment by springmeyer** [comment]
@flippmoke in JS generally I recommend `func(arg,arg,options)` instead of `func(arg,arg,boo)`. This is a better design because:

1) you won't break API if you think of another option you want to pass in the future
2) makes optional args more explicit

So I propose amending your changes to make the third arg expect an options object. Then the code internally would look inside that options argument for a property like  `get_color:true`.

**Comment by flippmoke** [comment]
I will change and post update here soon
