### ISSUE TITLE
Node v0.12.0

### ISSUE THREAD

**Issue by pnorman** [mapnik/node-mapnik#411]
My system has node v0.12.0.

Do I need to install a parallel copy of 0.11.x for node-mapnik? "Node v0.10.x or v0.11.x" are listed as the dependencies.

**Comment by pnorman** [comment]
Is v3.1.6 what you get with `npm install node-mapnik`? I was getting errors with it and 0.12.0 which I fixed by downgrading node.

I am of course stuck using the 1.x branch.

**Comment by springmeyer** [comment]
> Is v3.1.6 what you get with npm install node-mapnik?

Yes: https://www.npmjs.com/package/mapnik

>  I was getting errors with it and 0.12.0 which I fixed by downgrading node.

What errors?

**Comment by pnorman** [comment]
I'm having trouble reproducing with node-mapnik 3.x - in part because I can't use it. I did get the error reproduced with the latest release branch, 1.4.17

```
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/node_mapnik.cpp:226:9: error: no matching member function for call to 'Set'
        NODE_MAPNIK_DEFINE_CONSTANT(composite_ops, "src_in", mapnik::src_in)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/utils.hpp:32:15: note: expanded from macro 'NODE_MAPNIK_DEFINE_CONSTANT'
    (target)->Set(NanNew(name),                                         \
    ~~~~~~~~~~^~~
/home/pnorman/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/home/pnorman/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/node_mapnik.cpp:227:9: error: no matching member function for call to 'Set'
        NODE_MAPNIK_DEFINE_CONSTANT(composite_ops, "dst_in", mapnik::dst_in)
```
