### ISSUE TITLE
Build from source fails when used aginst current mapnik/master

### ISSUE THREAD

**Issue by anandthakker** [mapnik/node-mapnik#412]
I've just installed mapnik, from source, off the master branch.

Then, trying to install node-mapnik using `npm install mapnik@3.1.x`, I get the following build error:
```
In file included from ../src/node_mapnik.cpp:18:
../src/mapnik_image_view.hpp:9:10: fatal error: 'mapnik/image_data.hpp' file not found
#include <mapnik/image_data.hpp>        // for image_data_rgba8
```

It works fine if I install off the master branch instead of 3.1.x (`npm install mapnik/node-mapnik`), but that's not ideal since I've got another package depending on 3.1.x. 

I think this will be resolved when  9377b5e67926094b8038a9a4d4e1d11c79c4056a makes it into a release, so that the latest npm-installable version of node-mapnik is caught up with mapnik/master

**Comment by springmeyer** [comment]
> I think this will be resolved when 9377b5e makes it into a release, so that the latest npm-installable version of node-mapnik is caught up with mapnik/master

Correct, thanks for your patience. This will land this week. Until then please use node-mapnik master. You can point to it from your app's package.json like:

```js
"dependencies": {
 "mapnik": "https://github.com/mapnik/node-mapnik/tarball/master"
}
```
