### ISSUE TITLE
Protect Map Rendering With Mutex

### ISSUE THREAD

**Issue by flippmoke** [mapnik/node-mapnik#416]
Currently we do NOT prevent multiple rendering on a map object and only pipe out a small warning message here and the use of the acquire and release items. We need to implement a mutex in the map object to properly protect rendering.

https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_map.cpp#L1437-L1444

**Comment by springmeyer** [comment]
Because a pool is the recommended approach to avoid problems, with the pooled approach a mutex would unnecessary slow down rendering. So currently there is a tradeoff `fast, safe rendering with pooled  maps` at the cost of being easy to misuse. Misuse - as you know - will trigger crashes when maps use datasources which hold state at the datasource level (vs only at the featureset level) as per https://github.com/mapnik/mapnik/issues/2521

**Comment by flippmoke** [comment]
@springmeyer We are already eating some processing power just simply by having that branching code to check and put that error message, will a mutex really slow it down that much more?

**Comment by mikemorris** [comment]
@kkaefer is currently working on a similar problem in mapbox-gl-native, where rendering threads expect the style/source to be immutable, although it currently isn't. Would it be possible to handle state in a different place as an alternative solution?

**Comment by springmeyer** [comment]
>  Would it be possible to handle state in a different place in mapnik as an alternative solution?

@mikemorris - yes, this is what I feel is the best design. The plan in mapnik is to move state to: 1) `mapnik.Request` object that stores all mutable rendering details like bbox/srs/width/height, etc and 2) finish mapnik/mapnik#2521 (which is about moving state in datasources to the `featureset` object that gets created anew by datasources and is never shared between threads so that `datasource` objects can be stored on the map and immutable. This is already that case for most Mapnik plugins so mapnik/mapnik#2521 is basically about finishing it for all datasource plugins.

Moving on #1 would be easy but because of how serious the API breakage would be I've not seen a good time yet to do it. However once done maps would not need to be pooled and could be treated as immutable during rendering.

In chat @flippmoke raised the point that:

```js
map.render(...., callback);
map.srs = '.....';
```

Would still be non threadsafe, but I consider that a misusage so I'm not that concerned about protecting against it.

**Comment by flippmoke** [comment]
Something like this is what concerns me, it would seem to some that this might be safe, but it is not. 
```javascript
// Load preset map configuration
map.load('stuff.xml', function(err, result_map) {
   result_map.zoomAll();
   result_map.renderFile('file1.png');
});
map.load('stuff2.xml', function(err, result_map) {
   result_map.zoomAll();
   result_map.renderFile('file2.png');
});
```

**Comment by springmeyer** [comment]
@flippmoke even if that were "Safe" (aka not ever going to crash) it is fundamentally wrong usage. I think we both probably feel deeply uneasy about it and my feeling is that preventing it from crashing does not help the core issue that it is a misusage.

**Comment by flippmoke** [comment]
I don't feel like something like this should be considered misusage however:

```javascript
// Prepare a map
// Save map to different outputs
map.renderFile('image.png', {format:'png'}, function(err, result) {});
map.renderFile('image.tiff', {format:'tiff'}, function(err, result) {});
// continue operations while IO occurs for each

**Comment by springmeyer** [comment]
^^ agree that is an unsafe usage now and it would be nice if it were not unsafe. As synced on chat: the question is whether the benefit of being able to safely do that is is worth the complexity of mutexes and whether mutexes would ever limit the highest performance usage (as discussed if the mutex is on the map object, this performance penalty should be minor (untested)).

**Comment by flippmoke** [comment]
@springmeyer I made an example branch with a thread safe map object, adding a single mutex per map object. I haven't done any performance tests on this, but I think it will perform about the same.

**Comment by kkaefer** [comment]
> Would still be non threadsafe, but I consider that a misusage so I'm not that concerned about protecting against it.

While it is acceptable to crash in C land, the node module should never crash. Instead, in this case it should throw an exception indicating that the Map object is currently in use. You don't have to use a mutex to implement that. Instead, you can just add a flag, set it to true when starting to render, and back to false in the callback (which are all called in the same/main thread). Whenever a JS accessor changes anything about the Map object will that flag is set, throw.

**Comment by artemp** [comment]
@kkaefer  - do you mean ```std::atomic<bool> flag``` because otherwise behaviour is undefined when multiple threads trying to modify that flag 

@flippmoke - mutex locking requirement is almost always a sign of poor design.

**Comment by kkaefer** [comment]
@artemp: no, a regular bool is enough: I'm talking about adding this to the node module, not to mapnik itself. All node code is run in the same thread, so access to that variable is synchronized by definition.

**Comment by artemp** [comment]
@kkaefer - gotcha

**Comment by flippmoke** [comment]
> mutex locking requirement is almost always a sign of poor design.

@artemp I don't think it is a sign of a poor design always, and I feel that at sometimes they are reasonable.

> no, a regular bool is enough: I'm talking about adding this to the node module, not to mapnik itself. All node code is run in the same thread, so access to that variable is synchronized by definition.

@kkaefer I don't see the advance of checking a bool over a mutex in this situation. Internally, there will not be a syscall unless there is another item waiting in the queue when unlocking a mutex, so it will only take a few cycles in most situations. Additionally, I feel that managing the complexity of throwing exceptions that might occur from miss use is as much as properly using the mutex. Also the non atomic bool will work as long it is the node mapnik code executed in the main javascript thread, if it is checked in the async thread it should be atomic.

**Comment by kkaefer** [comment]
@flippmoke when you wait to lock a mutex during the accessor in node-mapnik, you're blocking the JavaScript thread. This means the callback which would reset the mutex can never be called and you're deadlocked. Instead, you'd have to queue all accessor actions and replay them once rendering is completed.

**Comment by flippmoke** [comment]
@kkaefer That is not true, it is all about where you place the mutex. Take for example the lock_guard [here](https://github.com/mapnik/node-mapnik/blob/map_mutexes/src/mapnik_map.cpp#L657). It is outside the javascript main thread when the locking occurs. Therefore, it does not unlock back in the javascript main thread, it unlocks when the lock_guard goes out of scope.

**Comment by flippmoke** [comment]
I went ahead an simply took the approach of protecting it with a boolean for now, added errors in case there is multiple rendering of the same map object occuring.
