### ISSUE TITLE
Composite Sync and Async Vector Tile Methods

### ISSUE THREAD

**Issue by flippmoke** [mapnik/node-mapnik#417]
Composite in vector tile should support async methods. 
Additionally: 
- look into using non standard protobuf library for reading
- increase test coverage

**Comment by flippmoke** [comment]
Added the sync capability, and increased coverage on these methods. Still haven't looked at non standard protobuf yet.

**Comment by springmeyer** [comment]
Just sync+async is great (commit looks good!). By non-standard protobuf I mean https://github.com/mapbox/pbf.hpp which is very low level and is more of a mapnik-vector-tile task first I think. We can hit this later and can track at https://github.com/mapbox/mapnik-vector-tile/issues/92.
