### ISSUE TITLE
Mapnik fails to install with IO.js

### ISSUE THREAD

**Issue by JerrySievert** [mapnik/node-mapnik#418]
only versions up to 1.4.10 are shown as available when installing under io.js - though it appears that the package.json file is attempting to allow it.

is this intentional behavior?

```shell
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v1.3.0
npm ERR! npm  v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: mapnik@'>=3.1.6 <3.2.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.1.2","0.2.3","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.3.0","0.3.1","0.4.0","0.4.1","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.6","0.5.7","0.5.8","0.5.9","0.6.0","0.5.10","0.5.5","0.6.1","0.6.2","0.5.11","0.5.12","0.5.13","0.6.3","0.5.14","0.6.4","0.6.5","0.5.15","0.5.16","0.5.17","0.6.7","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.7.7","0.7.8","0.7.9","0.7.10","0.7.11","0.7.12","0.7.13","0.7.14","0.7.15","0.7.16","0.7.17","0.7.18","0.7.19","0.7.20","0.7.21","0.7.22","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.2.1","0.7.24","1.2.2","0.7.25","1.2.3","0.7.26","1.3.0-alpha","1.3.0-alpha2","1.3.0-alpha4","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.4.0-alpha","1.4.0","1.2.4","1.4.1","1.4.2","0.7.27","0.7.28","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.9","1.4.10"]
```

```
$ node --version
v1.5.1
```

**Comment by springmeyer** [comment]
Not intended. IO.js has the same `process.versions.modules` value (`42`) as all previous io.js releases and so the binaries available should work with it. Not sure what is wrong.

**Comment by JerrySievert** [comment]
i had tried it originally on 1.3.0 - the question was asked because there are compiled modules, so was based on compatibility.

**Comment by JerrySievert** [comment]
for the short term, i did `npm install --force` for a working copy.

**Comment by springmeyer** [comment]
Okay, thanks for sharing the workaround.

**Comment by JerrySievert** [comment]
let me know if there's anything i can do to help - haven't had much of a chance to dive in very far, but can spend some time if need be.  my first guess is that the engines selection is a little funky.

**Comment by JerrySievert** [comment]
what i'm seeing is:

```
> semver.satisfies('1.5.1',  ">= 0.8.0 < 0.11.0 || >= 0.11.13 < 0.13.0 || >= 1.2.0 < 2.0.0");
true
```

i can contact some folks at NPM and see if there's something weird going on.

**Comment by springmeyer** [comment]
Ah, right that `engines` logic is out of control. I'm thinking it is less trouble just to remove it. Can you try removing both `engines` and `enginesStrict` and see how things work?

**Comment by JerrySievert** [comment]
i would rather get to the bottom of it - since it parses correctly in semver, it should *just work*.  trying to get some help currently.  if it's a bug for mapnik, it could be a bigger issue.  would rather see this through to the end than to have a simple workaround.

**Comment by JerrySievert** [comment]
looks like it's an npm bug - i've moved it on to them.  going to go ahead and close this.

when you get a chance, can you npm publish with the removed engines?
