### ISSUE TITLE
Using MSSQL as an OGR Datasource does not work

### ISSUE THREAD

**Issue by sjmorrow** [mapnik/node-mapnik#424]
I'm trying to use the [OGR Plugin](https://github.com/mapnik/mapnik/wiki/OGR) to connect Mapnik to a SQL server data source. My Mapnik XML is as follows:
``` xml
<Layer name="tceq_regions_shp"
  srs="+proj=longlat +ellps=GRS80 +no_defs">
    <StyleName>tceq_regions_shp</StyleName>
    <Datasource>
       <Parameter name="type">ogr</Parameter>
       <Parameter name="string">MSSQL:Server=myServer.database.windows.net;Database=DB_NAME;Uid=user@myServer;Pwd=myPassword;Tables=Geo_Tigerline_2014_48_Counties(shape4269);</Parameter>
       <Parameter name="layer_by_sql">SELECT * FROM Geo_Tigerline_2014_48_Counties</Parameter>
    </Datasource>
  </Layer>
```
And I get the following error when I run my application
```
Error: Unable to initialize "tceq-regions" layer: "OGR Plugin: connection failed:
MSSQL:Server=myServer.database.windows.net;Database=DB_NAME;Uid=user@myServer;Pwd=myPassword;Tables=Geo_Tigerline_2014_48_Counties(shape4269); 
was not found or is not a supported format"
```

Is MSSQL functionality missing from the version of GDAL that is being used in the pre-compiled mapnik binaries?

My environment:
* OS = Windows 8.1 64-Bit
* Node Version = v0.11.14 compiled with VC14 (as suggested on Wiki)
* Mapnik binary = node-v0.11.14-win32-x64

Summoning @BergWerkGIS because my gut tells me it's something to do with the Windows pre-built binaries.

Thanks for your time everyone!

**Comment by springmeyer** [comment]
I'm not sure if MSSQL support is build into the GDAL binaries, but yeah that is a good hunch and @BergWerkGIS will know (may be a few days till he answers here since he's traveling atm). Another person who's gotten this working is @jbrwn and he may have helpful ideas.

**Comment by sjmorrow** [comment]
I forgot to mention that when I used ogrinfo that is included with GDAL 1.11.2 with that exact same connection string, it connects fine. Not sure if that is helpful other than to prove there is nothing wrong with my connection string

**Comment by jbrwn** [comment]
@sjmorrow - If you use `layer_by_sql` you should also provide and `extent` parameter.  The short story is that the OGR MSSQL driver does not return in extent when `layer_by_sql` is used.  You need to force one with the extent parameter.   The long story can be found in issue [#1029](https://github.com/mapnik/mapnik/issues/1029)

It also might interest you to know that performance is terrible when `layer_by_sql` is used.  This explained in my last comment in issue [#1029](https://github.com/mapnik/mapnik/issues/1029).  You would be much better off encapsulating your SQL statement in a view and then using the `layer` parameter with the view name.

**Comment by sjmorrow** [comment]
@jbrwn Thanks for that insight. I'll keep that in mind if I ever get this working.

**Comment by jbrwn** [comment]
@sjmorrow No worries.  Hope it saves you a few cycles once you get the connection issue ironed out.

**Comment by sjmorrow** [comment]
I corresponded with @BergWerkGIS via e-mail and he says "it should work". @jbrwn have you successfully been able to connect to MSSQL from node-mapnik in the past? Just wondering if there is some additional build / compile step I can take to get MSSQL working.

**Comment by BergWerkGIS** [comment]
@sjmorrow 
Have you tried the suggested options?
* use `layer_by_sql` and provide extent manually?
* use `layer` and a view?

**Comment by sjmorrow** [comment]
I have, yes. According to [the source](https://github.com/mapnik/mapnik/blob/master/plugins/input/ogr/ogr_datasource.cpp#L152), mapnik doesn't even read those attributes until AFTER where my error is thrown, so I am doubtful that it would have made a difference anyways.

**Comment by BergWerkGIS** [comment]
@sjmorrow thanks for verifying. I'll check tomorrow.

**Comment by BergWerkGIS** [comment]
@sjmorrow I can reproduce your error.
Let's continue at https://github.com/mapbox/windows-builds/issues/37 as this is Windows specific.
