### ISSUE TITLE
Windows:  The specified procedure could not be found

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#427]
There seems to be some regression with `node-mapnik` in conjunction with Mapbox Studio on Windows.
I tried on W7, W8.1 and Server 2012, all the same.

Steps:
* clone mapbox-studio
* copied `node.exe` from Studio installer into clone dir
* `npm install`
  * some errors that dedupe of `node-pre-gyp` failed
* `node index.js` errors with

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.
c:\mb\mapbox-studio-dummy\node_modules\tilelive-bridge\node_modules\mapnik\lib\binding\node-v11-win32-x64\mapnik.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\mb\mapbox-studio-dummy\node_modules\tilelive-bridge\node_modules\mapnik\lib\mapnik.js:26:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I already checked with 
* `DUMPBIN`
* `ctypes.CDLL('mapnik.node')`
* [ProcessMonitor](https://technet.microsoft.com/en-us/sysinternals/bb896645)

But found nothing.

@springmeyer @flippmoke any ideas?

![image](https://cloud.githubusercontent.com/assets/4549888/6900847/b27a01b0-d709-11e4-87c9-b8a373cbfba2.png)

**Comment by BergWerkGIS** [comment]
Forgot: I changed the `node-pre-gyp` version in all modules to `0.6.4` (that's what node-mapnik uses) and run dedupe manually.
Didn't change anything.

**Comment by BergWerkGIS** [comment]
Ahhh, `node-mapnik-3.2.0` branch works out of the box.

However, I solved it by also changing Studio's package.json to `mapnik:3.2.0` and deduping mapnik.

**Comment by springmeyer** [comment]
@BergWerkGIS aha, yes, see https://github.com/mapbox/mapbox-studio/pull/1287. That is just waiting on https://github.com/mapnik/mapnik/commit/51b65534f5b6f11a6403e27de52cbfea66b86958 to trickle through and then all tests should be passing and it can get merged.
