### ISSUE TITLE
Solr Datasource

### ISSUE THREAD

**Issue by mihirsoni** [mapnik/node-mapnik#432]
Hi , 

first of all , this works wonderful  and thanks all for supporting, now I have tried this POSTGIS datasource and it works fine , our infrastructure is in solr and solr does have geosptial datasource , what would be the best way to use Mapnik + solr, is Mapnik lacking support for solr ?

Regards,
Mihir Soni

**Comment by springmeyer** [comment]
closing, discussion happened over at https://github.com/mapnik/mapnik/issues/2760
