### ISSUE TITLE
OS X build error around LTO

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#435]
Never seen this before: https://travis-ci.org/mapnik/node-mapnik/jobs/60632597#L170

> ld: in /Users/travis/build/mapnik/node-mapnik/sdk/mapnik-macosx-sdk-v3.0.0-rc1-1078-gf861df2-lto/lib/libprotobuf-lite.a(message_lite.o), could not parse object file /Users/travis/build/mapnik/node-mapnik/sdk/mapnik-macosx-sdk-v3.0.0-rc1-1078-gf861df2-lto/lib/libprotobuf-lite.a(message_lite.o): 'Invalid value', using libLTO version 'LLVM version 3.5svn' for architecture x86_64

**Comment by springmeyer** [comment]
Figured this out: Apple upgraded their compiler, and I'm now running locally:

```
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

But travis only has:

```
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

And because the Mapnik SDK is built on my machine (because travis is not powerful enough to build it via mapnik-packaging) the LTO signatures break.

Possible solutions are:

  - NOT viable: wait for travis to update their Xcode 
  - Upgrade the compiler on travis: https://github.com/mapbox/mason/issues/73
  - Stop building the Mapnik SDK with LTO (`-flto`)
  - Switch to mason for the Mapnik SDK (this is not ideal to do yet because mason packages are not built with LTO) <-- haha, see the recursive loop?
 
BTW, why LTO? Because Link time optimization shrinks multiple MB's off the binaries. It is also supposed to increase runtime speeds but I've not seen good proof of this yet.

**Comment by springmeyer** [comment]
> Stop building the Mapnik SDK with LTO (-flto)

Went with ^^ for now.

**Comment by gregteng** [comment]
I have the same issue,but i don't understand how you solve this problem.
