### ISSUE TITLE
Failing Vector Tile -> SVG test(s)

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#436]
I'm seeing:

  - all tests are passing on travis (linux and osx)
  - windows is experiencing two test failures around rendering of svg
  - locally on OSX I'm seeing one failure in rendering svg

I've spent some time trying to track this down (worrying about memory corruption), but cannot see the issue so am going to punt for now.

On OS X locally I see:

```
 1) mapnik.VectorTile  should read back the vector tile and render a native svg with it:
    Uncaught AssertionError: svg diff 199720 not less that 10
```

And the `tile0.actual-svg` is missing all the `L` commands (only contains `M`).

On windows the differences look more minor:

```
 1) mapnik.VectorTile  should read back the vector tile and render a native svg with it:
 
      Uncaught AssertionError: svg diff 48 not less that 10
      + expected - actual
 
      +true
      -false
      
      at C:\projects\node-mapnik\test\vector-tile.test.js:937:24
 
  2) mapnik.VectorTile  should read back the vector tile and render a cairo svg with it:
 
      Uncaught AssertionError: svg diff 34 not less that 20
      + expected - actual
 
      +true
      -false
      
      at C:\projects\node-mapnik\test\vector-tile.test.js:965:24
 
```

**Comment by springmeyer** [comment]
more clues:

  - locally svg tests work if I install from the OS X binary travis created and unset DYLD_LIBRARY_PATH (ensuring I'm truly using the remote binary).
  - locally the only differences I can think of: I'm using a more recent clang++ and boost 1.58

**Comment by springmeyer** [comment]
downgrading from boost 1.58 to 1.57 fixed for me locally...

**Comment by artemp** [comment]
@springmeyer ba117c6384978a655d64c67ea48803ad7763ab3e  works with boost 1.58 by simplifiying SVG path generator grammar to output `L` for all LINE_TO

**Comment by springmeyer** [comment]
fixed by https://github.com/mapnik/mapnik/commit/ba117c6384978a655d64c67ea48803ad7763ab3e
