### ISSUE TITLE
Error Building 1.4.17 Windows x64

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#440]
I am attempting to build on Windows 8.1 x64 with VS2013.

I am following : https://github.com/mapnik/node-mapnik/tree/1.x

I downloaded the Visual C++ Redistributable Packages for VS2013 and VS2014 both 32 and 64bit.
I downloaded node-v0.10.38-x86.msi

I then ran `npm install mapnik@1.x` and noticed it tried to build because there are no 32bit binaries for windows for 1.x (not sure why 64 bit binaries aren't included but meh)

I installed Protobuf with 'npm install Protobuf' and then I installed mapnik 2.2 following https://gist.github.com/springmeyer/5651701 and verified both the cpp and python tests worked and set the paths, ensured that mapnik-config works.

I tried `npm install mapnik --build-from-source` and it said

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\act
ion_before_build.vcxproj]

I assuming this means I dont have VS2014 installed so it seemed it was trying to build mapnik 3.x instead of mapnik 1.x so then I tried 

`npm install mapnik@1.x --build-from-source'

And the errors I got were:

C:\Users\Brian\Desktop\Node>npm install mapnik@1.x --build-from-source
npm http GET https://registry.npmjs.org/mapnik
npm http 304 https://registry.npmjs.org/mapnik
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mapnik@1.4.17 install C:\Users\Brian\Desktop\Node\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

C:\Users\Brian\Desktop\Node\node_modules\mapnik>node "C:\ProgramData\chocolatey\
lib\npm.1.4.9\tools\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild --name=mapnik --configuration=Release --module_name=
mapnik --version=1.4.17 --major=1 --minor=4 --patch=17 --runtime=node --node_abi
=node-v11 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64
--module_main=./lib/mapnik.js --host=https://mapbox-node-binary.s3.amazonaws.com
/ --module_path=C:\Users\Brian\Desktop\Node\node_modules\mapnik\lib\binding\node
-v11-win32-x64 --module=C:\Users\Brian\Desktop\Node\node_modules\mapnik\lib\bind
ing\node-v11-win32-x64\mapnik.node --remote_path=./mapnik/v1.4.17/ --package_nam
e=node-v11-win32-x64.tar.gz --staged_tarball=build\stage\mapnik\v1.4.17\node-v11
-win32-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/mapn
ik/v1.4.17/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/mapnik/
v1.4.17/node-v11-win32-x64.tar.gz
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  generate_setting
  generate_protoc_files
  'protoc' is not recognized as an internal or external command,
  operable program or batch file.
  Copying C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\Release\obj/glo
  bal_intermediate/mapnik_settings.js to C:/Users/Brian/Desktop/Node/node_modul
  es/mapnik/lib/binding/node-v11-win32-x64\mapnik_settings.js
          1 file(s) copied.
  node_mapnik.cpp
  blend.cpp
  mapnik_map.cpp
  mapnik_color.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_map.cpp) [C:\Us
ers\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
..\src\blend.cpp(1): fatal error C1083: Cannot open include file: 'mapnik/image
_data.hpp': No such file or directory [C:\Users\Brian\Desktop\Node\node_modules
\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\node_mapnik.cpp) [C:\U
sers\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_geometry.cpp
  mapnik_feature.cpp
  mapnik_image.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_geometry.cpp) [
C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_feature.cpp) [C
:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_image.cpp) [C:\
Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_image_view.cpp
  mapnik_grid.cpp
  mapnik_grid_view.cpp
..\src\mapnik_image_view.cpp(3): fatal error C1083: Cannot open include file: '
mapnik/color.hpp': No such file or directory [C:\Users\Brian\Desktop\Node\node_
modules\mapnik\build\mapnik.vcxproj]
..\src\mapnik_grid_view.cpp(2): fatal error C1083: Cannot open include file: 'm
apnik/grid/grid.hpp': No such file or directory [C:\Users\Brian\Desktop\Node\no
de_modules\mapnik\build\mapnik.vcxproj]
..\src\mapnik_grid.cpp(3): fatal error C1083: Cannot open include file: 'mapnik
/version.hpp': No such file or directory [C:\Users\Brian\Desktop\Node\node_modu
les\mapnik\build\mapnik.vcxproj]
  mapnik_memory_datasource.cpp
  mapnik_palette.cpp
  mapnik_projection.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_memory_datasour
ce.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_layer.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_layer.cpp) [C:\
Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_datasource.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_datasource.cpp)
 [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_featureset.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1185): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_color.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\
mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1202): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_color.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\
mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1215): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_color.cpp) [C:\Users\Brian\Desktop\Node\node_modules\ma
pnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1229): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_color.cpp) [C:\Users\Brian\Desktop\Node\node_modules\ma
pnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_color.cpp) [C:\
Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_expression.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1185): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_palette.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\buil
d\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1202): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_palette.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\buil
d\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1215): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_palette.cpp) [C:\Users\Brian\Desktop\Node\node_modules\
mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1229): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_palette.cpp) [C:\Users\Brian\Desktop\Node\node_modules\
mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1185): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_projection.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\b
uild\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1202): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_projection.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\b
uild\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1215): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_projection.cpp) [C:\Users\Brian\Desktop\Node\node_modul
es\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1229): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_projection.cpp) [C:\Users\Brian\Desktop\Node\node_modul
es\mapnik\build\mapnik.vcxproj]
  mapnik_cairo_surface.cpp
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_palette.cpp) [C
:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_projection.cpp)
 [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_cairo_surface.c
pp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
  mapnik_vector_tile.cpp
  vector_tile.pb.cc
c1xx : fatal error C1083: Cannot open source file: 'C:\Users\Brian\Desktop\Node
\node_modules\mapnik\build\Release\obj\global_intermediate\vector_tile.pb.cc':
No such file or directory [C:\Users\Brian\Desktop\Node\node_modules\mapnik\buil
d\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\mapnik-vector-tile
\src\mapnik3x_compatibility.hpp(4): fatal error C1083: Cannot open include file
: 'mapnik/config.hpp': No such file or directory (..\src\mapnik_vector_tile.cpp
) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1185): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_featureset.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\b
uild\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1202): w
arning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (.
.\src\mapnik_featureset.cpp) [C:\Users\Brian\Desktop\Node\node_modules\mapnik\b
uild\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1215): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_featureset.cpp) [C:\Users\Brian\Desktop\Node\node_modul
es\mapnik\build\mapnik.vcxproj]
C:\Users\Brian\Desktop\Node\node_modules\mapnik\node_modules\nan\nan.h(1229): w
arning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss
 of data (..\src\mapnik_featureset.cpp) [C:\Users\Brian\Desktop\Node\node_modul
es\mapnik\build\mapnik.vcxproj]
c:\users\brian\desktop\node\node_modules\mapnik\src\mapnik_featureset.hpp(5): f
atal error C1083: Cannot open include file: 'mapnik/datasource.hpp': No such fi
le or directory (..\src\mapnik_featureset.cpp) [C:\Users\Brian\Desktop\Node\nod
e_modules\mapnik\build\mapnik.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\ProgramData\chocolatey\lib\npm.1.4
.9\tools\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\ProgramData\\chocolatey\\lib\\npm.1.4.9\\tools\\nod
e_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=mapn
ik" "--configuration=Release" "--module_name=mapnik" "--version=1.4.17" "--major
=1" "--minor=4" "--patch=17" "--runtime=node" "--node_abi=node-v11" "--platform=
win32" "--target_platform=win32" "--arch=x64" "--target_arch=x64" "--module_main
=./lib/mapnik.js" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--modul
e_path=C:\\Users\\Brian\\Desktop\\Node\\node_modules\\mapnik\\lib\\binding\\node
-v11-win32-x64" "--module=C:\\Users\\Brian\\Desktop\\Node\\node_modules\\mapnik\
\lib\\binding\\node-v11-win32-x64\\mapnik.node" "--remote_path=./mapnik/v1.4.17/
" "--package_name=node-v11-win32-x64.tar.gz" "--staged_tarball=build\\stage\\map
nik\\v1.4.17\\node-v11-win32-x64.tar.gz" "--hosted_path=https://mapbox-node-bina
ry.s3.amazonaws.com/mapnik/v1.4.17/" "--hosted_tarball=https://mapbox-node-binar
y.s3.amazonaws.com/mapnik/v1.4.17/node-v11-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\Brian\Desktop\Node\node_modules\mapnik
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=ma
pnik --configuration=Release --module_name=mapnik --version=1.4.17 --major=1 --m
inor=4 --patch=17 --runtime=node --node_abi=node-v11 --platform=win32 --target_p
latform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js --host=
https://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\Users\Brian\Deskto
p\Node\node_modules\mapnik\lib\binding\node-v11-win32-x64 --module=C:\Users\Bria
n\Desktop\Node\node_modules\mapnik\lib\binding\node-v11-win32-x64\mapnik.node --
remote_path=./mapnik/v1.4.17/ --package_name=node-v11-win32-x64.tar.gz --staged_
tarball=build\stage\mapnik\v1.4.17\node-v11-win32-x64.tar.gz --hosted_path=https
://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/ --hosted_tarball=https://
mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/node-v11-win32-x64.tar.gz' (1
)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Brian\Desktop\
Node\node_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:833:5)
node-pre-gyp ERR! System Windows_NT 6.2.9200
node-pre-gyp ERR! command "node" "C:\\Users\\Brian\\Desktop\\Node\\node_modules\
\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to
-build"
node-pre-gyp ERR! cwd C:\Users\Brian\Desktop\Node\node_modules\mapnik
node-pre-gyp ERR! node -v v0.10.36
node-pre-gyp ERR! node-pre-gyp -v v0.5.27
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=mapnik --configuration=Release --
module_name=mapnik --version=1.4.17 --major=1 --minor=4 --patch=17 --runtime=nod
e --node_abi=node-v11 --platform=win32 --target_platform=win32 --arch=x64 --targ
et_arch=x64 --module_main=./lib/mapnik.js --host=https://mapbox-node-binary.s3.a
mazonaws.com/ --module_path=C:\Users\Brian\Desktop\Node\node_modules\mapnik\lib\
binding\node-v11-win32-x64 --module=C:\Users\Brian\Desktop\Node\node_modules\map
nik\lib\binding\node-v11-win32-x64\mapnik.node --remote_path=./mapnik/v1.4.17/ -
-package_name=node-v11-win32-x64.tar.gz --staged_tarball=build\stage\mapnik\v1.4
.17\node-v11-win32-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazon
aws.com/mapnik/v1.4.17/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws
.com/mapnik/v1.4.17/node-v11-win32-x64.tar.gz' (1)
npm ERR! mapnik@1.4.17 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@1.4.17 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\ProgramData\\chocolatey\\lib\\nodejs.commandline.0.10.36\\
tools\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm.1.4.9\\tools\\node_modul
es\\npm\\bin\\npm-cli.js" "install" "mapnik@1.x" "--build-from-source"
npm ERR! cwd C:\Users\Brian\Desktop\Node
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Brian\Desktop\Node\npm-debug.log
npm ERR! not ok code 0

I am not sure what I am missing here. I need 1.4.17 because I need MSSQL support as 3.x is currently broken.

**Comment by BHare1985** [comment]
I realized its because of the protoc error. Attempting to compile protoc leads to a bunch of external errors even though I got https://github.com/fuwaneko/node-protobuf to install because i compiled libprotobuf and libprotobuf-lite.  This isn't an issue with node-mapnik so I will close this, but this complexity is making me just wait until the MSSQL is supported before the company I work for switches over.

**Comment by BHare1985** [comment]
PS: If 64-bit window binaries could be added to 1.x, that would be awesome.

**Comment by flippmoke** [comment]
Not sure why you are using 1.x as our current version is 3.3.0, which there are windows binaries for at least 3.2.0 I know for certain.

**Comment by BHare1985** [comment]
@flippmoke

I want to use 1.x so that I can start prototyping using MSSQL data. Right now mapnik 3.x doesnt support MSSQL, see: https://github.com/mapnik/node-mapnik/issues/424

Later on, I plan to go to 3.x  when they fix the issue but I need to work with MSSQL to go forward with my app.

**Comment by flippmoke** [comment]
You might touch basis with @jbrwn in this ticket, if you wanted to speed up development of MSSQL plugin: https://github.com/mapnik/mapnik/issues/2797

**Comment by BergWerkGIS** [comment]
@BHare1985 
If you can wait a few days, I might be able to provide a 3.x node-mapnik MSSQL-enabled version.
I finally successfully compiled GDAL with ODBC support with VS2015:
https://github.com/mapbox/windows-builds/issues/37#issuecomment-100615391

**Comment by BergWerkGIS** [comment]
@BHare1985 

**Bad news:**

I'm not able to build gdal with MSSQL support with VS2014 CTP4 (the version we are currently using for our pre-compiled binaries).

This is due to CTP4 missing some aliases.

As a comment from Microsoft states in [Unresolved external when linking to odbc libs](https://connect.microsoft.com/VisualStudio/feedback/details/1039102):
*"Additionally, the legacy_stdio_definitions.lib library is currently missing the __imp_-prefixed aliases required by some libraries; these will be added in a future builds of Visual Studio 2015."*

So, we won't be able to provide a MSSQL enabled node-mapnik version via the "official channnels" (`npm install`) until we've moved all our native modules to VS2015 RC.

**Good news:**

I'm able to provide you with a workaround, if you can live with these restrictions:

* you have VS2015 RC or corresponding vcredist installed
* you don't use any other native modules in your project
* you are not scared to manually copy around some files :smirk: 

Download:
* https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/node-0.12.2-64bit.exe
* https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/node-v14-win32-x64.tar.gz

Extract `node-v14-win32-x64.tar.gz` into `<YOUR-EXISTING-PROJECT>\node_modules\mapnik\lib\binding`.

Copy `node-0.12.2-64bit.exe` directly into `<YOUR-EXISTING-PROJECT>` and use it to start your app.

/cc @springmeyer

**Comment by BHare1985** [comment]
Finally got re-assigned to Mapnik at work.

Started off with latest nodeJS (v0.12.3) and node-mapnik (v3.3.0)
Verified it was working with no issues.

I downloaded VS2015 RC vcredist here: https://www.microsoft.com/en-us/download/details.aspx?id=46881

Extracted the files from node-v14-win32-x64.tar.gz to the binding folder. Verified I was able to open nik2img.exe and shapeindex.exe without any library issues. This made me confident that VS2015 RC redist installed successfully.

I attempted to run my script with node-0.12.2-64bit.exe and got an error (most likely because my node isn't 0.12.2) I ran it with my installed node (0.12.3) and it started fine but got:

**Comment by BergWerkGIS** [comment]
Thanks for letting me know.

> I attempted to run my script with node-0.12.2-64bit.exe and got an error (most likely because my node isn't 0.12.2) I ran it with my installed node (0.12.3) and it started fine

Very interesting, I would expect it to be more the other way round.
