### ISSUE TITLE
3.3.1 release

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#441]
Shooting for v3.3.1 this week. Goal is to publish a release with just a few key bug fixes:

 - https://github.com/mapnik/mapnik/pull/2798
 - #433 (if we can solve)
 - #438 (if we can solve)

**Comment by flippmoke** [comment]
I think we are good to release a 3.3.1, I think we have solved #433 and mapnik/mapnik#2798. Also we have a fix in for #442.
