### ISSUE TITLE
mapnik.js:26:15 procedure could not be found

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#443]
Something very strange has happened. Yesterday everything was working fine, then this morning I installed Visual Studio 2015 Community RC and created a new project and did `npm install mapnik@3.x" and everything installed without error -- However I am getting this error: 

C:\Users\bh\Desktop\nodeMapnik>
C:\Users\bh\Desktop\nodeMapnik>node
> var mapnik = require('mapnik');
Error: The specified procedure could not be found.
C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\binding\node-v14-win32-x6
4\mapnik.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\li
b\mapnik.js:26:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
>

I figured it has something to do with messing with the Visual C++ Redistributable Packages so I reinstalled them/repaired them. Still nothing. I reinstalled NodeJS v0.12.2 and tryed to install mapkik again and it installs without error but won't load the module.

I have  uninstalled VS2015 in hopes to fix it, but still not working. I am slowly (painfully) uninstalling all the packages VS2015 left behind one by one from control panel as a System Restore failed.

Before I go any further I want to confirm that it's possible the VS2015 did something, or a hint of what could be the issue here.

**Comment by BHare1985** [comment]
Here is the output from installing:


C:\Users\bh\Desktop\nodeMapnik>npm install mapnik@3.x
\
> mapnik@3.3.0 install C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

[mapnik] Success: "C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\bindin
g\node-v14-win32-x64\mapnik.node" is installed via remote
mapnik@3.3.0 node_modules\mapnik
└── nan@1.8.4

C:\Users\bh\Desktop\nodeMapnik>node
> var mapnik = require('mapnik');
Error: The specified procedure could not be found.
C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\binding\node-v14-win32-x6
4\mapnik.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\li
b\mapnik.js:26:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
>

**Comment by BergWerkGIS** [comment]
@BHare1985 two things:

* for the time being, node-mapnik is still built with **`VS2014 CTP4`**, and not yet with **`VS2015 RC1`**, so you need the corresponding vcredist listed in the readme under [`install`](https://github.com/mapnik/node-mapnik#installing). **Unfortunately an install of `VS2015 RC1` removes the `VS2014 CTP4` vcredist, thus rendering our provided binaries unusable.**
* node 0.12.2 is not yet supported. Please downgrade your node install to one of the versions listed here: https://github.com/mapnik/node-mapnik/blob/master/appveyor.yml#L9-L32

I'm working hard at the moment to get everything to VS2015 RC1 (including MSSQL support) and will post back when binaries are available.

If you are under pressure to get things working, you could try to build everything from scratch on your own machine, using https://github.com/mapbox/windows-builds

This (and some time) should get you everything you want:
```
git clone https://github.com/mapbox/windows-builds.git
cd windows-builds
settings.bat "FASTBUILD=0" "IGNOREFAILEDTESTS=1" "NODE_VERSION=0.12.2"
scripts\build
```

**Comment by BHare1985** [comment]
Yeah I figure that, but reinstalling `VS2014 CTP4` Did not solve the issue. I also uninstalled all vcredist installed from 2015 and nothing yet. I downgraded to nodejs 0.11.13 and tried to install but it fails:



C:\Users\bh\Desktop\nodeMapnik>npm install mapnik
npm http GET https://registry.npmjs.org/mapnik
npm http 304 https://registry.npmjs.org/mapnik
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mapnik@3.3.0 install C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.3.0/
node-v0.11.13-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.3.0/
node-v0.11.13-win32-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary
.s3.amazonaws.com/mapnik/v3.3.0/node-v0.11.13-win32-x64.tar.gz (falling back to
source compile with node-gyp)

C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik>node "c:\Program Files\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 clean

C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik>node "c:\Program Files\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 configure --fallback-to-build --module=c:\Users\bh\Desktop\nodeMapnik\node_modu
les\mapnik\lib\binding\node-v0.11.13-win32-x64\mapnik.node --module_name=mapnik
--module_path=C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\binding\nod
e-v0.11.13-win32-x64

C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik>node "c:\Program Files\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 build --fallback-to-build --module=c:\Users\bh\Desktop\nodeMapnik\node_modules\
mapnik\lib\binding\node-v0.11.13-win32-x64\mapnik.node --module_name=mapnik --mo
dule_path=C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\binding\node-v0
.11.13-win32-x64
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(44,5): error MSB8020: The builds tools for v140 (Platform Toolset = 'v14
0') cannot be found. To build using the v140 build tools, either click the Proj
ect menu or right-click the solution, and then select "Update VC++ Projects..."
. Install v140 to build using the v140 build tools. [C:\Users\bh\Desktop\nodeMa
pnik\node_modules\mapnik\build\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\Use
rs\\bh\\Desktop\\nodeMapnik\\node_modules\\mapnik\\lib\\binding\\node-v0.11.13-w
in32-x64\\mapnik.node" "--module_name=mapnik" "--module_path=C:\\Users\\bh\\Desk
top\\nodeMapnik\\node_modules\\mapnik\\lib\\binding\\node-v0.11.13-win32-x64"
gyp ERR! cwd C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=c:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\binding
\node-v0.11.13-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\Users
\bh\Desktop\nodeMapnik\node_modules\mapnik\lib\binding\node-v0.11.13-win32-x64'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\Users\bh\Desktop\nod
eMapnik\node_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)

node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)

node-pre-gyp ERR! stack     at maybeClose (child_process.js:992:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1059:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "c:\\Users\\bh\\Desktop\\nodeMapnik\\node_modul
es\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback
-to-build"
node-pre-gyp ERR! cwd C:\Users\bh\Desktop\nodeMapnik\node_modules\mapnik
node-pre-gyp ERR! node -v v0.11.13
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=c:\Users\bh\D
esktop\nodeMapnik\node_modules\mapnik\lib\binding\node-v0.11.13-win32-x64\mapnik
.node --module_name=mapnik --module_path=C:\Users\bh\Desktop\nodeMapnik\node_mod
ules\mapnik\lib\binding\node-v0.11.13-win32-x64' (1)
npm ERR! mapnik@3.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.3.0 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mapnik"
npm ERR! cwd C:\Users\bh\Desktop\nodeMapnik
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\bh\Desktop\nodeMapnik\npm-debug.log
npm ERR! not ok code 0

C:\Users\bh\Desktop\nodeMapnik>



I know the build tools issue is because I dont have Visual Studio 2014 but Visual Studio 2012, and I installed Visual Studio 2015  but uninstalled it.  I don't expect you to handle this mess I got myself into, I just wish I never installed VS2015 because now I can't use mapnik at all, but I wanted to let you know of the 403 of https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.3.0/node-v0.11.13-win32-x64.tar.gz

**Comment by BergWerkGIS** [comment]
> but I wanted to let you know of the 403 of https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.3.0/node-v0.11.13-win32-x64.tar.gz

We don't have binaries for 0.11.13, so the 403 is expected.
Please use one of the versions you see here:
https://github.com/mapnik/node-mapnik/blob/master/appveyor.yml#L9-L32

* 0.10.36
* 0.11.14
* 0.12.0

**Comment by BHare1985** [comment]
The readme says

By default, binaries are provided for:

64 bit OS X 10.9, 64 bit Linux (>= Ubuntu Trusty), and 64/32 bit Windows
Node v0.10.x and Node v0.11.13

**Comment by BergWerkGIS** [comment]
@BHare1985 thanks for pointing that out. Will update the ReadMe.

**Comment by bh-ms2soft** [comment]
I was able to fix it by removing new DLLs with modification dates April 2015 in the C:\Windows\System32


The list of what I removed is:

04/15/2015  10:50 PM           333,480 concrt140.dll
04/15/2015  10:50 PM           796,840 concrt140d.dll
04/15/2015  10:50 PM         5,609,632 mfc140.dll
04/15/2015  10:50 PM            47,272 mfc140chs.dll
04/15/2015  10:50 PM            47,272 mfc140cht.dll
04/15/2015  10:50 PM        10,864,800 mfc140d.dll
04/15/2015  10:50 PM            75,944 mfc140deu.dll
04/15/2015  10:50 PM            66,216 mfc140enu.dll
04/15/2015  10:50 PM            74,920 mfc140esn.dll
04/15/2015  10:50 PM            75,944 mfc140fra.dll
04/15/2015  10:50 PM            73,896 mfc140ita.dll
04/15/2015  10:50 PM            55,464 mfc140jpn.dll
04/15/2015  10:50 PM            54,440 mfc140kor.dll
04/15/2015  10:50 PM            71,848 mfc140rus.dll
04/15/2015  10:50 PM         5,637,792 mfc140u.dll
04/15/2015  10:50 PM        10,936,488 mfc140ud.dll
04/15/2015  10:50 PM           103,584 mfcm140.dll
04/15/2015  10:50 PM           133,792 mfcm140d.dll
04/15/2015  10:50 PM           103,584 mfcm140u.dll
04/15/2015  10:50 PM           132,264 mfcm140ud.dll
04/15/2015  10:50 PM           634,528 msvcp140.dll
04/15/2015  10:50 PM         1,001,128 msvcp140d.dll
04/15/2015  10:50 PM           551,080 vcamp140.dll
04/15/2015  10:50 PM         1,392,808 vcamp140d.dll
04/15/2015  10:50 PM           387,248 vccorlib140.dll
04/15/2015  10:50 PM         1,022,648 vccorlib140d.dll
04/15/2015  10:50 PM           203,424 vcomp140.dll
04/15/2015  10:50 PM           230,568 vcomp140d.dll
04/15/2015  10:50 PM            88,248 vcruntime140.dll
04/15/2015  10:50 PM           133,816 vcruntime140d.dll
04/23/2015  01:06 AM           264,360 VSPerf140.dll


Then I reinstalled Visual Studio 2014 CTP4 64bit from  https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64.exe

It seems one of the DLLs is left over from a VS2015 install, and doesnt get removed on an uninstall. Also, it's possible that VS2014-CTP4 doesn't replace the DLL with theirs because it's newer. None the less removing these DLLs and reinstall seems to have fixed it for me. I know it's tied to vcruntime140.dll because when trying to run nik2img.exe manually It would have entry point errors in vcruntime140.dll

This isn't really a node-mapnik issue, more of a Microsoft one but I figured id post my solution incase someone else installs VS2015 and runs into this issue.

**Comment by BHare1985** [comment]
I was able to fix it by removing new DLLs with modification dates April 2015 in the C:\Windows\System32

The list of what I removed is:

04/15/2015 10:50 PM 333,480 concrt140.dll
04/15/2015 10:50 PM 796,840 concrt140d.dll
04/15/2015 10:50 PM 5,609,632 mfc140.dll
04/15/2015 10:50 PM 47,272 mfc140chs.dll
04/15/2015 10:50 PM 47,272 mfc140cht.dll
04/15/2015 10:50 PM 10,864,800 mfc140d.dll
04/15/2015 10:50 PM 75,944 mfc140deu.dll
04/15/2015 10:50 PM 66,216 mfc140enu.dll
04/15/2015 10:50 PM 74,920 mfc140esn.dll
04/15/2015 10:50 PM 75,944 mfc140fra.dll
04/15/2015 10:50 PM 73,896 mfc140ita.dll
04/15/2015 10:50 PM 55,464 mfc140jpn.dll
04/15/2015 10:50 PM 54,440 mfc140kor.dll
04/15/2015 10:50 PM 71,848 mfc140rus.dll
04/15/2015 10:50 PM 5,637,792 mfc140u.dll
04/15/2015 10:50 PM 10,936,488 mfc140ud.dll
04/15/2015 10:50 PM 103,584 mfcm140.dll
04/15/2015 10:50 PM 133,792 mfcm140d.dll
04/15/2015 10:50 PM 103,584 mfcm140u.dll
04/15/2015 10:50 PM 132,264 mfcm140ud.dll
04/15/2015 10:50 PM 634,528 msvcp140.dll
04/15/2015 10:50 PM 1,001,128 msvcp140d.dll
04/15/2015 10:50 PM 551,080 vcamp140.dll
04/15/2015 10:50 PM 1,392,808 vcamp140d.dll
04/15/2015 10:50 PM 387,248 vccorlib140.dll
04/15/2015 10:50 PM 1,022,648 vccorlib140d.dll
04/15/2015 10:50 PM 203,424 vcomp140.dll
04/15/2015 10:50 PM 230,568 vcomp140d.dll
04/15/2015 10:50 PM 88,248 vcruntime140.dll
04/15/2015 10:50 PM 133,816 vcruntime140d.dll
04/23/2015 01:06 AM 264,360 VSPerf140.dll

Then I reinstalled Visual Studio 2014 CTP4 64bit from https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64.exe

It seems one of the DLLs is left over from a VS2015 install, and doesnt get removed on an uninstall. Also, it's possible that VS2014-CTP4 doesn't replace the DLL with theirs because it's newer. None the less removing these DLLs and reinstall seems to have fixed it for me. I know it's tied to vcruntime140.dll because when trying to run nik2img.exe manually It would have entry point errors in vcruntime140.dll

This isn't really a node-mapnik issue, more of a Microsoft one but I figured id post my solution incase someone else installs VS2015 and runs into this issue.

**Comment by BergWerkGIS** [comment]
@BHare1985 
Thanks for sharing. I just ran into the same problem.

* Uninstalled vcredist VS2015 RC (was not listed in control panel anymore)
* reinstalled vcredist VS2014 CTP4 (was listed in control panel)
* but VS2015 RC file were still there

Manually deleting the files and reinstalling CTP4 solved it for me, too.
