### ISSUE TITLE
Consistent handling of proj_transform failures

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#448]
We know that `pj_transform` commonly fails when being ask to transform into spherical mercator.

In mapnik-vt 0.7.0 we used `mapnik::transform_path_adapter` to reproject geometries: https://github.com/mapbox/mapnik-vector-tile/blob/v0.7.1/src/vector_tile_processor.ipp#L817-L890.

The `mapnik::transform_path_adapter` is specifically designed to cope with `pj_transform` failures (by skipping](https://github.com/mapnik/mapnik/blob/master/include/mapnik/transform_path_adapter.hpp#L85-L102). This is an important solution in order to keep large shapes mostly intact that might have a small percentage of points which extend outside the valid range of spherical mercator.

The task now is to ensure that we still skip with the new reprojection that is used, which is happening inside here: https://github.com/mapbox/mapnik-vector-tile/blob/887e82a1011f02ad9ef0aa756018b03e6665c81d/src/vector_tile_processor.ipp#L1252-L1264

**Comment by flippmoke** [comment]
Just need to make small fix to MVT's calculating of bounding boxes and this can be closed.

**Comment by springmeyer** [comment]
@flippmoke My understanding is different. The concern is that `if (!prj_trans_.backward(x, y, z)) return false` at https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_strategy.hpp#L61 may lead to incorrectly closed polygons. We need to skip failed transforms instead of aborting on them.

**Comment by springmeyer** [comment]
This problem is deeper that I first anticipated. I worried that incorrect handling of polygons would lead to dropped features or incorrectly closed polygons. Rather what happens is that an exception is thrown which aborts all rendering.

To recap: An invalid coordinate is one that - when reprojected to the target projection from the source projection - triggers a non-zero return from [pj_transform](https://trac.osgeo.org/proj/wiki/pj_transform). This is very common in geodata that is global - many natural earth shapefiles will trigger this because they have a few coordinates at -180.000001 instead of exactly `-180.0`. Or even coordinates [way outside those extents](https://github.com/mapbox/tilelive.js/issues/113). Given the new behavior, even if 99% of the coordinates are within the valid range that can be reprojected to mercator, [all rendering will abort here](https://github.com/mapnik/mapnik/blob/master/include/mapnik/geometry_transform.hpp#L38).

Starting at https://github.com/mapbox/mapnik-vector-tile/commit/11aed657e599251bf9ad6cbe0405a251b6bb3643#diff-2f08898bf55283bb72b03127f87d076f two things changed:

  - We dropped `mapnik::transform_path_adapter` which, as per above, previously skipped failed `pj_transform`.
  - We moved from a pipeline that did `clip -> reproject -> scale to int` to `reproject -> scale to int -> clip`.

My sense is that clipping first was likely avoiding the need for skipping in `mapnik::transform_path_adapter` in most cases because clipping had already removed the coordinates that might trip up `pj_transform`.

**Comment by springmeyer** [comment]
Testcase at https://springmeyer.s3.amazonaws.com/poly-lat-invalid-4269.zip. This has intentionally placed coordinates that cross pass -90. It renders fine in QGIS:

![screen shot 2015-06-10 at 12 39 54 am](https://cloud.githubusercontent.com/assets/20300/8077388/3f7d55ca-0f0a-11e5-9d1d-953575e657b4.png)

It renders fine in mapbox-studio with node-mapnik@3.2.0 (sorry for the barely visible shape, squint it is there):

![screen shot 2015-06-10 at 12 46 56 am](https://cloud.githubusercontent.com/assets/20300/8077398/53f82340-0f0a-11e5-84be-3aacaf925ad7.png)

It breaks mapbox-studio with node-mapnik@3.3.x:

![screen shot 2015-06-10 at 12 46 11 am](https://cloud.githubusercontent.com/assets/20300/8077407/63d1c9e2-0f0a-11e5-8636-4a0e481bcafc.png)

The blank screen is because each tile is returning a 404 with `Can't transformm geometry`.

**Comment by springmeyer** [comment]
tracking fix at https://github.com/mapbox/mapnik-vector-tile/issues/116
