### ISSUE TITLE
intialize persistent typo

### ISSUE THREAD

**Issue by tmcw** [mapnik/node-mapnik#453]
https://github.com/mapnik/node-mapnik/blob/a972ab71aa9a7d2b4047f7e9586c4f8dd7e23c35/src/mapnik_image.cpp#L157

This typo is repeated in the cpp code & tests - correct word should be initialize

**Comment by springmeyer** [comment]
Thanks for catching this, will fix shortly.

**Comment by flippmoke** [comment]
*Looks at the Blame quietly...*

![image](https://cloud.githubusercontent.com/assets/1794907/7923384/38bcef40-0878-11e5-8162-29b65c6bb5c5.png)
