### ISSUE TITLE
Make buffer-size configurable in vt.addGeoJSON

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#457]
It's [currently hardcoded](https://github.com/mapnik/node-mapnik/blob/98c7eaca3ad5a1629f2899061acd50c843c9b3c2/src/mapnik_vector_tile.cpp#L2187) which is not good. This `vt.addGeoJSON` was added mainly to make it easier to write unit tests and may be rethought in the future. But until then we should probably default to `128` and make the option configurable and documented.

**Comment by BergWerkGIS** [comment]
Don't know, if this could be a hint to track down anything, but doesn't happen in Mapbox Studio 0.2.7 (with the data provided in https://github.com/mapnik/mapnik/issues/2873):

![image](https://cloud.githubusercontent.com/assets/4549888/8002002/9270d894-0b6b-11e5-8f58-5b63c5033009.png)

**Comment by springmeyer** [comment]
right @BergWerkGIS - because Mapbox Studio does not use `vt.addGeoJSON`, a function added mostly for debugging/tests and the only thing that suffers from this bug.
