### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by tmcw** [mapnik/node-mapnik#458]
Would be great to split out some of the instructions about building & documenting node-mapnik into its own file: currently to build docs you need to:

```sh
npm run docs
```

And push to gh-pages.

**Comment by springmeyer** [comment]
k, there is https://github.com/mapnik/node-mapnik/blob/master/docs/Contributing.md that can be moved around/split apart (and some nascent docs beside it that can be moved to the new inline doc structure, yay).

**Comment by tmcw** [comment]
Ahh - cool, the perk of contributing.md in the root is that it'll automatically show up on top of the new-issue form

**Comment by tmcw** [comment]
:+1: moved the file and added a documentation section in f9656f1012fa6fd974862e4d164def4b71fe4cd6
