### ISSUE TITLE
New Mapnik SDK

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#460]
Need to pull in updated mapnik sdk tomorrow with https://github.com/mapnik/mapnik/pull/2901 for https://github.com/mapbox/mapnik-vector-tile/issues/116. After that v3.3.1 will be ready to tag.

 - [x] linux/osx: @springmeyer
 - [x] windows: @BergWerkGIS

**Comment by BergWerkGIS** [comment]
10 failing tests on Windows:
https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.518/job/q8thh3n8g8mi6jt3#L4196

**Comment by springmeyer** [comment]
@BergWerkGIS - interesting. I presume that might be due to https://github.com/mapnik/mapnik/issues/2893 (did you build with that commit?) Unix builds are using and SDK from yesterday so do not include https://github.com/mapnik/mapnik/issues/2893 /cc @artemp

**Comment by BergWerkGIS** [comment]
y, using commit https://github.com/mapnik/mapnik/commit/167708329df701805b6925f6f4facdc33d90dcb1

Should I try another one tomorrow (about to power down, dinner's already on the table)?

**Comment by springmeyer** [comment]
@BergWerkGIS yes, don't worry about this today. Have a nice dinner!
