### ISSUE TITLE
Resolve failing image tests

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#461]
Surfacing from https://github.com/mapnik/node-mapnik/issues/460#issuecomment-111213167

**Comment by flippmoke** [comment]
This is likely due to https://github.com/mapnik/mapnik/commit/96f7120ecc11c81ebe90c91d2db9757a844ef2eb

**Comment by springmeyer** [comment]
fixed: https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.524
