### ISSUE TITLE
Use Mapnik 3.0.1

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#485]
@flippmoke - As discussed the plan has been to tag node-mapnik v3.4.1 using Mapnik v3.0.0. But now that Mapnik v3.0.1 is ready I think using v3.0.1 would be ideal.

Remaining things to do:

  - [x] Ensure my commit testing Mapnik v3.0.1 works on travis osx/linux: https://travis-ci.org/mapnik/node-mapnik/builds/72943258
  - [x] Get a Mapnik v3.0.1 windows SDK - currently blocked by https://github.com/mapbox/windows-builds/issues/53 /cc @BergWerkGIS 
  - [x] Update node-mapnik changelog by copy/paste from mapnik changelog (which is up to date)

**Comment by BergWerkGIS** [comment]
Our build server (mapnik) and AppVeyor (node-mapnik) are not yet available with VS2015 (reason for error).

* I will manually publish `mapnik Windows SDK` (till I've upgraded our own build server).
* I will manually publish `node-mapnik` (till AppVeyor has upgraded).

Just ping me, when you are ready.

**Comment by springmeyer** [comment]
@BergWerkGIS - thanks, makes sense. @flippmoke let's pause on node-mapnik v3.4.1 release until we can get VS 2015 windows binaries able to be published automatically from appveyor.

**Comment by springmeyer** [comment]
To be clear: the appveyor.yml is still building against Mapnik 3.0.0 but we need to wait to tag node-mapnik v3.4.1 until it is building against Mapnik 3.0.1 (to ensure the same Mapnik version is used for both Windows, Mac, and Linux binaries).

**Comment by flippmoke** [comment]
Use of mapnik 3.0.1 for binaries is complete for using linux and osx. It is my understanding that @BergWerkGIS has made the mapnik core binaries as well, the only remaining step is to build them as part of 3.4.1 release. This can now be tracked in #487, so I think this issue is closed.
