### ISSUE TITLE
Publish Node-Mapnik 3.4.1

### ISSUE THREAD

**Issue by flippmoke** [mapnik/node-mapnik#489]
The changes to node mapnik for the 3.4.1 release are complete however, we currently are not able to release due to #487. After talking with @springmeyer, we have decided the best course of action is to simply tag `3.4.1` release and publish it to npm at a later date. This will allow work to continue towards a `3.4.2` or `3.5.0` in master.

Steps left in this process are:
 
 - [x] Publish binaries for linux and osx
 - [x] Publish Binaries for windows
 - [x] re-tag 3.4.1
 - [x] Publish to npm 3.4.1

**Comment by springmeyer** [comment]
@flippmoke https://github.com/mapnik/node-mapnik/pull/492 is almost done - it came together much quicker that I hoped. Next actions are:

  - test it a bit more
  - queue up pull requests that move all other node c++ modules (needed by studio) to vs 2015
  - once all other node c++ modules are looking good (give me a few days), I'll merge https://github.com/mapnik/node-mapnik/pull/492
  - then we can tag and close this.

**Comment by springmeyer** [comment]
> I'll merge #492 then we can tag and close this.

Done (https://travis-ci.org/mapnik/node-mapnik/builds/73590828). @flippmoke ready for you to re-tag and  publish.
