### ISSUE TITLE
error from show_module_runtime.ps1

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#490]
Seems harmless, but seeing:

```
Get-ChildItem : The specified path, file name, or both are too long. The fully qualified file name must be 
less than 260 characters, and the directory name must be less than 248 characters.
At C:\mb\node-mapnik-bergwerkgis\scripts\show_module_runtime.ps1:3 char:19
```

/cc @BergWerkGIS - should we ignore or fix?

**Comment by BergWerkGIS** [comment]
Fix would have to be in directory structure of `node_modules` (flatter hierarchy) and not in the PowerShell script.

<pre>
The specified <b>path</b>, <b>file name</b>, or both <b>are too long</b>.
The fully qualified <b>file name must be less than 260 characters</b>, 
and the <b>directory name must be less than 248 characters</b>.
</pre>

It's running into this stupid `MAX_PATH` limit of 260 chars, that exists (to keep compatibility with old software) and also doesn't exist.
Depending on how the file system is accessed.

Nevertheless we could try the `extended-length path` syntax (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) and see how this works with PowerShell (never tried it). 

That should give us a maximum total path length of 32,767 chars:

```
"\\?\C:\very long path"
```

**Comment by springmeyer** [comment]
okay, I'm fine with this warning :)
