### ISSUE TITLE
Using mapnik.Datasource with parameterized queries

### ISSUE THREAD

**Issue by im4LF** [mapnik/node-mapnik#495]
For example I create a new layer with Datasource:

```javascript
new mapnik.Datasource({
    type: 'postgis',
    ...
    table: '(SELECT geom, name FROM some_table WHERE category = ' .parseInt(user_input). ') AS layer'
});
```
I need to filter input values for preventing sql-injections (parseInt, ...);

Postgres have escaping functionality, so can I use some of this:

```javascript
new mapnik.Datasource({
    type: 'postgis',
    ...
    table: '(SELECT geom, name FROM some_table WHERE category = $1) AS layer',
    params: [ user_input ]
});
```

**Comment by im4LF** [comment]
Anybody?

**Comment by springmeyer** [comment]
This feels like something solvable via mapnik variables (experimental): https://github.com/mapnik/mapnik/issues/2553

**Comment by im4LF** [comment]
Is this functionality supports sql injection filters?

**Comment by springmeyer** [comment]
@im4LF I don't understand your question. Please followup over at https://github.com/mapnik/mapnik/issues/2553
