### ISSUE TITLE
Minor: figure out git settings to fix line endings issue

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#497]
Should revert https://github.com/mapnik/node-mapnik/commit/183d8d9a03057312805debc3a82a4d1c2d7eb879 once we figure out windows line endings issue per https://github.com/mapnik/node-mapnik/pull/492#commitcomment-12451925

**Comment by BergWerkGIS** [comment]
Reverted.

Solved via forcing linefeed line endings (`world_merc.converted.geojson text eol=lf`) on checkout in `.gitattributes`:
https://github.com/mapnik/node-mapnik/blob/master/.gitattributes

**NOTE:**
An existing `node-mapnik` clone directory should be deleted and a fresh clone be done.
The new `.gitattributes` doesn't change the existing json file.
