### ISSUE TITLE
Docs followup on VS 2015 change

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#498]
@BergWerkGIS - when you have time can you:

  - update https://github.com/mapnik/node-mapnik/blob/master/README.md#windows-specific to say when vs 2015 is used
  - update https://github.com/mapnik/node-mapnik/wiki/WindowsBinaries

**Comment by BergWerkGIS** [comment]
:white_check_mark: https://github.com/mapnik/node-mapnik#windows-specific
:white_check_mark: https://github.com/mapnik/node-mapnik/wiki/WindowsBinaries
:white_check_mark: https://github.com/mapbox/node-cpp11/blob/master/README.md

Leaving open as a reminder to search for other places to update.

**Comment by springmeyer** [comment]
Great, thanks for the updates. I can't think of anywhere else atm, so will close this now.
