### ISSUE TITLE
int overflow in 3.4.1

### ISSUE THREAD

**Issue by calvinmetcalf** [mapnik/node-mapnik#499]
in version 3.4.1 (But not 3.4.0) I get the following warning

    Warning 1: Integer overflow occured when trying to return 64bit integer. Use GetFieldAsInteger64() instead

when I have JavaScript dates like `1440518400000` represented as integers causing them to be truncated (and all the dates in my map be in the year 1970).

**Comment by flippmoke** [comment]
That looks like a bug in our code associated with GDAL 2.0 and our gdal plugin, is that what you are using?

**Comment by calvinmetcalf** [comment]
it's reading a geojson file so maybe?

**Comment by flippmoke** [comment]
I am sorry this would be the OGR plugin.

**Comment by flippmoke** [comment]
This has been fixed in https://github.com/mapnik/mapnik/commit/161469ed638f2feabe8534983b20f51d3e5370aa as the bug was in mapnik-core rather then in the node bindings this will take a little while to filter its way up stream. It will be a part of the next mapnik-core release however.
