### ISSUE TITLE
npm install mapnik failed

### ISSUE THREAD

**Issue by qiyexue** [mapnik/node-mapnik#500]
environment：windows 7 64;node(v0.12.7);
D:\mapnik-node>npm install mapnik
\
> mapnik@3.4.2 install D:\mapnik-node\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

D:\mapnik-node\node_modules\mapnik>if not defined npm_config_node_gyp (node "D:\
program files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
gyp\bin\node-gyp.js" clean )  else (node  clean )

D:\mapnik-node\node_modules\mapnik>if not defined npm_config_node_gyp (node "D:\
program files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\mapnik-node\node_
modules\mapnik\lib\binding\node-v14-win32-x64\mapnik.node --module_name=mapnik -
-module_path=D:\mapnik-node\node_modules\mapnik\lib\binding\node-v14-win32-x64 )
  else (node  configure --fallback-to-build --module=D:\mapnik-node\node_modules
\mapnik\lib\binding\node-v14-win32-x64\mapnik.node --module_name=mapnik --module
_path=D:\mapnik-node\node_modules\mapnik\lib\binding\node-v14-win32-x64 )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: node-v0.12.7.tar.gz local checksum aa512bf70097d5aec4df1e8
764365bb86cf78d5851ceea1d2f6a9b3596fa2cba not match remote b23d64df051c9c969b0c5
83f802d5d71de342e53067127a5061415be7e12f39d
gyp ERR! stack     at deref (D:\program files\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\install.js:307:20)
gyp ERR! stack     at Request.<anonymous> (D:\program files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\install.js:417:24)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (D:\program files\nodejs\node_
modules\npm\node_modules\request\request.js:1153:12)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\program files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\
\mapnik-node\\node_modules\\mapnik\\lib\\binding\\node-v14-win32-x64\\mapnik.nod
e" "--module_name=mapnik" "--module_path=D:\\mapnik-node\\node_modules\\mapnik\\
lib\\binding\\node-v14-win32-x64"
gyp ERR! cwd D:\mapnik-node\node_modules\mapnik
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=D:\mapnik-node\node_modules\mapnik\lib\binding\node-v14-wi
n32-x64\mapnik.node --module_name=mapnik --module_path=D:\mapnik-node\node_modul
es\mapnik\lib\binding\node-v14-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\mapnik-node\node_mod
ules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "D:\\mapnik-node\\node_modules\\mapnik\\node_mo
dules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\mapnik-node\node_modules\mapnik
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\mapnik
-node\node_modules\mapnik\lib\binding\node-v14-win32-x64\mapnik.node --module_na
me=mapnik --module_path=D:\mapnik-node\node_modules\mapnik\lib\binding\node-v14-
win32-x64' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\program files\\nodejs\\\\node.exe" "D:\\program files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "mapnik"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.4.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.4.2 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\mapnik-node\npm-debug.log

D:\mapnik-node>

**Comment by BergWerkGIS** [comment]
Do you have the  `Visual C++ Redistributable Package for Visual Studio 2015` installed?
https://github.com/mapnik/node-mapnik#windows-specific

**Comment by qiyexue** [comment]
Thank you !Yes,I have installed,I try it again,and sometimes it reminds me to install .net framework sdk 2.0.maybe this is the problem.

**Comment by BergWerkGIS** [comment]
To avoid confusion for future readers of this issue:

`Visual C++ Redistributable Package for Visual Studio 2015` and the `.Net Framework` are two different things.

`node-mapnik` relies on the **`Visual C++ Redistributable Package / vcredist`**, but does **not** need the `.Net Framework`.
