### ISSUE TITLE
Unable to Render Beyond z17

### ISSUE THREAD

**Issue by nickwebha** [mapnik/node-mapnik#501]
When trying to render tiles beyond z17 node-mapnik just produces blue, featureless tiles.

**Comment by flippmoke** [comment]
This doesn't provide us much detail in order to help you with a problem that you might have, can you please provide us with more details and ideally a repeatable test case that we can use to reproduce any problems that there might be in the code. 

https://github.com/mapnik/mapnik/wiki/A-perfect-testcase

**Comment by nickwebha** [comment]
In my JavaScript I have my "class":

    var MAP = function() {
    	function initialize() {
    		mapnik.register_system_fonts();
    		mapnik.register_default_fonts();
    		mapnik.register_default_input_plugins();
    	};

    	this.tile = function(request, response, style, x, y, z) {
    		var cwd = process.cwd();
    		var style_path = cwd + configuration.map.path.style + style + ".xml";

    		if ( ! fs.existsSync(style_path) || z < configuration.map.zoom.minimum || z > configuration.map.zoom.maximum ) {
    			response.writeHead(404);
    			response.end();

    			return;
    		}

    		var path = cwd + configuration.map.path.cache;

    		try {
    			path += z + "/";
    			if ( ! fs.existsSync(path) )
    				fs.mkdirSync(path);

    			path += y + "/";
    			if ( ! fs.existsSync(path) )
    				fs.mkdirSync(path);

    			path += x + "/";
    			if ( ! fs.existsSync(path) )
    				fs.mkdirSync(path);

    			path += style + ".png";
    			if ( ! fs.existsSync(path) ) {
    				var tile = new mapnik.Map(configuration.map.tile.size, configuration.map.tile.size);

    				tile.loadSync(style_path, { strict: true });
    				tile.extent = sphericalmercator.xyz_to_envelope(x, y, z, false);

    				tile.renderFileSync(path, { format: "png" });
    			}

    			response.writeHead(200, { "Content-Type": "image/png" });
    			response.end(fs.readFileSync(path));
    		}
    		catch ( exception ) {
    			response.writeHead(404);
    			response.end();
    		}
    	};

    	initialize();
    };

The various `configuration` object members are for the style (.xml from .mml/.mss), minimum/maximum desired zoom levels, and the cache path where generated tiles get cached.

This is what I get with my [carto style sheet](http://external.lifebloodnetworks.com/node-mapnik/2015.08.10-01/carto_style_sheet.zip):
[z17] ![z17](http://external.lifebloodnetworks.com/node-mapnik/2015.08.10-01/z17.png)
[z18] ![z17](http://external.lifebloodnetworks.com/node-mapnik/2015.08.10-01/z18.png)

As far as I can tell the carto style sheet allows for zoom levels above 17 (`zoom >= 17` in a number of places).

**Comment by flippmoke** [comment]
I would try logging the `extent` of the map and see what happens for zoom level 18.
```
tile.extent = sphericalmercator.xyz_to_envelope(x, y, z, false);
```

**Comment by flippmoke** [comment]
Also instead of providing a zip file could you provide the xml style you are using? Maybe just link it as a gist?

**Comment by nickwebha** [comment]
z18 is giving me `[ NaN, NaN, NaN, NaN ]` for each tile. Lower zoom levels (obviously) output the expected (example: `[ -8238077.160463155, 4970547.0753284395, -8237771.412350015, 4970852.82344158 ]`).

I have also Gist'ed my [compiled carto style sheet](https://gist.github.com/nickwebha/a1a07e7981713b568971).

**Comment by nickwebha** [comment]
The sphericalmercator.inc.js file is in [this gist](https://gist.github.com/nickwebha/0967cec5d8e39cbe9bda).

**Comment by nickwebha** [comment]
The problem was not in node-mapnik but in my `sphericalmercator.inc.js` file. It seems z18 was hard-coded in there at some point. Thank you so much for your help! I would not have known where to look without this conversation!

Closing issue.
