### ISSUE TITLE
npm ERR! Test failed.  -  mapnik.VectorTile

### ISSUE THREAD

**Issue by billyz313** [mapnik/node-mapnik#508]
I did the npm install followed be the npm test.  I got 501 passing, 4 pending, and 4 failing.  The 4 failing all had to do with the  mapnik.VectorTile as seen below.  Any ideas what I need to do?

 mapnik.VectorTile
    â should fail when adding bad parameters to add geoJSON
    â should be able to create a vector tile from geojson
    â should be able to create a vector tile from geojson - with simplification
    1) should be able to create a vector tile from geojson - multipoint
    2) should be able to create a vector tile from geojson - multipoint - with simplification
    â should be able to create a vector tile from multiple geojson files
    â toGeoJSON should fail with invalid useage
    â should throw with invalid usage
    â should be initialized properly
    â should accept optional width/height
    â should be able to setData/parse (sync)
    â should error out if we pass invalid data to setData - 1
    â should error out if we pass invalid data to setData - 2
    â should error out if we pass invalid data to setData - 3
    â should error out if we pass invalid data to setData - 4
    â should error out if we pass invalid data to setData - 5
    â should return empty but have layer name
    â should error out if we pass invalid data to addData
    â should fail to do clear
    â should fail to parse
    â should be able to setData/parse (async)
    â should be able to get layer names without parsing
    â should be able to get tile info as JSON
    â should be able to get tile info as various flavors of GeoJSON
    â should be able to get and set data
    â should be able to get virtual datasource and features
    â should be able to clear data (sync)
    â should be able to clear data (async)
    â should be able to add data
    â should detect as solid a tile with two "box" layers
    â should render an empty vector
    â should detect as non-solid a tile with intersecting rectangle
    â should detect as non-solid a tile with intersecting rectangle 2
    â should detect as solid a tile with rectangle that is solid within tile extent
    â should fail to render due to bad arguments passed
    â should render expected results
    â should render expected results - with objectional arguments
    â should fail to render due to bad parameters
    â should fail to render two vector tiles at once
    â should render a vector_tile of the whole world (78ms)
    â should render a vector_tile of the whole world - area threshold applied
    â should render a vector_tile of the whole world - simplify_distance applied
    â should read back the vector tile and render an image with it
    â should read back the vector tile and render a native svg with it
    â should read back the vector tile and render a cairo svg with it
    3) should read back the vector tile and render an image with it using negative buffer
    â should read back the vector tile and render a grid with it
    â should read back the vector tile and render a grid with it - layer name and fields
    4) should read back the vector tile and render an image with markers
    â should be able to resample and encode (render) a geotiff into vector tile
    â should fail to addImage due to bad input
    â should be able to push an image tile directly into a vector tile layer without decoding (39ms)
    â should include image in getData pbf output
    â should be able to render data->vtile and vtile->image with roughtly the same results

  501 passing (3s)
  4 pending
  4 failing

  1) mapnik.VectorTile  should be able to create a vector tile from geojson - multipoint:

      AssertionError: 61 == 60
      + expected - actual

      -61
      +60

      at Context.<anonymous> (test/vector-tile.test.js:205:16)

  2) mapnik.VectorTile  should be able to create a vector tile from geojson - multipoint - with simplification:

      AssertionError: 61 == 60
      + expected - actual

      -61
      +60

      at Context.<anonymous> (test/vector-tile.test.js:255:16)

  3) mapnik.VectorTile  should read back the vector tile and render an image with it using negative buffer:

      Uncaught AssertionError: 0 == 1588
      + expected - actual

      -0
      +1588

      at test/vector-tile.test.js:1182:20

  4) mapnik.VectorTile  should read back the vector tile and render an image with markers:

      Uncaught AssertionError: 0 == 11
      + expected - actual

      -0
      +11

      at test/vector-tile.test.js:1264:20

**Comment by flippmoke** [comment]
What version of node mapnik is this for you or are you on master?

**Comment by billyz313** [comment]
I did git clone https://github.com/mapnik/mapnik -b 2.3.x

**Comment by billyz313** [comment]
sry, i mean git clone https://github.com/mapnik/node-mapnik

**Comment by flippmoke** [comment]
Trying pulling the latest and seeing if it works.

**Comment by billyz313** [comment]
thank you!
