### ISSUE TITLE
PointSymbolizer or MarkersSymbolizer supports iconfont ?

### ISSUE THREAD

**Issue by qiyexue** [mapnik/node-mapnik#512]
# Udig sld 

![1](https://cloud.githubusercontent.com/assets/6417642/9484348/67bbf20c-4bdd-11e5-9f80-72ca389a3533.png)

#### Does PointSymbolizer or MarkersSymbolizer support like this ?
    <sld:WellKnownName>ttf://3333#0x38</sld:WellKnownName>

**Comment by springmeyer** [comment]
No, this is not supported by Mapnik.

**Comment by qiyexue** [comment]
ok,thanks
