### ISSUE TITLE
Windows: failing composite tests

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#516]
With latest mapnik/master node-mapnik/master I get these failing tests:

![image](https://cloud.githubusercontent.com/assets/4549888/9761312/7c1a1a4e-56eb-11e5-8c62-f5190698bd43.png)

**Comment by BergWerkGIS** [comment]
Fails locally and on EC2, but not on AppVeyor.

**Comment by springmeyer** [comment]
Odd, took a quick look at those tests and don't see any clues.

**Comment by BergWerkGIS** [comment]
Disappeared with:
https://github.com/mapnik/mapnik/commit/0532df7b6eab77d1ee601fef8ac8f01e4b15cdd2
https://github.com/mapnik/node-mapnik/commit/39a02b6a925e028e8797d7baabab0a590cf0b94b
