### ISSUE TITLE
Windows: Failing SVG tests with boost 1.59

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#520]
Don't know, if this is really related to `boost@1.59`, but it's the only thing I've changed on my machine.

@flippmoke maybe you could give it a spin on *nix?
/cc @artemp FYI

refs https://github.com/mapbox/windows-builds/issues/56

![image](https://cloud.githubusercontent.com/assets/4549888/9852987/e0392d90-5af0-11e5-9ef4-a621d1b66c45.png)

**Comment by flippmoke** [comment]
Test fixed in node-mapnik.
