### ISSUE TITLE
"npm install -g mapnik" fails

### ISSUE THREAD

**Issue by lintonye** [mapnik/node-mapnik#521]
This worked perfectly a few days ago. Here is the npm-debug.log file: http://pastebin.com/di8YPKbe

Looks like it's the same issue as https://github.com/mapnik/node-mapnik/issues/519

**Comment by springmeyer** [comment]
Yes, your logs show you are using node v4.x. This is not yet supported. We are tracking at https://github.com/mapnik/node-mapnik/pull/509.
