### ISSUE TITLE
svg renderer should gracefully handle files without height/width

### ISSUE THREAD

**Issue by samanpwbb** [mapnik/node-mapnik#523]
right now, if you provide an SVG without a width/height, node mapnik throws an error: https://github.com/mapnik/node-mapnik/blob/bf581563d923871f4d4cce4c15b1ba544f1617ae/src/mapnik_image.cpp#L2394-L2398

But SVGs without width/height are valid in the SVG spec and the majority of SVGs in the wild do not have these properties.

**Comment by jfirebaugh** [comment]
Mapnik needs _some_ hint as to the desired dimensions. I saw a suggestion that the `viewBox` could be a fallback. Can someone update the ticket with details?

**Comment by jakepruitt** [comment]
@jfirebaugh `viewBox` is now used as a default to calculate the aspect ratio in the event that the width or height is missing. If both are missing, the viewbox's width and height are used as the size and width. This update was merged by @artemp this morning, so now it just needs to be released and incorporated into a new node-mapnik release. Once that is done, we can put the functionality in api-assets and test that it works.

**Comment by springmeyer** [comment]
Thanks @jakepruitt - assuming the new Mapnik version upstream is released as a `patch` then I think its appropriate to quickly after release a new patch of node-mapnik as `v3.4.8`. So I've created https://github.com/mapnik/node-mapnik/milestones/v3.4.8 and assigned this ticket to it.

**Comment by springmeyer** [comment]
v3.4.8 will go out tomorrow once #538 falls and this will be available then.
