### ISSUE TITLE
Test failure against Mapnik master

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#524]
Seeing some subtle changes/test failures locally:

```
  2) mapnik.VectorTile  should render a vector_tile of the whole world - area threshold applied:

      Uncaught AssertionError: [{"name":"world","extent":4096,"version":1,"features":[{"id":1,"type":3,"geometry":[9,2688,3686,18,0,4,4,1,15],"properties":{"AR deepEqual [{"name":"world","extent":4096,"version":1,"features":[{"id":1,"type":3,"geometry":[9,2688,3686,18,0,4,4,1,15],"properties":{"AR
      + expected - actual

                 "AREA": 238174
                 "FIPS": "AG"
                 "ISO2": "DZ"
                 "ISO3": "DZA"
      -          "LAT": 28.163
      +          "LAT": 28
                 "LON": 2.632
                 "NAME": "Algeria"
                 "POP2005": 32854159
                 "REGION": 2
```

I'm thinking this might have to do with https://github.com/mapnik/mapnik/issues/3078 /cc @artemp 

Note: that specific test failure is being reported that way in the `nan-2.0` branch. In master we are comparing hex encoded buffers so the test failure looks different.

**Comment by BergWerkGIS** [comment]
Not seeing this on local Windows builds, neither with node 0.10.40 or 0.12.7.

**Comment by BergWerkGIS** [comment]
ah, overlooked that this is for `nan-2.0`, branch.

Gettings same errors, although with with more information.

Seems the `actual` version of the pdf does not get generated.


```
1) mapnik.VectorTile  should render a vector_tile of the whole world:
     Uncaught Error: ENOENT, no such file or directory 'c:\mb\windows-builds-64\packages\node-mapnik\test\data\vector_tile\tile0.vector.actual.pbf'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)
      at c:\mb\windows-builds-64\packages\node-mapnik\test\vector-tile.test.js:1566:34

  2) mapnik.VectorTile  should render a vector_tile of the whole world - area threshold applied:
     Uncaught Error: ENOENT, no such file or directory 'c:\mb\windows-builds-64\packages\node-mapnik\test\data\vector_tile\tile0-area_threshold.vector.actual.pbf'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)
      at c:\mb\windows-builds-64\packages\node-mapnik\test\vector-tile.test.js:1594:34

  3) mapnik.VectorTile  should render a vector_tile of the whole world - simplify_distance applied:
     Uncaught Error: ENOENT, no such file or directory 'c:\mb\windows-builds-64\packages\node-mapnik\test\data\vector_tile\tile0-simplify_distance.vector.actual.pbf'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)
      at c:\mb\windows-builds-64\packages\node-mapnik\test\vector-tile.test.js:1622:34
```

**Comment by springmeyer** [comment]
@BergWerkGIS - this is happening in master branch of node-mapnik + master of mapnik. The test errors I get locally on OS X in that case are https://gist.github.com/springmeyer/7cd743177b1b4cc90492. The problem you are seeing above is just a glitch in my attempt to change the tests to show more detail.

**Comment by BergWerkGIS** [comment]
reran again to make sure (with node 0.10.40):

`mapnik@master` + `node-mapnik@nan-2.0` => errors above
`mapnik@master` + `node-mapnik@master` =>  no failed tests

**Comment by springmeyer** [comment]
@BergWerkGIS - thanks, I confirmed I'm hitting this on master too. Although I just did a build on a clean checkout and don't hit the problem. So something may be odd about my local checkout.

**Comment by springmeyer** [comment]
> So something may be odd about my local checkout.

Nevermind. The tests started passing for me because I had rebuilt mapnik at https://github.com/mapnik/mapnik/commit/9ce2f337b3daa71f834a3477b64. So, the cause is some change in mapnik between https://github.com/mapnik/mapnik/commit/9ce2f337b3daa71f834a3477b64 and master: https://github.com/mapnik/mapnik/compare/9ce2f337b3daa71f834a3477b64...master

**Comment by springmeyer** [comment]
Found that reverting 7938479bb400cee676a7 fixes the problem. Narrowed down to this change alone that will solve these test failures. 

```diff
diff --git a/include/mapnik/value.hpp b/include/mapnik/value.hpp
index cfa86fa..c5ffd27 100644
--- a/include/mapnik/value.hpp
+++ b/include/mapnik/value.hpp
@@ -76,7 +76,7 @@ struct equals
 {
     bool operator() (value_integer lhs, value_double rhs) const
     {
-        return  lhs == static_cast<value_integer>(rhs);
+        return  lhs == rhs;
     }
 
     bool operator() (value_bool lhs, value_double rhs) const
```

This says to me that we need to revert the changes associated with #3078, go back and ensure we have 100% test coverage of these operators, and then try re-integrating the fixes to address in the warnings in #3078.

**Comment by artemp** [comment]
@springmeyer - good call ^ 

we need to upcast to double LHS 

```
return  static_cast<double>(lhs) == rhs;
```

**Comment by springmeyer** [comment]
solved by https://github.com/mapnik/mapnik/commit/8c2f15c94a6de1540bb50a33dc8f7f052a94c943, thanks @artemp!
