### ISSUE TITLE
line symbolizer offset

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#525]
I need this feature: https://github.com/mapnik/mapnik/issues/180 but didn't see any documentation on how to use it, and where/if its exposed in node-mapnik at all.

I have two geometries that represent each direction of a road. I need to pick one direction to be one offset and the other offset in the opposite direction (Which offset it gets I hope I can specify with mapnik xml using an attribute of the geometry). Not only that but to aide in visuals I would like the offsets to be dynamically changing with zoom level.

That is, when zoomed in the offset is much closer. When zoomed out the offset is much further away. We currently have this feature with ArcGIS Server so we know its a useful thing, just not sure if Mapnik, or specifically node-mapnik has something that can support this?

Work arounds is using our SQL Server to do the offset of the geometries one time and resave the WKB with the new offsets and then just deal with not having different offsets for different zooms. Sadly SQL Server doesnt have a function that makes offsetting lines easy, unlike PostGIS which has ST_OffsetCurve

**Comment by danpat** [comment]
Line offsets are available, and it works well in many situations.  Be aware that there are a couple of known bugs (https://github.com/mapnik/mapnik/issues/3041).

If using CartoCSS, use `line-offset: N`:

    https://github.com/mapnik/mapnik-reference/blob/master/3.0.5/reference.json#L686

In Mapnik XML, add the `offset` parameter to your LineSymbolizer, like so:

```
<Style name="style-foo" filter-mode="first">
  <Rule>
    <LineSymbolizer offset="10" />
  </Rule>
</Style>
```

or using CartoCSS:
```
::foo {
  line-offset: 10;
}
```

Offset direction is to the right relative to the geometry direction.  If the geometries are the same, but have opposite ordering, giving them both a positive offset will move them away from each other.

You can specify different offsets at different zooms by doing something like this:

CartoCSS:
```
::foo {
  [zoom <= 10] {
      line-offset: 10;
  }
  [zoom >10][zoom <= 14] {
      line-offset: 15;
  }
  [zoom >14] {
      line-offset: 20;
  }
}
```

In Mapnik XML:
```
<Style name="style-foo" filter-mode="first">
  <Rule>
    <MaxScaleDenominator>400000</MaxScaleDenominator>
    <MinScaleDenominator>25000</MinScaleDenominator>
    <LineSymbolizer offset="15" />
  </Rule>
  <Rule>
    <MaxScaleDenominator>25000</MaxScaleDenominator>
    <LineSymbolizer offset="20" />
  </Rule>
  <Rule>
    <MinScaleDenominator>400000</MinScaleDenominator>
    <LineSymbolizer offset="10" />
  </Rule>
</Style>
```

See http://wiki.openstreetmap.org/wiki/MinScaleDenominator for setting the values on Min/MaxScaleDenominator.  Carto conveniently converts standard web mercator zoom levels to the right values for Mapnik XML.

If you have a property on your line features that specifies the direction relative to the geometry order, you can use that to decide on a positive or negative offset:

In CartoCSS:
```
::foo {
  [attr =~ "POS"] {
      line-offset: 10;
  }
  [attr =~ "NEG"] {
      line-offset: -10;
  }
}
```

In Mapnik XML:
```
<Style name="style-foo" filter-mode="first">
  <Rule>
    <Filter>([attr].match('NEG'))</Filter>
    <LineSymbolizer offset="-10" />
  </Rule>
  <Rule>
    <Filter>([attr].match('POS'))</Filter>
    <LineSymbolizer offset="10" />
  </Rule>
</Style>
```

the `.match` operator is just one of several ways to look at attribute values, see https://github.com/mapnik/mapnik/wiki/Filter for more details.
