### ISSUE TITLE
Tests hang against mapnik master

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#534]
Seeing:

```
  mapnik.Datasource
    ✓ should throw with invalid usage
    ✓ should validate with known shapefile - ogr
HANG
```

The hang is in `shape_index_featureset<mapnik::filter_in_box>::shape_index_featureset(mapnik::filter_in_box const&, std::__1::unique_ptr<shape_io, std::__1::default_delete<shape_io> >&&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  (in shape.input) + 363  [0x102daf44b]` and is likely a regression after https://github.com/mapnik/mapnik/pull/3089

/cc @artemp

**Comment by artemp** [comment]
regression : fixed in de9de659c3772fdf232a3c24f5c254a0a86046b9 + ac8c76c9685145496c4f89a04cc84f594f48fd9c

/cc @springmeyer

**Comment by springmeyer** [comment]
@artemp - can you please link against the actual URL for the commits instead of just the hash? This makes it much easier for me to go check out. And it reminds you to commit the fixes ;)

**Comment by springmeyer** [comment]
Sweet, confirmed the fix and the hang is gone.
