### ISSUE TITLE
SVG parsing test failures with boost 1.59

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#535]
When built against boost 1.59 new SVG test failures appear: https://gist.github.com/springmeyer/dbecaf9ca6a40ebfd04b.

The cause is newly encountered:

```
Failed to parse double: "105000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
Failed to parse double: "-105000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```
This looks like the same (cause) as reported at https://github.com/mapnik/mapnik/issues/3111

/cc @artemp for advice on how to fix, or whether we should just update the test fixtures to be different.

**Comment by BergWerkGIS** [comment]
Same thing on Windows: https://github.com/mapnik/node-mapnik/issues/520
