### ISSUE TITLE
Incompatible library version: libgdal.dylib requires version 10.0.0 or later, but libgeos_c.1.dylib provides version 9.0.0

### ISSUE THREAD

**Issue by pngimbwa** [mapnik/node-mapnik#544]
Hi there;

I know it might be a repeated question.

But the above error appears when I try to run this command:
>>>from django.contrib.gis import goal

The error:
Referenced from: /usr/local/lib/libgdal.dylib
Reason: Incompatible library version: libgdal.dylib requires version 10.0.0 or later, but libgeos_c.1.dylib provides version 9.0.0

Am using Mac OS X El Capitan (10.11)

Help will be appreciated.

Peter

**Comment by springmeyer** [comment]
I can see you are using geojson, in python. But this repo is about mapnik via node.js. So I'm going to close this ticket as it seems like you must have created this issue in the wrong place?
