### ISSUE TITLE
Updated windows SDK

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#550]
- [x] Update master to point at new dev build of Win SDK with latest git hash based on work from https://github.com/mapbox/windows-builds/issues/65
- [ ] Ensure all tests are passing - refs #549

/cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
latest SHA, built with updated deps: `mapnik-win-sdk-v3.0.7-57-g669bca8-x64-14.0.7z`
@springmeyer do you want to update today, or should I tomorrow?

**Comment by springmeyer** [comment]
SDK works, will track last fix at #549
