### ISSUE TITLE
Expose FillType for vt encoding

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#552]
Depending on the findings by @flippmoke at https://github.com/mapbox/mapnik-vector-tile/issues/166 we'll want to expose this option in node-mapnik

**Comment by springmeyer** [comment]
@flippmoke can this be closed (with a link to the fix)?

**Comment by flippmoke** [comment]
This can be closed once https://github.com/mapnik/node-mapnik/pull/553 is merged.

**Comment by springmeyer** [comment]
okay, :+1:
