### ISSUE TITLE
Consistently expose image constructor options

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#554]
Noticed that a few of the alternative image constructors do not support all possible options. For example `new mapnik.Image(w,h, options)` supports both `type`, `initialize`, `premultiplied`, `painted` being passed.

TODO:

 - [x] `fromBufferSync` should likely gain `premultiplied` and `painted` (not planning support for `type` since only rgba is expected/supported)
 - [ ] `fromBytes` should also likely gain  `premultiplied` and `painted` (`type` is automatically deduced)

/cc @bsudekum @flippmoke

**Comment by flippmoke** [comment]
`fromBytes` uses the image readers in mapnik -- therefore `premultiplied` should be determined from the file itself. 
`painted` could be useful -- but I would rather expose an option to set `painted` rather then add another option. 
Therefore -- I do  not see the need to add the extra options for `fromBytes` currently. I am going to close as `fromBufferSync` is done.
