### ISSUE TITLE
Datasource getting hit x times with x styles

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#555]
Is it normal for a datasource to get x queries when x styles are defined to a layer?

I am using this SQL Server plugin: https://github.com/gaspardle/mapnik-mssql and it seems that it's sending two queries to sql server when I have two styles defined for one layer. Performance is getting hit hard because of it.

I am asking here to see if its a normal behavior in mapnik, or a bug in nodejs mapnik, or a bug in the plugin (or the plugin needs some sort of cache on when to reuse resultsets).

**Comment by BHare1985** [comment]
After some research seems I want `cache-features` according to https://github.com/mapnik/mapnik/wiki/XMLConfigReference

Will wait for a reply to confirm, and then close.

**Comment by talaj** [comment]
> Is it normal for a datasource to get x queries when x styles are defined to a layer?

Yes, it is intended behavior now. The reason why `cache-features` is not used by default is that it can take a lot of memory, see https://github.com/mapnik/mapnik/issues/657.

I think that can make sense to reevaluate this decision as I'm using `cache-features` on all layers with more than one style without any memory issue so far.
