### ISSUE TITLE
some SVG can't be render 

### ISSUE THREAD

**Issue by bladepeter** [mapnik/node-mapnik#556]
I rendered a geojson file  with xml stylesheet, some MarkersSymbolizer use svg , but some can render ,some can't. the svg files can be displayed in web browser. 
(1) following is XML:
            MarkersSymbolizer file='symbols/rail.svg' allow-overlap='true' ignore-placement='true' height='12' width='60'/
(2) The svg can't be rendered is :+1: 

path style="fill:none;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke:rgb(67.058824%,65.098039%,65.098039%);stroke-opacity:1;stroke-miterlimit:4;" d="M 0 7.5 L 40 7.5 "
path style="fill:none;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke:rgb(100%,100%,100%);stroke-opacity:1;stroke-dasharray:12,12;stroke-miterlimit:4;" d="M 0 7.5 L 40 7.5 "
so, what can I do?

**Comment by talaj** [comment]
Mapnik doesn't support CSS styling in SVG, see https://github.com/mapnik/mapnik/issues/3048.

You can convert your SVG to plain XML using [Inkscape](`https://inkscape.org/en/):

File -> Save As... -> Optimized SVG -> Style to XML

**Comment by bladepeter** [comment]
@talaj thank you! But I want to do the transform automatic,are there any solutions?

**Comment by bladepeter** [comment]
@talaj So,another question,could I output plain XML SVG with mapnik?I create my svgs with mapnik now.

**Comment by talaj** [comment]
> But I want to do the transform automatic,are there any solutions?

I don't know about any automatic solution for this.

> could I output plain XML SVG with mapnik?I create my svgs with mapnik now.

SVGs created by Mapnik should be plain XML already.
