### ISSUE TITLE
Don't concatenate commands.

### ISSUE THREAD

**Issue by ChALkeR** [mapnik/node-mapnik#557]
https://github.com/mapnik/node-mapnik/blob/master/bin/mapnik-render.js#L32:

``` javascript
child_process.exec('open ' + image);
```

This should be probably replaced with:

``` javascript
child_process.execFile('open', [image]);
```

Your current version does not deal with fine with special chars (i.e. spaces) in filenames.
`image` is just `process.argv[3]`, so it could contain arbitary input.

Not sure what the `open` command is here, and have not tested the code, hence no PR.

**Comment by flippmoke** [comment]
Not an expert here, but wouldn't you want a new subshell for the window you open?

**Comment by tjwebb** [comment]
> so it could contain arbitary input.

He's saying that this is a security issue. Which it is.
