### ISSUE TITLE
Release node-mapnik v3.4.10 on Mapnik v3.0.9-rc2

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#558]
Per chat with @artemp and @flippmoke we'll wait to cut v3.4.10 until next Mapnik tag is available

**Comment by vjpr** [comment]
Does https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.10-alpha/node-v47-darwin-x64.tar.gz exist, if one wanted to use the prebuilt binary with Node 5?

**Comment by springmeyer** [comment]
@vjpr - yes, to do so you'd just install from master github until the `v3.4.10` tag is available like:

```
npm install https://github.com/mapnik/node-mapnik/tarball/master
```

**Comment by springmeyer** [comment]
done, ended up on rc2: https://github.com/mapnik/node-mapnik/commit/dd150a358917031ba7448b1a916ed3fa6186a6e2
