### ISSUE TITLE
build fails on Darwin 15

### ISSUE THREAD

**Issue by aberenyi** [mapnik/node-mapnik#559]
Hi there,

It looks like build fails on Darwin 15. I've tried using the binary `npm i mapnik` and the source `npm i mapnik --build-from-source` method too - (almost the) same result; [binary npm-debug.log](https://copy.com/bikLK3WONuOofWCZ) & [source npm-debug.log](https://copy.com/jULWBBVAxCzenPkv).

I have `mapnik` installed via homebrew, version `3.0.5` & `node 5.0.0`.

**Comment by springmeyer** [comment]
Binaries will be available for node v5 once the v3.4.10 is out. Until then it is expected that the build will fall back to a source compile. As far as why your source compile is failing, I'm not sure. Usually `ELIFECYCLE` indicates some permissions problem. Your logs are a bit baffling to me. Maybe just wait for the binaries to be available and until then use an older node version.
