### ISSUE TITLE
Test failure against Mapnik master

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#560]
Seeing:

```
  561 passing (3s)
  1 pending
  1 failing

  1) mapnik.Feature  should construct a feature properly:
     AssertionError: Missing expected exception..
      at Function._throws (assert.js:301:5)
      at Function.assert.throws (assert.js:318:11)
      at Context.<anonymous> (test/feature.test.js:45:16)
```

Looks like this json is no longer considered invalid by Mapnik: https://github.com/mapnik/node-mapnik/blob/master/test/feature.test.js#L46

/cc @artemp to investigate

**Comment by artemp** [comment]
@springmeyer - the above is fixed after 32331e9b3e2c0a6b10f352f9c47453397df5194c but I'm getting some other failures, would be cool to sync briefly !

**Comment by springmeyer** [comment]
other failures fixed in https://github.com/mapnik/node-mapnik/commit/aa8b9e01b7137c92812af57b41e7ec539dc43715, closing.

**Comment by artemp** [comment]
add malformed feature tests
https://github.com/mapnik/test-data/commit/e2ddd49eaf1638dd871ab168f7d3f88a10d42696
https://github.com/mapnik/mapnik/commit/b85055ee38da59baaaa2a590d3144e4240d142d8
