### ISSUE TITLE
EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by vandelay** [mapnik/node-mapnik#561]
Hi good people

Today, suddenly: segfaults. As described [here](https://github.com/mapnik/node-mapnik/wiki/Troubleshooting#segfault--segmentation-fault--exc_bad_access-sigsegv) I am reporting them.

https://gist.github.com/vandelay/a5ba14be8a9c5b9bce17

https://gist.github.com/vandelay/6184ae7a6068dd979974

https://gist.github.com/vandelay/ba81a6594ef6fb49466f

Thanks for your work.

Cheers

Dom

**Comment by springmeyer** [comment]
Looks like the crash happens during rendering utf8 grids. I don't know why this would happen and its not something I've seen before. Can you provide more details about what your app is doing when it crashes?

**Comment by vandelay** [comment]
I'm using a modified version of the sample code tile/database/app.js . It has worked and generated many tiles already. PNGs work fine. When I call with utfgrid=true, it segfaults on the 7th tile.

```javascript
						// Did they request JSON for utfgrid? ?utfgrid=true
					  var queryObject = url.parse(req.url,true).query;
						var utfgrid = queryObject.utfgrid;
						
						// Render a utfgrid with object data
						if (utfgrid == 'true') {
							
			         var grid = new mapnik.Grid(256, 256, {key: '__id__'});
			         var options = {'layer': 0,
			                        'fields': ['__id__','id','name']
			                       };
			         map.render(grid, options, function(err, grid) {
			             if (err) { 
										 throw err;
									 } else {
			               var grid_utf = grid.encodeSync({resolution: 4});
										 res.writeHead(200, {'Content-Type': 'application/json'});
			               res.end(JSON.stringify(grid_utf,null,1));

									 }
			         });
						
						} else {
						
						  // Render a PNG
            	var im = new mapnik.Image(map.width, map.height);
            	map.render(im, function(err, im) {
              	if (err) {
             		 throw err;
              	} else {
                 res.writeHead(200, {'Content-Type': 'image/png'});
                 res.end(im.encodeSync('png'));
             	 }
            	});
```

**Comment by vandelay** [comment]
Ok, so the problem seems to be in the alternating between images and utfgrid rendering (the big if...else above).

If I just do one or the other, then it is fine. So, I can work around it.

Thanks!

**Comment by vandelay** [comment]
For anyone else reading, I think it was the grid being a different size to the map.
