### ISSUE TITLE
How to create svg with node-mapnik?

### ISSUE THREAD

**Issue by bladepeter** [mapnik/node-mapnik#563]
@springmeyer 
I want to create svg with node-mapnik, and I create successfully with the "renderfile" method of map,but the method can't  save the result as  chinese filename,so I want to use the "render" method,but get error:"renderable mapnik object expected"  ,following is the code:

var im = new  mapnik.CairoSurface('svg',256,256);
map.render(im,{format:'svg'}, function(err,im){
    if(err){
    }else{
        im.encode('svg',function(err,image){
            fs.writeFileSync('E:/data/temp/frameogr.svg',image);
        });
   }
});

**Comment by springmeyer** [comment]
node-mapnik does not support rendering a Map to an SVG at the moment. It could, but the functionality is not exposed in the API. It is exposed when going from vector tile -> SVG, but not map -> SVG.

**Comment by bladepeter** [comment]
@springmeyer  Thanks！
