### ISSUE TITLE
Windows node 5.1.0 install fails

### ISSUE THREAD

**Issue by TimJMartin** [mapnik/node-mapnik#567]
Hi 

I am trying to install node mapnik on windows 7 x64. I noticed that from version 3.4.8 it supports node 5.1.0 Stable but I am getting the following errors during the install. I have followed the instructions to install the VS2015 runtimes. I am wondering if its because node v5.1.0 does not have C++ enabled? However, I cannot see a node 5.1.0 version on this page - https://github.com/mapbox/node-cpp11/blob/master/README.md#windows.

Any ideas?

Thanks

Log:

C:\Temp\mapniktest>npm install mapnik

> mapnik@3.4.11 install C:\Temp\mapniktest\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

C:\Temp\mapniktest\node_modules\mapnik>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Temp\mapniktest\node_modules\mapnik>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Temp\mapnikte
st\node_modules\mapnik\lib\binding\node-v47-win32-x64\mapnik.node --module_name=
mapnik --module_path=C:\Temp\mapniktest\node_modules\mapnik\lib\binding\node-v47
-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Temp\mapnikt
est\node_modules\mapnik\lib\binding\node-v47-win32-x64\mapnik.node --module_name
=mapnik --module_path=C:\Temp\mapniktest\node_modules\mapnik\lib\binding\node-v4
7-win32-x64 )
'mapnik-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'mapnik-config --includes' returned exit status 1. while trying to
load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Temp\\mapniktest\\node_modules\\mapnik\\lib\\bin
ding\\node-v47-win32-x64\\mapnik.node" "--module_name=mapnik" "--module_path=C:\
\Temp\\mapniktest\\node_modules\\mapnik\\lib\\binding\\node-v47-win32-x64"
gyp ERR! cwd C:\Temp\mapniktest\node_modules\mapnik
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Temp\mapniktest\node_modules\mapnik\lib\binding\node-v4
7-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\Temp\mapniktest\no
de_modules\mapnik\lib\binding\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Temp\mapniktest\node
_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Temp\\mapni
ktest\\node_modules\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "ins
tall" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Temp\mapniktest\node_modules\mapnik
node-pre-gyp ERR! node -v v5.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Temp\m
apniktest\node_modules\mapnik\lib\binding\node-v47-win32-x64\mapnik.node --modul
e_name=mapnik --module_path=C:\Temp\mapniktest\node_modules\mapnik\lib\binding\n
ode-v47-win32-x64' (1)
npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Temp\mapniktest\pack
age.json'
npm WARN EPACKAGEJSON mapniktest No description
npm WARN EPACKAGEJSON mapniktest No repository field.
npm WARN EPACKAGEJSON mapniktest No README data
npm WARN EPACKAGEJSON mapniktest No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "mapnik"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.4.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.4.11 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\mapniktest\npm-debug.log

C:\Temp\mapniktest>

**Comment by BergWerkGIS** [comment]
The publish scripts for Windows didn't run through and a build from source is started.

Interesting though, that if fails with 

```
'mapnik-config' is not recognized as an internal or external command,
```
/cc @springmeyer 

I'll kick off a new build and try to republish.

**Comment by BergWerkGIS** [comment]
@TimJMartin 
After this build (https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.983) has finished successfully Windows binaries should be available and `npm install mapnik` should work.

**Comment by BergWerkGIS** [comment]
`npm install mapnik` works now with `node@5.1.0 x64` on Windows

**Comment by TimJMartin** [comment]
I can also confirm that it now works

@BergWerkGIS many thanks
