### ISSUE TITLE
Convert spatialite to mbtiles

### ISSUE THREAD

**Issue by bmehta** [mapnik/node-mapnik#571]
I have successfully converted spatialite to mbtiles using Mapbox Studio. I suspect Mapnik is the one doing this behind the scenes. I am trying to do this programatically now. Is it possible to use node-mapnik to achieve this through node/js?

Thanks.

**Comment by springmeyer** [comment]
> I have successfully converted spatialite to mbtiles using Mapbox Studio.

Okay. Through the Source editor I presume?

>  I suspect Mapnik is the one doing this behind the scenes.

Yes, but also a lot of logic built on top of mapnik.

>  I am trying to do this programatically now.

Sure.

For automation you can use all the components of Mapbox Studio Classic. You just need to call them from the command line. This can be done outside of Mapbox Studio Classic or even by finding them inside the `node_modules` folder in a Mapbox Studio Classic package.


>  Is it possible to use node-mapnik to achieve this through node/js?

As per above, yes. But you need a bit more than node-mapnik.

The basic breakdown of who does what (in Mapbox Studio Classic) is:

  - Mapnik (core) understands how to read various data formats and query them
  - Mapnik-vector-tile can turn queries into Vector Tiles (https://github.com/mapbox/mapnik-vector-tile)
  - Node-mapnik bundles https://github.com/mapbox/mapnik-vector-tile and offers a javascript API for working with Vector Tiles
  - tilelive (https://github.com/mapbox/tilelive) brings a notion of tiling schemes
  - tilelive-bridge offers a tilelive backend to create vector tiles from a mapnik XML
  - node-mbtiles offers a tilelive backend to put image and vector tiles into a mbtiles database
  - Mapbox Studo Classic offers a UI around all these tools

**Comment by bmehta** [comment]
Thank you.

**Comment by bmehta** [comment]
Dane,

Further questions as I dig deeper into the source code for Mapbox Studio classic.
Been trying to find where this piece is, but no success.

What decides the combinations of z, x, y for vector tiles?
(I am using an intermediate mapnik xml as input for automation that was created from spatialite)


Binita
--------------------------------------------
On Mon, 12/7/15, Dane Springmeyer <notifications@github.com> wrote:

 Subject: Re: [node-mapnik] Convert spatialite to mbtiles (#571)
 To: "mapnik/node-mapnik" <node-mapnik@noreply.github.com>
 Cc: "BM" <binita_mehta@yahoo.com>
 Date: Monday, December 7, 2015, 9:51 PM
 
 
 I have successfully converted spatialite to mbtiles using
 Mapbox Studio.
 
 
 Okay. Through the Source editor I presume?
 
 
 I suspect Mapnik is the one doing this behind the
 scenes.
 
 
 Yes, but also a lot of logic built on top of mapnik.
 
 
 I am trying to do this programatically now.
 
 
 Sure.
 
 For automation you can use all the components of Mapbox
 Studio Classic. You just need to call them from the command
 line. This can be done outside of Mapbox Studio Classic or
 even by finding them inside the node_modules
 folder in a Mapbox Studio Classic package.
 
 
 Is it possible to use node-mapnik to achieve this through
 node/js?
 
 
 As per above, yes. But you need a bit more than
 node-mapnik.
 
 The basic breakdown of who does what (in Mapbox Studio
 Classic) is:
 
 
 Mapnik (core) understands how to read various data
 formats and query them
 Mapnik-vector-tile can turn queries into Vector Tiles
 (https://github.com/mapbox/mapnik-vector-tile)
 Node-mapnik bundles https://github.com/mapbox/mapnik-vector-tile
 and offers a javascript API for working with Vector
 Tiles
 tilelive (https://github.com/mapbox/tilelive)
 brings a notion of tiling schemes
 tilelive-bridge offers a tilelive backend to create
 vector tiles from a mapnik XML
 node-mbtiles offers a tilelive backend to put image and
 vector tiles into a mbtiles database
 Mapbox Studo Classic offers a UI around all these
 tools
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by springmeyer** [comment]
@bmehta example code (NOT used by Mapbox Studio Classic) but that might be helpful is https://svn.openstreetmap.org/applications/rendering/mapnik/generate_tiles.py which has logic for figuring out what z/x/y to render given a bbox. In Mapbox Studio Classic this is done by https://github.com/mapbox/node-sphericalmercator, `tilelive.copy`, and a given tilelive "scheme". Mapbox Studio Classic uses the "pyramid" scheme which starts at 0,0,0 and then decends downward in z/x/y and skips any child tiles that look like they do not have data. The equivalent to `generate_tiles.py` would be the `scanline` "scheme" https://github.com/mapbox/tilelive/blob/master/lib/stream-scanline.js

**Comment by bmehta** [comment]
Thanks. Little confused about tilelive.copy. Looks like it is used to copy source mbtiles to destination mbtiles? How does it play a role when importing sqlite and exporting to mbtiles?


--------------------------------------------
On Tue, 12/8/15, Dane Springmeyer <notifications@github.com> wrote:

 Subject: Re: [node-mapnik] Convert spatialite to mbtiles (#571)
 To: "mapnik/node-mapnik" <node-mapnik@noreply.github.com>
 Cc: "BM" <binita_mehta@yahoo.com>
 Date: Tuesday, December 8, 2015, 2:20 PM
 
 @bmehta example code
 (NOT used by Mapbox Studio Classic) but that might be
 helpful is https://svn.openstreetmap.org/applications/rendering/mapnik/generate_tiles.py
 which has logic for figuring out what z/x/y to render given
 a bbox. In Mapbox Studio Classic this is done by https://github.com/mapbox/node-sphericalmercator,
 tilelive.copy, and a given tilelive
 "scheme". Mapbox Studio Classic uses the
 "pyramid" scheme which starts at 0,0,0 and then
 decends downward in z/x/y and skips any child tiles that
 look like they do not have data. The equivalent to
 generate_tiles.py would be the
 scanline "scheme" https://github.com/mapbox/tilelive/blob/master/
  lib/stre
  am-scanline.js
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by springmeyer** [comment]
> Thanks. Little confused about tilelive.copy. Looks like it is used to copy source mbtiles to destination mbtiles?

It is generic and abstracted from formats. Different "backends" implement sources and sinks for various formats. https://github.com/mapbox/tilelive/blob/master/API.md is the generic API.

>  How does it play a role when importing sqlite and exporting to mbtiles?

tilelive.copy provides the ability to pass in a bbox and get back tiles rendered. To do this it needs a source and sink. In your case the "source" is going to be a `tilelive-bridge` source that needs a Mapnik XML that points to the sqlite. In your case the "sink" is going to be a `node-mbtiles` sink that creates an mbtiles file full of vector tiles.
@bmehta -

**Comment by bmehta** [comment]
@springmeyer. Thanks for your response.

Trying to use tilelive-copy utility included with tilelive with mapnik xml as source and mbtiles as destination.

./tilelive-copy bridge:////Users/mehtab/projects/mbtiles-automation/app/data/data.xml mbtiles:////Users/mehtab/projects/mbtiles-automation/app/data/data.mbtiles --scheme=pyramid --minzoom=0 --maxzoom=16 --bounds=34.650059,-77.933513,38.891531,-76.831915 --timeout=60000

I see this output
[0.278s] 100.0000%      2/     1 @    2/s | ✓ 1 □ 948.9k | 0s left

However, I only see 1 row each in the tiles and images database of the mbtiles file. I have attached the xml (source) as well as mbtiles (destination).
Something to do with bounds perhaps?



--------------------------------------------
On Tue, 12/8/15, Dane Springmeyer <notifications@github.com> wrote:

 Subject: Re: [node-mapnik] Convert spatialite to mbtiles (#571)
 To: "mapnik/node-mapnik" <node-mapnik@noreply.github.com>
 Cc: "BM" <binita_mehta@yahoo.com>
 Date: Tuesday, December 8, 2015, 3:45 PM
 
 
 Thanks. Little confused about tilelive.copy. Looks like
 it is used to copy source mbtiles to destination
 mbtiles?
 
 
 It is generic and abstracted from formats. Different
 "backends" implement sources and sinks for various
 formats. https://github.com/mapbox/tilelive/blob/master/API.md
 is the generic API.
 
 
 How does it play a role when importing sqlite and
 exporting to mbtiles?
 
 
 tilelive.copy provides the ability to pass in a bbox and
 get back tiles rendered. To do this it needs a source and
 sink. In your case the "source" is going to be a
 tilelive-bridge source that needs a Mapnik XML
 that points to the sqlite. In your case the "sink"
 is going to be a node-mbtiles sink that creates
 an mbtiles file full of vector tiles.
 
 @bmehta - 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bmehta** [comment]
@springmeyer 
Attached is also the sqlite that is the datasource in data.xml above.

[24033802405_acs14_From_FME_EPSG4326.sqlite.zip](https://github.com/mapnik/node-mapnik/files/57003/24033802405_acs14_From_FME_EPSG4326.sqlite.zip)

**Comment by bmehta** [comment]
@springmeyer 
Ignore the last 2 comments. I was able to generate the mbtiles successfully by using bounds=-180,-85.0511,180,85.0511.
