### ISSUE TITLE
binary dispatch: FAIL. 

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#573]
I am running node-mapnik on Amazon Linux AMI release 2015.03 using Amazon Beanstalk with node-v0.12.6-linux-x64 binaries 

Using these packages

 "tilelive": "5.8.2",
"tilelive-mapnik": "0.6.17"

Mapnik has been running without flaw for months with this setup and just recently I am getting

```
binary dispatch: FAIL
Trace: [Error: binary dispatch: FAIL]
    at Function.<anonymous> (/var/app/current/node_modules/windwalker/node_modules/tilelive-mapnik/lib/mapnik_backend.js:330:25)
```

I attempted to google the error but got no where with it. Any suggestions are welcomed

**Comment by springmeyer** [comment]
Also never seen that error before.

**Comment by springmeyer** [comment]
The error is likely coming from https://github.com/mapnik/mapnik/blob/e0c756ee8d90c9cd1cbc67c8b5e2ce5d7451128a/include/mapnik/util/variant.hpp#L411-L418. So we need to ask what might cause that code to execute... well that variant code handles evaluating all core objects in Mapnik. My hunch is that your style has some kind of expression which is triggering an edge case condition. So it is likely something invalid in your style. And probably Mapnik's fault that you are not getting a more helpful error.

Two things I recommend:

1) Print out your style to XML and share in a gist so I can take a look to see if anything looks odd

2) Try reducing the style detail slowly until you no longer hit the error. Then re-introduce things one-by-one until it becomes clear what styling parameter is causing the error.

**Comment by BHare1985** [comment]
The weird thing is that I have no issues in windows, only linux. The other complicated part is that I am using CartoCSS to take mml and convert it to mapnik XML.

1) https://gist.github.com/bh-ms2soft/71c30d3b5b8e1213c141

2) Will be working on this now but just wanted to give an update

**Comment by BHare1985** [comment]
OK this MML

```
#MAPNIK {
	[StyleIndex = 1]{line-color:grey;}
	[zoom = 21] {
		[LinkDir <= 0] { line-offset:  30; }
	}
}
```

I have confirmed my datasource is giving me good values: http://i.imgur.com/lUzMcPA.png


Creates this XML: https://gist.github.com/BHare1985/80770da025f433d01888

Which causes the error, if I take out the `[LinkDir <= 0] { line-offset:  30; }` or `[StyleIndex = 1]{line-color:grey;}` Logic it works, so it seems the AND conditional is causing the error. 

I have diffed our production server (doing the same things) and its working fine but this server (dev) is having this issues. It works fine on Windows, so I am not sure whats going on.

**Comment by springmeyer** [comment]
Thanks for the narrowing work. A couple more thoughts to narrow this down further:

  - Port the testcase to use a CSV datasource (https://github.com/mapnik/mapnik/wiki/A-perfect-testcase). See if you can still replicate.
  - See if you can replicate outside of a server environment. Just run nik2img or some script to read and render the XML on the command line.

**Comment by springmeyer** [comment]
> Just run nik2img or some script to read and render the XML on the command line.

Forgot we were on the node-mapnik issue tracker here. So https://github.com/mapnik/node-mapnik/blob/master/bin/mapnik-render.js would be an easy way to try replicating from the command line.

**Comment by artemp** [comment]
@BHare1985 @springmeyer - puzzling indeed! The only way iteration over `Types...` can fail is when `type_index' gets invalid value : 
https://github.com/mapnik/mapnik/blob/master/include/mapnik/util/variant.hpp#L92
https://github.com/mapnik/mapnik/blob/master/include/mapnik/util/variant.hpp#L108
This would mean some conversions are not working as expected somehow.
 
 @BHare1985 - are you be able to compile mapnik from source on dev box ? If so I can suggest some stderr to verify my assumption and get more info.

Another thing to try is to modify filter expression not to have `<=` to see if this is a problem. For example
does this still fail for you 
```
([LinkDir] = -1) and ([StyleIndex] = 1)<
```
?
BTW, I updated variant as I discovered inconsistent behaviour (https://github.com/mapbox/variant/issues/53) but I don't see this is related here.

**Comment by BHare1985** [comment]
I resolved this temporarily by forcing a dependency to my application to the specific version of mapnik `3.4.5`, rather then rely on tilelive-mapnik's  `">=0.7.25 && <4.0.0"`.

So something since the `3.4.5` release and now things started to get weird for my code/modules. I believe the release after Nov 30th is the culprit but not sure. I will tell you specifically which version if I find the time to debug this myself.  Also worth noting that my mysql plugin also stopped working with the newest mapnik as well (I got binary dispatch: FAIL errors before my plugin stopped though)

**Comment by springmeyer** [comment]
@BHare1985 thanks for further narrowing down. Would you mind checking if you can replicate with node-mapnik@3.4.14  as well?

**Comment by springmeyer** [comment]
bump @BHare1985  - does v3.4.14 work or also error the same ways as releases post v3.4.5?

**Comment by BHare1985** [comment]
Sorry I wasnt able to spin up another instance to test at work. 

3.4.14 wasn't working 2 days ago, and then we tried 3.4.5 and it worked. I cannot confirm which version it stopped working but the error existed with 3.4.14

**Comment by springmeyer** [comment]
At this point we've only seen this one report of this problem. If this problem persists with future releases please re-open a new ticket when you hit it again.
