### ISSUE TITLE
mapnik.Image.data() is not documented

### ISSUE THREAD

**Issue by mikemorris** [mapnik/node-mapnik#574]
Returns underlying image buffer to JavaScript, [`NAN_METHOD(Image::data)`](https://github.com/mapnik/node-mapnik/blob/3db7897524b10428e4087e0c1f5b04c7176f86f1/src/mapnik_image.cpp#L3688-L3693). Not documented at http://mapnik.org/node-mapnik/documentation/#mapnik-image

**Comment by flippmoke** [comment]
@mikemorris you can add the markup [like this](https://github.com/mapnik/node-mapnik/blob/3db7897524b10428e4087e0c1f5b04c7176f86f1/src/mapnik_image.cpp#L1098-L1105) if you want to add it :)
