### ISSUE TITLE
Upgrade libpng to 1.6.20 in SDK for v3.4.13

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#578]
- https://github.com/mapnik/mapnik-packaging/commit/7aef0611450b3564f3c9b8b80e8b86daffdf751e
 - https://github.com/mapbox/windows-builds/commit/63022b0a26ba3e2f5e88ea45009ac2a8ada2fc50

TODO:

  - [x] Rebuild Unix SDK @springmeyer
  - [x] Rebuild Windows SDK @BergWerkGIS

**Comment by BergWerkGIS** [comment]
new `mapnik` Windows SDKs
32bit:
https://s3.amazonaws.com/mapnik/dist/dev/mapnik-win-sdk-v3.0.9-55-gfd6e770-x86-14.0.7z

64bit:
https://s3.amazonaws.com/mapnik/dist/dev/mapnik-win-sdk-v3.0.9-55-gfd6e770-x64-14.0.7z

**Comment by springmeyer** [comment]
Thank you @BergWerkGIS!
