### ISSUE TITLE
Error: invalid index file

### ISSUE THREAD

**Issue by mojodna** [mapnik/node-mapnik#590]
It appears that somewhere in the mapnik-3.4 series the index file format has changed. We're unable to use `.index`es that were created with `shapeindex-0.3.0` using mapnik-3.4.16 (https://github.com/mapnik/node-mapnik-sample-code/issues/6 shows it happening in 3.4.15 as well). We were previously, but I'm not sure how far back at the moment.

We managed to solve it by using the `shapeindex` alternative that now ships with node-mapnik to reindex: `node_modules/.bin/mapnik-shapeindex.js`

**Comment by springmeyer** [comment]
I'm sorry about this change and not documenting it well. I've added details now at https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#3413

> We managed to solve it by using the shapeindex alternative that now ships with node-mapnik to reindex: node_modules/.bin/mapnik-shapeindex.js

That is the intended upgrade process/workaround. In other words, when you upgrade to node-mapnik >= 3.4.13 then you must regenerate .index files. The benefit is then you can use the experimental `--index-parts` option which can lead to faster read for polygons with many geometry parts that are outside the query extents.
