### ISSUE TITLE
Update source build dependencies

### ISSUE THREAD

**Issue by mikemorris** [mapnik/node-mapnik#592]
In https://github.com/mapnik/node-mapnik#source-build

From @flippmoke in chat:
> in general it is very important for the latest node-mapnik to use the latest mapnik

I'm hitting the following error when running `npm install --build-from-source` with the latest versions of `boost` (1.60.0) and `mapnik` (3.0.5) installed via Homebrew. @flippmoke thinks this method may have changed in a newer version of Boost or a more recent version of Mapnik than the latest Homebrew package.

```
../src/mapnik_vector_tile.cpp:4521:18: error: no matching function for call to 'is_valid'
            if (!mapnik::geometry::is_valid(feature->get_geometry(), message))
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/mapnik/geometry_is_valid.hpp:104:13: note: candidate function template not viable: requires single argument 'geom', but 2 arguments were
      provided
inline bool is_valid(T const& geom)
```

Refs mapnik/mapnik/issues/3286 for automated Homebrew publishing

**Comment by springmeyer** [comment]
`npm install --build-from-source` will only work if your `mapnik-config --version` == version value or mapnik stored reported in package.json: https://github.com/mapnik/node-mapnik/blob/688835042710b4aed9c80a8b38cf6159b9452877/package.json#L8.

Latest homebrew packages Mapnik v3.0.12 and latest node-mapnik v3.0.14 does as well, so `npm install --build-from-source` will again work.
