### ISSUE TITLE
Update Mapnik SDK to 3.0.10

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#598]
We will do a node-mapnik 3.4.17 release once Mapnik core is tagged (will be 3.0.10)

Next steps:

  - [x] @artemp leads on Mapnik core
  - [x] @springmeyer rebuilds Mapnik SDK after tag - https://github.com/mapnik/mapnik/issues/3296
  - [x] @mapsam tests latest SDK
  - [x] @mapsam does node-mapnik release with SDK built from official Mapnik tag

**Comment by flippmoke** [comment]
After update publish new versions of:
  * mapnik-omnivore
  * tilelive-omnivore
  * mapbox-upload-validate

**Comment by mapsam** [comment]
Node mapnik `3.4.17` published! https://www.npmjs.com/package/mapnik
