### ISSUE TITLE
Raster-scaling causes Floating point exception

### ISSUE THREAD

**Issue by averas** [mapnik/node-mapnik#600]
I'm generating tiles using tilelive and node-mapnik. In a certain map configuration I have I use a linear color ramp to encode raster values into png tiles. The carto style is:

```
#raster {
  raster-opacity:1;
  raster-scaling:near;
  raster-colorizer-default-mode: linear;
  raster-colorizer-default-color: transparent;
  raster-colorizer-stops:
    stop(0,rgb(0, 0, 0))
    stop(255, rgb(255, 0, 0))
    stop(256, rgb(0, 1, 0))
    stop(511, rgb(255, 1, 0))
    stop(512, rgb(0, 2, 0))
    stop(767, rgb(255, 2, 0))
    stop(768, rgb(0, 3, 0))
    stop(1023, rgb(255, 3, 0))
    ....
```
which gives me a Mapnik XML configuration of:

```
<Style name="raster" filter-mode="first">
  <Rule>
    <RasterSymbolizer opacity="1" scaling="near" default-mode="linear" default-color="rgba(0, 0, 0, 0)" >
	<stop value="0" color="#000000" /> 
	<stop value="255" color="#ff0000" /> 
	<stop value="256" color="#000100" /> 
	<stop value="511" color="#ff0100" /> 
	<stop value="512" color="#000200" /> 
	<stop value="767" color="#ff0200" /> 
	<stop value="768" color="#000300" /> 
	<stop value="1023" color="#ff0300" /> 
    ....
```
As you can see, what I'm doing is encoding the exact raster pixel value into something that I can later read when decoding the tile images client side.

All this works great, **as long as I keep the scaling parameter set to "near" or "fast"**. If I change it to any other algorithm, such as lanczos, node-mapnik generates a couple of tiles (which look fine), and then crashes with a:

<pre>
Floating point exception (core dumped)
</pre>

I have a strong feeling the color interpolation algorithms get in trouble based on my color ramp, I just can't understand why. Any clues?

tilelive 5.12.1
node-mapnik 3.4.16

**Comment by talaj** [comment]
@averas - Does that raster contain no-data pixels? If yes, I very much suspect [this](https://github.com/mapnik/mapnik/blob/ce98a5c81131136cf198db6f24af6cd55ec2626d/include/mapnik/span_image_filter.hpp#L134) as it assumes weight map contains only non-zero values.

Can you please try out `scaling="gaussian"` which has non-zero weight map?

Can you please also try to set no-data to some value which is not present in the raster?

```xml
     <Datasource>                                                            
         <Parameter name="file">...</Parameter>
         <Parameter name="type">gdal</Parameter>                             
         <Parameter name="nodata">-1000</Parameter>            
     </Datasource>                                                           
```

**Comment by averas** [comment]
@talaj 

> Does that raster contain no-data pixels?

Yes, lots of them.

> Can you please try out scaling="gaussian" which has non-zero weight map?

This had no effect (and I had actually already tried this).

> Can you please also try to set no-data to some value which is not present in the raster?

This might be the solution though! Just generated a bunch of tiles without any issues. So looking good so far! This solution obviously causes some "bleeding" into no-data areas though. I'm not sure this is a big issue yet, and the amount of bleeding will certainly differ based on which scaling algorithm I use.

**Comment by talaj** [comment]
It would be great if you can share a piece of the raster so I can reproduce it locally and propose a fix.

**Comment by averas** [comment]
It's a VRT referencing lots of raster files. I could get you one of these files, but that would deviate from my setup, so would not really be representative. I've generated a VRT for you containing only two of these files, and I've made sure the crash happens using that VRT (when not using the fix you proposed). You can either use the that VRT or the raster files separately to reproduce.

The VRT is at 
http://firefly.ibk.se/~racer/dems.vrt
and the references raster files at 
http://firefly.ibk.se/~racer/834f526b-d9c6-43cf-a4bc-46c3a2b8116a/dem_cut.tif
and
http://firefly.ibk.se/~racer/f82bc4b8-423a-4d04-91e0-2da7c63430b9/dem_cut.tif

It seems you will have to try out different zoom levels to provoke the crash.

**Comment by springmeyer** [comment]
> I've generated a VRT for you containing only two of these files, and I've made sure the crash happens using that VRT (when not using the fix you proposed).

Very nicely done (and communicated) @averas. I wanted to add that if you want to take it to the next level see https://github.com/mapnik/mapnik/wiki/A-perfect-testcase. The idea is that testcases that provide a standalone Mapnik XML can then be converted quickly to the format we use for regression/visual tests at https://github.com/mapnik/test-data-visual.

**Comment by talaj** [comment]
@averas - Thanks for those files. I have not been able to reproduce the crash so far. What I miss is an exact bounding box of some crashing tile in extent of the data you posted here and output projection, if there is some reprojection.

**Comment by averas** [comment]
Thanks for the feedback guys. 

@springmeyer Next time I will definitely have a neat perfect test case for you, but for this I actually had problems reproducing this issue in isolation myself, which eventually had me creating a contained repository for this.

@talaj As mentioned above, I had problems recreating it myself when tested in isolation. Anyway, here you are:

```
$ git clone https://github.com/averas/node-mapnik-crash.git
$ cd node-mapnik-crash/
$ npm install
$ node index.js
....
Floating point exception (core dumped)
```

**Comment by talaj** [comment]
@averas - Thank you for the test case. I'm able to reproduce it locally now. As I expected, it's crashing [here](https://github.com/mapnik/mapnik/blob/ce98a5c81131136cf198db6f24af6cd55ec2626d/include/mapnik/span_image_filter.hpp#L134), but I have to figure out why.
It's easily fixable by https://github.com/mapycz/mapnik/commit/8fcc5fbedb2f720b48a94798a3c5f69ba2987f65.

I will send a pull request to Mapnik repo as soon as I will now what is exactly going on.

**Comment by averas** [comment]
@talaj Good to hear you were able to reproduce the crash with the test case, and that you have a potential solution ready. Looking forward to hearing from you when you find the root cause. :-)

**Comment by talaj** [comment]
@averas The problem is [solved in Mapnik](https://github.com/mapnik/mapnik/pull/3349) now.

**Comment by averas** [comment]
@talaj Great work! Thanks for the feedback!
