### ISSUE TITLE
gh-pages & documentation maintenance

### ISSUE THREAD

**Issue by mapsam** [mapnik/node-mapnik#604]
The docs and `gh-pages` branch could use some love. Some maintenance tasks (not all are priority):

- [x] ~~clear out unnecessary files in `gh-pages`. Is there a need for all of the source files in `gh-pages`? Is it a headache to remove them for versioning purposes?~~ this would be a versioning headache
- [ ] research automate any changes in `/documentation` to push to `gh-pages` via travis
- [x] add `index.html` file to `gh-pages` that redirects `mapnik.org/node-mapnik` to `mapnik.org/node-mapnik/documentation`
- [x] if not the above, add some information to `mapnik.org/node-mapnik` so we don't throw a 404
- [x] set up system for versioning our documentation (i.e. `mapnik.org/node-mapnik/documentation/3.5/`)
- [ ] update to docs 4.0.0 #599 

cc @springmeyer @artemp

**Comment by springmeyer** [comment]
pre voice, we'll keep source files across branches to make it easy to merge. All the other items :+1: @mapsam to forge ahead.

**Comment by mapsam** [comment]
Currently blocked on bumping to documentation 4.0.0, filed a ticket https://github.com/documentationjs/documentation/issues/363 for some help.

Working through organizing docs based on versions right now. Since the node mapnik minor versions include API changes, it makes sense to have our API docs mimick minor versions and we can update on every release. Patch changes can be updated within minor API version docs.

Here's what I'm looking at:

![mapnik-docsupdate](https://cloud.githubusercontent.com/assets/1943001/13407798/17f34640-dedf-11e5-8347-fa6bd4ff4ae7.gif)

Notice a couple of things:

* root of the docs exist at `mapnik.org/node-mapnik`. Currently this page just lists out *what* node mapnik is, how to install it, and the documentation versions. I think in the future we can make this page a lot more useful to fit the flow of `mapnik.org`. This removes the 404 you currently see.
* documentation URLs are versioned, right now we have `3.5` and `3.4`.
* `/documentation` URL forwards to the latest `3.5`

**Comment by springmeyer** [comment]
> mapnik.org/node-mapnik

:+1: support your thinking on the phases here: get this in place, develop further as clear doc needs arise.

> documentation URLs are versioned, right now we have 3.5 and 3.4.

Great!

**Comment by mapsam** [comment]
Closing this now that we have #605 merged in. #599 covers `4.0.0` updates!
