### ISSUE TITLE
mapnik@3.5.3 can't be required.

### ISSUE THREAD

**Issue by mojodna** [mapnik/node-mapnik#609]
3.5.2 worked.

`mapnik_settings.js` exists, but it's in `lib/binding/...`, not `package/lib/binding/...`:

```bash
$ find . -name mapnik_settings.js
./node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik_settings.js
```

```bash
$ mkdir /tmp/mapnik
$ cd /tmp/mapnik
$ node -v
v4.2.6
$ npm -v
2.14.12
$ npm install mapnik
/
> mapnik@3.5.3 install /private/tmp/mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

[mapnik] Success: "/private/tmp/mapnik/node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik.node" is installed via remote
mapnik@3.5.3 node_modules/mapnik
├── protozero@1.3.0
└── nan@2.2.0
$ node -p "require('mapnik')"
module.js:328
    throw err;
    ^

Error: Cannot find module '/private/tmp/mapnik/node_modules/mapnik/package/lib/binding/node-v46-darwin-x64/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/private/tmp/mapnik/node_modules/mapnik/package/lib/mapnik.js:8:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by mojodna** [comment]
Part of the problem is that the package is duplicated within `package/`, so `binary.find()` looks beneath that. I can't see anything in the diff that would be responsible (but I also don't see all of the commits shown in the compare view in master, e.g. the 3.5.3 changelog entry):

https://github.com/mapnik/node-mapnik/compare/3.5.2...3.5.3

**Comment by flippmoke** [comment]
@mojodna I can't seem to reproduce locally:

```
mthompson@flippmoke:~$ cd tmp/mapnik/
mthompson@flippmoke:~/tmp/mapnik$ node -v
v4.2.6
mthompson@flippmoke:~/tmp/mapnik$ npm -v
2.14.12
mthompson@flippmoke:~/tmp/mapnik$ npm install mapnik
\
> mapnik@3.5.3 install /Users/mthompson/tmp/mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

[mapnik] Success: "/Users/mthompson/tmp/mapnik/node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik.node" is installed via remote
mapnik@3.5.3 node_modules/mapnik
├── protozero@1.3.0
└── nan@2.2.0
```

`npm cache clean` and try again?

**Comment by mojodna** [comment]
It installs fine but can't actually be required.

Try running:

```bash
node -p "require('mapnik')"
```

**Comment by flippmoke** [comment]
doh, missed that line sorry.

**Comment by mojodna** [comment]
Meh, I should have split the commands out to make it clearer.

**Comment by flippmoke** [comment]
I am thinking that @springmeyer published something when he had a `packages` directory already?

**Comment by calvinmetcalf** [comment]
could you guys unpublish it as soon as you get a chance?

**Comment by flippmoke** [comment]
It is now unpublished, closing this ticket for now.

**Comment by mojodna** [comment]
Thanks!

**Comment by calvinmetcalf** [comment]
thanks!

**Comment by springmeyer** [comment]
Thanks for the quick report @mojodna and for the unpublish @flippmoke 

> I am thinking that @springmeyer published something when he had a packages directory already?

Yes, looking back now that is what happened. I had been testing `npm pack` results last week and untarred that had left behind a `package` directory that then got packaged again. I've committed https://github.com/mapnik/node-mapnik/commit/070eb1fc906bd47d47c9ac01dad615554a5dad95 which should prevent this ever happening in the future.

**Comment by volkanunsal** [comment]
I'm experiencing the same issue with version 3.6.2. The package installs but when required throws a similar error:

```
Error: Cannot find module '/tmp/node_modules/mapnik/lib/binding/mapnik_settings.js'
      at Function.Module._resolveFilename (module.js:513:15)
```

**Comment by volkanunsal** [comment]
Here is a simple Dockerfile to replicate it

```Dockerfile
```
