### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by zackarychapple** [mapnik/node-mapnik#621]
Both 3.5.5 and 3.5.6 get the below build error for me on OSX Mavericks. 3.5.4 builds with no issue. 

Versions of NPM and Node
```
ROSELCDV000101N:material2 chapplez$ node --version && npm --version
v4.2.1
2.14.7
```

Error:

```
ROSELCDV000101N:material2 chapplez$ npm install
-
> mapnik@3.5.5 install /Users/chapplez/code/playground/material2/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/chapplez/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/chapplez/.nvm/versions/node/v4.2.1/bin/node" "/Users/chapplez/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/chapplez/code/playground/material2/node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik.node" "--module_name=mapnik" "--module_path=/Users/chapplez/code/playground/material2/node_modules/mapnik/lib/binding/node-v46-darwin-x64"
gyp ERR! cwd /Users/chapplez/code/playground/material2/node_modules/mapnik
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/chapplez/.nvm/versions/node/v4.2.1/bin/node /Users/chapplez/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/chapplez/code/playground/material2/node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik.node --module_name=mapnik --module_path=/Users/chapplez/code/playground/material2/node_modules/mapnik/lib/binding/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/chapplez/code/playground/material2/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/chapplez/.nvm/versions/node/v4.2.1/bin/node" "/Users/chapplez/code/playground/material2/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/chapplez/code/playground/material2/node_modules/mapnik
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.24
node-pre-gyp ERR! not ok 
Failed to execute '/Users/chapplez/.nvm/versions/node/v4.2.1/bin/node /Users/chapplez/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/chapplez/code/playground/material2/node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik.node --module_name=mapnik --module_path=/Users/chapplez/code/playground/material2/node_modules/mapnik/lib/binding/node-v46-darwin-x64' (1)
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/chapplez/.nvm/versions/node/v4.2.1/bin/node" "/Users/chapplez/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.5.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.5.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chapplez/code/playground/material2/npm-debug.log
```

**Comment by springmeyer** [comment]
Thanks for reporting. We are missing binaries for node 4 due to an nvm bug that was causing a silently failure to install node 4 and ended up defaulting to node 5 (https://travis-ci.org/mapnik/node-mapnik/jobs/118982636#L54):

```
Downloading https://nodejs.org/dist/v4.4.1/node-v4.4.1-darwin-x64.tar.gz...
######################################################################## 100.0%
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local/Cellar/nvm/0.31.0/versions/node/v4.4.1"
Run `npm config delete prefix` or `nvm use --delete-prefix v4.4.1` to unset it.
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local/Cellar/nvm/0.31.0/versions/node/v4.4.1"
Run `npm config delete prefix` or `nvm use --delete-prefix v4.4.1` to unset it.
v5.9.0
3.7.3
/usr/local/bin/node
```

**Comment by springmeyer** [comment]
@zackarychapple hang tight - will fix in a sec.


@mapnik/devs This should be fixed by https://github.com/mapnik/node-mapnik/commit/fffca068ed144b07a8d0c39549a5f80a472251ba. I will kick off a `[publish binary]` build for v3.5.6 and will expect the node v4 target for travis to succeed while the other targets should fail (since binaries already exist).

**Comment by springmeyer** [comment]
@zackarychapple - can you try installing v3.5.6 again? Should work now.

**Comment by zackarychapple** [comment]
:+1: Works now.  Thanks!

**Comment by nidhi-pandey-jixtra** [comment]
@springmeyer This issue is coming again.

Here are the logs:

> 
> > mapnik@3.5.14 install /Users/Username/Downloads/tiletools/node_modules/mapnik
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v51-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
> /bin/sh: mapnik-config: command not found
> gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Darwin 16.0.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Username/Downloads/tiletools/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node" "--module_name=mapnik" "--module_path=/Users/Username/Downloads/tiletools/node_modules/mapnik/lib/binding/node-v51-darwin-x64"
> gyp ERR! cwd /Users/Username/Downloads/tiletools/node_modules/mapnik
> gyp ERR! node -v v7.4.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Username/Downloads/tiletools/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node --module_name=mapnik --module_path=/Users/Username/Downloads/tiletools/node_modules/mapnik/lib/binding/node-v51-darwin-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Username/Downloads/tiletools/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> node-pre-gyp ERR! System Darwin 16.0.0
> node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Username/Downloads/tiletools/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /Users/Username/Downloads/tiletools/node_modules/mapnik
> node-pre-gyp ERR! node -v v7.4.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.34
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Username/Downloads/tiletools/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node --module_name=mapnik --module_path=/Users/Username/Downloads/tiletools/node_modules/mapnik/lib/binding/node-v51-darwin-x64' (1)
> nan@2.4.0 node_modules/sqlite3/node_modules/nan -> node_modules/nan
> - abbrev@1.1.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/abbrev
> - ansi-regex@2.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/ansi-regex
> - aproba@1.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/aproba
> - asn1@0.2.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/asn1
> - assert-plus@0.2.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/assert-plus
> - asynckit@0.4.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/asynckit
> - aws-sign2@0.6.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/aws-sign2
> - aws4@1.6.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/aws4
> - balanced-match@0.4.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/balanced-match
> - buffer-shims@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/buffer-shims
> - caseless@0.12.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/caseless
> - co@4.6.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/co
> - code-point-at@1.1.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/code-point-at
> - concat-map@0.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/concat-map
> - brace-expansion@1.1.7 node_modules/tilelive-vector/node_modules/mapnik/node_modules/brace-expansion
> - console-control-strings@1.1.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/console-control-strings
> - core-util-is@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/core-util-is
> - assert-plus@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/dashdash/node_modules/assert-plus
> - dashdash@1.14.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/dashdash
> - deep-extend@0.4.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/deep-extend
> - delayed-stream@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/delayed-stream
> - combined-stream@1.0.5 node_modules/tilelive-vector/node_modules/mapnik/node_modules/combined-stream
> - delegates@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/delegates
> - extend@3.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/extend
> - extsprintf@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/extsprintf
> - forever-agent@0.6.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/forever-agent
> - fs.realpath@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/fs.realpath
> - assert-plus@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/getpass/node_modules/assert-plus
> - getpass@0.1.6 node_modules/tilelive-vector/node_modules/mapnik/node_modules/getpass
> - graceful-fs@4.1.11 node_modules/tilelive-vector/node_modules/mapnik/node_modules/graceful-fs
> - har-schema@1.0.5 node_modules/tilelive-vector/node_modules/mapnik/node_modules/har-schema
> - has-unicode@2.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/has-unicode
> - hoek@2.16.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/hoek
> - boom@2.10.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/boom
> - cryptiles@2.0.5 node_modules/tilelive-vector/node_modules/mapnik/node_modules/cryptiles
> - inherits@2.0.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/inherits
> - block-stream@0.0.9 node_modules/tilelive-vector/node_modules/mapnik/node_modules/block-stream
> - ini@1.3.4 node_modules/tilelive-vector/node_modules/mapnik/node_modules/ini
> - is-typedarray@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/is-typedarray
> - isarray@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/isarray
> - isstream@0.1.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/isstream
> - jsbn@0.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/jsbn
> - ecc-jsbn@0.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/ecc-jsbn
> - jodid25519@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/jodid25519
> - json-schema@0.2.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/json-schema
> - json-stringify-safe@5.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/json-stringify-safe
> - jsonify@0.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/jsonify
> - json-stable-stringify@1.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/json-stable-stringify
> - ajv@4.11.6 node_modules/tilelive-vector/node_modules/mapnik/node_modules/ajv
> - har-validator@4.2.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/har-validator
> - assert-plus@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/jsprim/node_modules/assert-plus
> - mime-db@1.27.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/mime-db
> - mime-types@2.1.15 node_modules/tilelive-vector/node_modules/mapnik/node_modules/mime-types
> - form-data@2.1.4 node_modules/tilelive-vector/node_modules/mapnik/node_modules/form-data
> - minimatch@3.0.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/minimatch
> - minimist@0.0.8 node_modules/tilelive-vector/node_modules/mapnik/node_modules/minimist
> - mkdirp@0.5.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/mkdirp
> - ms@0.7.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/ms
> - debug@2.6.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/debug
> - number-is-nan@1.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/number-is-nan
> - is-fullwidth-code-point@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/is-fullwidth-code-point
> - oauth-sign@0.8.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/oauth-sign
> - object-assign@4.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/object-assign
> - os-homedir@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/os-homedir
> - os-tmpdir@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/os-tmpdir
> - osenv@0.1.4 node_modules/tilelive-vector/node_modules/mapnik/node_modules/osenv
> - nopt@4.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/nopt
> - path-is-absolute@1.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/path-is-absolute
> - performance-now@0.2.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/performance-now
> - process-nextick-args@1.0.7 node_modules/tilelive-vector/node_modules/mapnik/node_modules/process-nextick-args
> - punycode@1.4.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/punycode
> - qs@6.4.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/qs
> - minimist@1.2.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/rc/node_modules/minimist
> - safe-buffer@5.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/safe-buffer
> - semver@5.3.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/semver
> - set-blocking@2.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/set-blocking
> - signal-exit@3.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/signal-exit
> - sntp@1.0.9 node_modules/tilelive-vector/node_modules/mapnik/node_modules/sntp
> - hawk@3.1.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/hawk
> - assert-plus@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/sshpk/node_modules/assert-plus
> - string_decoder@1.0.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/string_decoder
> - stringstream@0.0.5 node_modules/tilelive-vector/node_modules/mapnik/node_modules/stringstream
> - strip-ansi@3.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/strip-ansi
> - string-width@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/string-width
> - strip-json-comments@2.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/strip-json-comments
> - rc@1.2.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/rc
> - tough-cookie@2.3.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/tough-cookie
> - tunnel-agent@0.6.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/tunnel-agent
> - tweetnacl@0.14.5 node_modules/tilelive-vector/node_modules/mapnik/node_modules/tweetnacl
> - bcrypt-pbkdf@1.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/bcrypt-pbkdf
> - sshpk@1.11.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/sshpk
> - uid-number@0.0.6 node_modules/tilelive-vector/node_modules/mapnik/node_modules/uid-number
> - util-deprecate@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/util-deprecate
> - readable-stream@2.2.9 node_modules/tilelive-vector/node_modules/mapnik/node_modules/readable-stream
> - are-we-there-yet@1.1.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/are-we-there-yet
> - uuid@3.0.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/uuid
> - verror@1.3.6 node_modules/tilelive-vector/node_modules/mapnik/node_modules/verror
> - jsprim@1.4.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/jsprim
> - http-signature@1.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/http-signature
> - request@2.81.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/request
> - wide-align@1.1.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/wide-align
> - gauge@2.7.3 node_modules/tilelive-vector/node_modules/mapnik/node_modules/gauge
> - npmlog@4.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/npmlog
> - wrappy@1.0.2 node_modules/tilelive-vector/node_modules/mapnik/node_modules/wrappy
> - once@1.4.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/once
> - inflight@1.0.6 node_modules/tilelive-vector/node_modules/mapnik/node_modules/inflight
> - glob@7.1.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/glob
> - rimraf@2.6.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/rimraf
> - fstream@1.0.11 node_modules/tilelive-vector/node_modules/mapnik/node_modules/fstream
> - fstream-ignore@1.0.5 node_modules/tilelive-vector/node_modules/mapnik/node_modules/fstream-ignore
> - tar@2.2.1 node_modules/tilelive-vector/node_modules/mapnik/node_modules/tar
> - tar-pack@3.4.0 node_modules/tilelive-vector/node_modules/mapnik/node_modules/tar-pack
> - node-pre-gyp@0.6.34 node_modules/tilelive-vector/node_modules/mapnik/node_modules/node-pre-gyp
> - nan@2.4.0 node_modules/tilelive-vector/node_modules/nan
> protozero@1.4.5 node_modules/tilelive-vector/node_modules/protozero -> node_modules/protozero
> mapnik@3.5.14 node_modules/tilelive-vector/node_modules/mapnik -> node_modules/mapnik
> /Users/Username/Downloads/tiletools
> ├── mbtiles@0.9.0 
> ├── tessera@0.10.0 
> ├── tilejson@1.0.3 
> ├── tilelive@5.12.3 
> ├── tilelive-file@0.0.3 
> ├── tilelive-http@0.11.3 
> ├── tilelive-mapbox@0.4.0 
> ├── tilelive-s3@6.5.0 
> ├── tilelive-tmstyle@0.6.0 
> ├── tilelive-utfgrid@0.2.0 
> ├── UNMET DEPENDENCY tilelive-vector@latest
> └─┬ tl@0.9.0 
>   └── nomnom@1.7.0  (git+https://github.com/mojodna/nomnom.git#39a68fd9647c180cba00ff76cc6b53e239060638)
> 
> npm WARN enoent ENOENT: no such file or directory, open '/Users/Username/Downloads/tiletools/package.json'
> npm WARN tiletools No description
> npm WARN tiletools No repository field.
> npm WARN tiletools No README data
> npm WARN tiletools No license field.
> npm ERR! Darwin 16.0.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "tessera" "tl" "mbtiles" "mapnik" "tilelive" "tilelive-file" "tilelive-http" "tilelive-mapbox" "tilelive-mapnik" "tilelive-s3" "tilelive-tmsource" "tilelive-tmstyle" "tilelive-utfgrid" "tilelive-vector" "tilejson" "--save"
> npm ERR! node v7.4.0
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mapnik@3.5.14 install script 'node-pre-gyp install --fallback-to-build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mapnik package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mapnik
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mapnik
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/Username/Downloads/tiletools/npm-debug.log

NPM Version: 4.0.5
Node Version: 7.4.0

**Comment by flippmoke** [comment]
> Node Version: 7.4.0

We are not currently building binaries for node v7 - try v6 which is the current LTS.

**Comment by OnkelTem** [comment]
Current LTS is 8.9.0

It doesn't build
