### ISSUE TITLE
PostGIS connexion hang...

### ISSUE THREAD

**Issue by geomartino** [mapnik/node-mapnik#624]
Is there a way to check/debug why the mapnik.Datasource() method keep hanging with no return?
in fact, the error I get is this one:
Error: Postgis Plugin: timeout expired

The database settings has been verify with a pgadmin client and everything is ok.  The DB also accept all host (*).  The geo_mercator field is in SRID 900913.

`var postgis_settings = {
  'host' : '<servername>',
  'port': '<port>',
  'dbname' : '<dbname>',
  'table' : '<table>',
  'user' : '*',
  'password' : '*',
  'type' : 'postgis',
  'geometry_field': 'geom_mercator',
 'initial_size' : '10',
 'estimate_extent' : '1'
};
var postgis = new mapnik.Datasource(postgis_settings);
`

**Comment by four43** [comment]
Can you connect to the database from node not using mapnik? Just using a postgres driver to make a query?

**Comment by geomartino** [comment]
You are right Seth, the problem is not related to mapnik at all because just a simple tests with node/pg package hang also when trying to connect.  
All the port are open (5432 for pg, 8000 for node), so I don't understand why the connexion is not working.  
My database is running on a remote machine so do I have to set something in particular for nodejs in that case?

**Comment by four43** [comment]
If you have shell access to your node server I would ssh into it and try `telnet [postgis server] 5432` to see if it connects. Telnet is a really simple program that can open a connection to a server on a given port. If that doesn't connect (just hangs), you still have a networking issue - could be firewall or postgres isn't binding to 0.0.0.0, but if it connects it could point you to a node problem.

**Comment by geomartino** [comment]
telnet [postgis server] 5432 still hang.  How can I check if postgres is binding to 0.0.0.0?
if you are referring to listen_addresses, I set it to "*"
in the postgresql.conf, I also see the commented unix_socket_permissions parameter, any chance it could be related?

thanks again for your help on this Seth, I know it's not the right place to have that conversation because it's not related to mapnik anymore but I will find a way to sahe this discussion at the right place when I figured it out.

**Comment by four43** [comment]
Ooh one more fun little trick, if you have shell access to your DB server you can run `sudo netstat -tulpn` to see what ports are bound to what address. It will show you processes bound to TCP IPv6 and classic IPv4 addresses. If you see the `:5432` bound to something like 127.0.0.1 you know you have Postgres binding issues. Try that real quick! It's pretty neat.

**Comment by geomartino** [comment]
Based on what you said, everything seem t be ok?
![tulon](https://cloud.githubusercontent.com/assets/837765/14358359/90f09ab8-fcba-11e5-8b6d-95301eac2dee.png)

**Comment by springmeyer** [comment]
I'll add: Mapnik/node-mapnik use libpq internally. Which is what `psql` command line program uses. They both respond to the same options and environment variables. So you should be able to debug this issue completely outside of Mapnik. Since this is unrelated to Mapnik I'll close this issue now.

**Comment by brianreavis** [comment]
@geomartino Adding to what @springmeyer said: Double check you're not SSH tunneling with pgadmin. Firewalls will cause your connection to hang. If you're on AWS for instance, you'll have to add port 5432 to Inbound Rules for the Security Group the instance is bound to.
