### ISSUE TITLE
Infinite loop on npm install mapnik 

### ISSUE THREAD

**Issue by d-fnc** [mapnik/node-mapnik#630]
Hello everyone!

Basically what the problem is, if i try to install mapnik locally with the "npm install mapnik" command, it's trying to install 'node-pre-gyp' over and over again. I think it's in an infinite loop for some reason. New staging directories are created inside staging directories, and so forth.

Im on Ubuntu 14.04 and my npm and node versions are the following: 
node --version && npm --version
v0.12.12
3.8.1

I'm pretty sure it's a bug, but maybe i'm doing something wrong. I can not post an error log, since it doesn't register as an error.
Please advise.
Regards, Ferenc.

**Comment by tjwebb** [comment]
@mojodna this is not an issue with npm3, it's an issue with this project. See my issue here: https://github.com/mapnik/node-mapnik/issues/650

**Comment by brianreavis** [comment]
@tjwebb I think you're mistaken. `npm install {some other package}` (as is the case in the preinstall hook) *should not* run the preinstall hook of the current package.

**Comment by springmeyer** [comment]
Closing per https://github.com/mapnik/node-mapnik/issues/650#issuecomment-229747309
