### ISSUE TITLE
unsigned integer overflow in blend.cpp

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#632]
Caught using `-fsanitize=integer` and running https://github.com/mapbox/node-blend tests:

```
../src/blend.cpp:312:28: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
```

https://github.com/mapnik/node-mapnik/blob/3c04401b0f40afc4bbd8519e7b51f95c6bac892b/src/blend.cpp#L312

**Comment by artemp** [comment]
```c++
Images::reverse_iterator rit = baton->images.rbegin();
    Images::reverse_iterator rend = baton->images.rend();
    for (int index = total - 1; rit != rend; rit++, index--) {
```
this should use prefix increment, right ? ^ /cc @springmeyer
