### ISSUE TITLE
v3.5.14 release planning

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#634]
Aiming to get the next node-mapnik on latest mapnik and gdal. I'll plan to call this node-mapnik `v3.5.14`, but happy to have it be `v3.5.15` or higher if anyone needs a `v3.5.14` sooner for bug fixes.

  - [x] mapnik v3.0.12 - https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.12
  - [x] gdal 2.1.0 (https://trac.osgeo.org/gdal/wiki/Release/2.1.0-News / https://github.com/naturalatlas/node-gdal/issues/164)

**Comment by brendanvinson** [comment]
When do you estimate a tag for this being available?

**Comment by springmeyer** [comment]
@brendanvinson next Monday.

**Comment by springmeyer** [comment]
Delayed as I'm juggling a few things. Shooting now for the end of the week.

**Comment by yohanboniface** [comment]
Is a there a workaround in the meantime to get a node-mapnik running with node 6.0?

**Comment by tomhughes** [comment]
Well the current node-mapnik won't build with the current mapnik anyway, so getting a new node-mapnik isn't going to help me with node 6 support (which has now been pushed in Fedora Rawhide breaking node-mapnik) until we have a new mapnik release as well...

**Comment by tomhughes** [comment]
Ah I see this ticket has mapnik 3.0.12 as a dependency.

**Comment by brendanvinson** [comment]
@springmeyer Do you have an updated ETA on this?

**Comment by vjpr** [comment]
Bump

**Comment by springmeyer** [comment]
Delayed due to busyness and juggling a variety of things. New ETA is late next week.

**Comment by brendanvinson** [comment]
Any further word on this?

**Comment by sebastic** [comment]
With dbd1b2d 3.5.14 seems to be ready, the release tag is still missing though.

**Comment by springmeyer** [comment]
Tasks that need to be hit before the tag will land:

   - [ ] mapnik-swoop tests passing per https://github.com/mapnik/node-mapnik/blob/master/CONTRIBUTING.md#mapnik-swoop
     - current failures are mapnik-omnivore and tilelive-bridge (@artemp is investigating)
   - [ ] doc updates (@mapsam)
   - [ ] changelog updated

**Comment by springmeyer** [comment]
Closing: mapnik@3.5.14 is now published.

**Comment by mapsam** [comment]
Lovely @springmeyer!
