### ISSUE TITLE
Non NULL terminated strings and strcmp

### ISSUE THREAD

**Issue by artemp** [mapnik/node-mapnik#635]
I see a lot of code snippets like 

```c++
if (strcmp(*v8::String::Utf8Value(format_val), "jpeg") == 0) {}
```

* strcmp - compares two null-terminated byte strings lexicographically http://en.cppreference.com/w/c/string/byte/strcmp 
* v8::Strings are not NULL terminated e.g can have `\0` anywhere `'A\u0000Z'`

So it's possible to have format_val = 'jpeg\0bonkers big bytes by bad buddy blows ....big bang` 
Does anyone see an issue here ? 

/cc @lightmare @springmeyer 
Also, it's considered a good practice to prefix "C" library functions with `std` when used in `c++`

**Comment by springmeyer** [comment]
:+1 to fix. Looks like these are only in `src/blend.cpp` which means they are carry over from the node-blend port to node-mapnik.
