### ISSUE TITLE
NodeJS 6 Support

### ISSUE THREAD

**Issue by ddproxy** [mapnik/node-mapnik#636]
No pressure here, just noticed the other day that we were having issues getting node-mapnik to build on NodeJS 6 release. I know it was just released (this week) so I'm not too concerned, I'm just preparing for a nerd-battle between different languages and I'm hoping the jump to nJS 6 would give us the extra edge ;)

**Comment by springmeyer** [comment]
Done in #637, binaries will be available in the upcoming tag: https://github.com/mapnik/node-mapnik/issues/634

**Comment by tjwebb** [comment]
@ddproxy if you're tired of waiting, like I was, I've compiled and published node 6 binaries for linux and osx: https://github.com/langateam/node-mapnik/blob/master/package.json#L14.
