### ISSUE TITLE
not found vector_tile_config.hpp

### ISSUE THREAD

**Issue by vahid-01** [mapnik/node-mapnik#638]
nodejs version 6

error : 
vahid@vahid-P61A-D3:~/Downloads/test$ npm uninstall mapnik 
npm WARN enoent ENOENT: no such file or directory, open '/home/vahid/package.json'
npm WARN vahid No description
npm WARN vahid No repository field.
npm WARN vahid No README data
npm WARN vahid No license field.
vahid@vahid-P61A-D3:~/Downloads/test$ sudo npm install mapnik
npm WARN lifecycle mapnik@3.5.13~preinstall: cannot run in wd %s %s (wd=%s) mapnik@3.5.13 npm install node-pre-gyp /home/vahid/node_modules/.staging/mapnik-deb17200

> mapnik@3.5.13 install /home/vahid/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

(node:17175) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17184) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17184) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:17229) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
make: Entering directory `/home/vahid/node_modules/mapnik/build'
  ACTION binding_gyp_make_vector_tile_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /home/vahid/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik_settings.js
  TOUCH Release/obj.target/make_vector_tile.stamp
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
  CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
../src/node_mapnik.cpp:2:34: fatal error: vector_tile_config.hpp: No such file or directory
 #include "vector_tile_config.hpp"
                                  ^
compilation terminated.
make: *** [Release/obj.target/mapnik/src/node_mapnik.o] Error 1
make: Leaving directory `/home/vahid/node_modules/mapnik/build'

**Comment by denaje** [comment]
Got this error as well on version 3.5.13 and several versions before. My output when attempting to `npm install`:

```
npm WARN mapnik@3.5.13 No license field.

> mapnik@3.5.13 install /home/jdenardo/pixelgator/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/jdenardo/pixelgator/node_modules/mapnik/build'
  ACTION binding_gyp_make_vector_tile_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik_settings.js
  TOUCH Release/obj.target/make_vector_tile.stamp
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
  CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
../src/node_mapnik.cpp:2:34: fatal error: vector_tile_config.hpp: No such file or directory
compilation terminated.
mapnik.target.mk:196: recipe for target 'Release/obj.target/mapnik/src/node_mapnik.o' failed
make: *** [Release/obj.target/mapnik/src/node_mapnik.o] Error 1
make: Leaving directory '/home/jdenardo/pixelgator/node_modules/mapnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.5.1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik.node" "--module_name=mapnik" "--module_path=/home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /home/jdenardo/pixelgator/node_modules/mapnik
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik.node --module_name=mapnik --module_path=/home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jdenardo/pixelgator/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.5.1-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/jdenardo/pixelgator/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/jdenardo/pixelgator/node_modules/mapnik
node-pre-gyp ERR! node -v v6.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik.node --module_name=mapnik --module_path=/home/jdenardo/pixelgator/node_modules/mapnik/lib/binding/node-v48-linux-x64' (1)
pixelgator@1.0.0 /home/jdenardo/pixelgator
└── (empty)

npm WARN pixelgator@1.0.0 No repository field.
npm ERR! Linux 4.5.1-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.5.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.5.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jdenardo/pixelgator/npm-debug.log
npm ERR! code 1
```

[npm-debug.txt](https://github.com/mapnik/node-mapnik/files/245752/npm-debug.txt)

**Comment by vahid-01** [comment]
I solved that problem by changed nodejs version to 4.4.3.

**Comment by denaje** [comment]
Thanks for the info. I downgraded to 5.11.0 and it worked for me.

**Comment by tjwebb** [comment]
Also seeing this in node 6.2.0. Would love a prebuilt binary for the latest node release.

**Comment by davenquinn** [comment]
This has been a problem with any source build for the past few months. The only way to get around it is to clone the repository and run `make` locally, and link into `node_modules`. Any insight into why this is the case @springmeyer? Prior to January(ish) this wasn't a problem.

**Comment by tjwebb** [comment]
@davenquinn @denaje @vahid-01  I've compiled and published node 6 binaries for linux and osx: https://github.com/langateam/node-mapnik/blob/master/package.json#L14.

**Comment by springmeyer** [comment]
Node v6 binaries will be landing with #634. Until then stick to node v4.
