### ISSUE TITLE
could not zoom to combined layer extents using zoom_all because proj4 could not back project any layer extents into the map srs

### ISSUE THREAD

**Issue by kyawmyintthein** [mapnik/node-mapnik#639]
Here is my style.xml

<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">

  <Style name="color relief style">
    <Rule>
      <RasterSymbolizer />
    </Rule>
  </Style>

  <Style name="slopeshade style">
    <Rule>
      <RasterSymbolizer opacity="0.85" comp-op="multiply" scaling="bilinear" />
    </Rule>
  </Style> 
  
  <Style name="hillshade style">
    <Rule>
      <RasterSymbolizer opacity="0.6" comp-op="multiply" scaling="bilinear" />
    </Rule>
  </Style>
  
  <Style name="rivers style">
    <Rule>
      <LineSymbolizer stroke="rgb(255,255,255)" stroke-width="1" />
    </Rule>
  </Style>

  <Layer name="color relief" srs="+proj=utm +zone=48 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs">
    <StyleName>color relief style</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">data/S07E106_utm48s_relief.tif</Parameter>
    </Datasource>
  </Layer>

  <Layer name="slopeshade" srs="+proj=utm +zone=48 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs">
    <StyleName>slopeshade style</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">data/S07E106_utm48s_slopeshade.tif</Parameter>
    </Datasource>
  </Layer>

  <Layer name="hillshade" srs="+proj=utm +zone=48 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs">
    <StyleName>hillshade style</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">data/S07E106_utm48s_hs.tif</Parameter>
    </Datasource>
  </Layer> 

  <Layer name="rivers" srs="+proj=utm +zone=48 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs">
    <StyleName>rivers style</StyleName>
    <Datasource>
      <Parameter name="type">shape</Parameter>
      <Parameter name="file">data/s07e106_25m.shp</Parameter>
    </Datasource>
  </Layer> 

</Map>

**Comment by springmeyer** [comment]
The problem is probably that the `srs` defined for your layers is not correct (does not match your datasource).
