### ISSUE TITLE
Property values from GeoJSON stored as arrays and objects do not preserve spaces

### ISSUE THREAD

**Issue by mapsam** [mapnik/node-mapnik#642]
When decoding a vector tile into a GeoJSON using using `vectortile.toGeoJSON` the values of the GeoJSON properties that are stored as arrays or objects are missing all of their spaces. 

Here's the input file properties example:
```JSON
{
  "properties": {
  "object": {
    "name": "waka flocka"
  },
  "array": ["waka flocka"],
  "name": "waka flocka"
}
```

Output geometry properties
```JSON
{
  "properties": {
  "object": {
    "name": "wakaflocka"
  },
  "array": ["wakaflocka"],
  "name": "waka flocka"
}
```

Notice the values in `object` and `array` are now missing spaces. 

Also, each value is stored as a string rather than an object or array. Here's a test I've written to explain what I'm seeing:

```javascript
it.only('preserve spaces in values that are objects themselves', function(done) {
    var vtile = new mapnik.VectorTile(0,0,0);
    var geojson = {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            "object": {
              "name": "waka flocka"
            },
            "array": ["waka flocka"],
            "name": "waka flocka"
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [-90, -19.31114335506463],
                [-90, 71.1877539181316],
                [101.25, 71.1877539181316],
                [101.25, -19.31114335506463],
                [-90, -19.31114335506463]
              ]
            ]
          }
        }
      ]
    };

    vtile.addGeoJSON(JSON.stringify(geojson),'layer-name');
    var gj = JSON.parse(vtile.toGeoJSONSync('layer-name'));
    var props = gj.features[0].properties;
    assert.equal(props.name, 'waka flocka', 'string preserves spaces');
    // are objects & arrays always stored as strings? Do we always have to JSON parse twice?
    assert.equal(JSON.parse(props.array)[0], 'waka flocka', 'array preserves spaces');
    assert.equal(JSON.parse(props.object).name, 'waka flocka', 'object preserves spaces');
    done();
});
```

New test is failing over at [`gj-key-underscore-test`](https://travis-ci.org/mapnik/node-mapnik/builds/127637052) (sorry, terrible branch name).

cc/ @flippmoke @artemp @springmeyer @danswick

**Comment by springmeyer** [comment]
> Also, each value is stored as a string rather than an object or array.

This is by design: is was the only feasible way to preserve arbitrary objects when round tripped (previously they would be dropped). See https://github.com/mapnik/mapnik/issues/2678 (and especially the linked tickets) for the background on why.

> properties that are stored as arrays or objects are missing all of their spaces

o_O that is not intended! Nice catch. Probably a bug in the code added to Mapnik (https://github.com/mapnik/mapnik/commit/ae9eafa2c1b0d23a3e8bd3bd94cbd4a65edf107b) to accept these objects as strings: next step would be to see if you can replicate with Mapnik core alone.

**Comment by artemp** [comment]
@mapsam - after https://github.com/mapnik/mapnik/commit/db912d9b67bc7f314420ae4f9c9388692e0b8ad7
 
```python
>>> f["array"]
'["waka jawaka"]'
>>> f["object"]
'{\n    "name": "waka jawaka"\n  }'
```
NOTE: objects and arrays are preserved as it is e.g white space ^ 

Let me know if this solves this issue for now. To handle object/array properly we'll need to change how values are stored in feature.   
/cc @springmeyer -

**Comment by mapsam** [comment]
Confirmed Mapnik core preservers spaces after @artemp's fixes. This should be fixed in the next release of Mapnik and updated here.

**Comment by springmeyer** [comment]
Great @mapsam, so I'll close and consider this done once #634 is finished (in my court).
