### ISSUE TITLE
Boost?

### ISSUE THREAD

**Issue by brendanvinson** [mapnik/node-mapnik#644]
I currently have node-mapnik 3.5.13 installed (and eagerly waiting for 3.5.14 for node 6 support, but I digress...) and it runs fine, but I did have a question regarding boost.

Does it come with the package and/or are there benefits to installing it on the server? I've tried searching both Google and the repository, but I can't seem to find a definitive answer to this.

Server: CentOS 7.2
Memory ~1 GB
Node: 5.11
Node-Mapnik Version: 3.5.13

Thanks!

**Comment by brendanvinson** [comment]
Just tried logging out `mapnik.versions`:
```js
{ node: '5.10.1',
v8: '4.6.85.31',
boost: '1.59.0',
boost_number: 105900,
mapnik: '3.0.11',
mapnik_number: 300011,
mapnik_git_describe: 'v3.0.11',
cairo: '1.14.4' }
```

So I'm assuming yes, though it seems odd that it's not recognizing the correct node version.

**Comment by brianreavis** [comment]
> odd that it's not recognizing the correct node version

This is the version of node that node-mapnik is compiled against.

**Comment by brendanvinson** [comment]
Compiled... on your end?

To get the node version on my system would I need to install from source?

**Comment by tjwebb** [comment]
@brendanvinson I've compiled and published node 6 binaries for linux and osx: https://github.com/langateam/node-mapnik/blob/master/package.json#L14.

**Comment by springmeyer** [comment]
> Does it come with the package and/or are there benefits to installing it on the server?

If you depend on node-mapnik binaries then boost comes compiled inside the binaries and you don't need to install it externally. If you build from source `npm install --build-from-source` and provide your own Mapnik core version to build node-mapnik against, then node-mapnik will use the boost on your system that Mapnik used and it will get this via `mapnik-config --includes`.
