### ISSUE TITLE
XML entities not working

### ISSUE THREAD

**Issue by turban** [mapnik/node-mapnik#646]
I'm not getting XML entities to work with node-mapnik. In the changelog for 1.4.4 I read:

"Mapnik now build with rapidxml/ptree xml parser rather than libxml2 (meaning no xincludes or entities are supported)".

Are there other ways of using variables or include other XML stylesheets in node-mapnik? Is it possible to configure node-mapnik to support XML entities and includes?

**Comment by tomhughes** [comment]
This is really a mapnik issue rather than a node-mapnik issue, as it depends on what XML parser you have configured your mapnik build to use.

You can still use libxml2 to get support for entities, but you will need to set the `XML2_CONFIG` option when configuring your mapnik build to enable it.

**Comment by turban** [comment]
If I understand things correctly, Mapnik gets installed when I run "npm install mapnik@3.x" together with the node bindings. How can I set the XML2_CONFIG option when Mapnik is installed like this?

**Comment by springmeyer** [comment]
@turban you have two options:

1) Preprocess your stylesheets with `xmllint -noent` and then you can continue using node-mapnik with its pre-packaged binaries that do not support entities, but support  most other XML features
2) Build Mapnik core from source with libxml2 as a dependency. Build node-mapnik from source `npm install --build-from-source` against your mapnik core version.
