### ISSUE TITLE
API Documentation for map.render

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#648]
The `map.render` function is one of the most important, used, and flexible/complex of all node-mapnik APIs. It looks like this is not yet documented.

Note: noticed this trying to find out what the default was for `area_threshold` without going to the code.

**Comment by mapsam** [comment]
I can take a swing at this today @springmeyer - good catch!

**Comment by springmeyer** [comment]
Thanks @mapsam!

**Comment by clouddie** [comment]
Documenting this API would be really useful, I am at a loss figuring out why rendering the map to a vector tile does not work by calling this function...

**Comment by mapsam** [comment]
Hi @clouddie - sorry for the delay here. Working on this now.

**Comment by mapsam** [comment]
Added `map.render` docs in f81d0834da2d8eae026ec69f85efcdfccd1f971c

**Comment by mapsam** [comment]
http://mapnik.org/documentation/node-mapnik/3.5/#Map.render hope that helps @clouddie

**Comment by clouddie** [comment]
Thanks, fantastic @mapsam ! What I couldn't figure out was that the function needed a xml file, as when rendering a map into an image (thought that vector tiles weren't "styled" on the backend, because they're rendered client-side).
And you shouldn't apologize, I'm just a noob who can't read C++ code...

**Comment by mapsam** [comment]
@clouddie no problem. 

> thought that vector tiles weren't "styled" on the backend, because they're rendered client-side 

Worth noting that a vector tile **isn't** styled, and just holds geographic information and attribute data. When using the map.render function on a vector tile, it will grab the geo data and properties from the XML and generate a vector tile object whereas if you were to map.render an `Image` object it would handle the styling information from the XML.

**Comment by clouddie** [comment]
Hi, @mapsam, just to let you know, with the new docs I have actually managed to render a map to an image, and also to a vector tile slightly changing the example here : [node-mapnik-samples](https://github.com/mapnik/node-mapnik-sample-code/blob/master/render/app.js)

But I tried to do the same with a postgis datasource, it actually renders into an image, but I cannot render it to a vector tile...Are there any catches when defining Parameters in a xml file for a postgis data source to render to a vector tile ?

**Comment by springmeyer** [comment]
@clouddie I think you are misunderstanding something. `map.render` either renders to a vector tile or an image, depending on the object passed it. It does not matter what datasource parameters you are using.
