### ISSUE TITLE
Failing test against mapnik master

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#654]
Not sure yet what is causing this, but I think it is some change upstream in mapnik latest:

```
 1) mapnik.VectorTile.composite should support compositing tiles and clipping to max_extent (reencode):

      AssertionError: 54522 == 54463
      + expected - actual

      -54522
      +54463
      
      at Context.<anonymous> (test/vector-tile.composite.test.js:304:16)
```

Refs https://github.com/mapnik/mapnik/compare/v3.0.11...master

**Comment by tjwebb** [comment]
The same test fails for me on mapnik 3.0.9

**Comment by springmeyer** [comment]
fixed in https://github.com/mapnik/node-mapnik/commit/5de529fe4c051c6ab6ebf8437743fffe41b353e5
