### ISSUE TITLE
How to render map in image center?

### ISSUE THREAD

**Issue by diversoft** [mapnik/node-mapnik#661]
###  I want to render a entire map after using the function zoomAll, but i can't get a entire map, with some offset.

```js
var mapnik = require('mapnik');
var fs = require('fs'); 
// register fonts and datasource plugins
mapnik.register_default_fonts();
mapnik.register_default_input_plugins();
console.log( mapnik.fonts());
console.log(mapnik.imageType);

var map = new mapnik.Map(1080, 566);//How to set map size && image size?
map.load('H:/MapDataQuery/map_big.xml', function(err,map) {
    if (err) throw err;
    map.zoomAll();
    var img = new mapnik.Image(1080, 606,{type:0});
    map.render(img, function(err,im) {
      if (err) throw err;
	  im.save('image.png', 'png', function(err) {
		  if (err) throw err;
	  });

    });
});
```
![image](https://cloud.githubusercontent.com/assets/2303685/16363005/672ccae8-3bef-11e6-8d0f-b7031dea84b6.jpg)

**Comment by diversoft** [comment]
i got it.
before render map, must set map's extent, must confirm your entire map in the extent.

map.extent = [12859124.449251,3979153.352779,13556209.486337,4633546.241092];
map.bufferedExtent= map.extent;

**Comment by flippmoke** [comment]
@diversoft you might check out http://mapnik.org/node-mapnik/documentation/3.5/#Map

It appears that we are not currently documenting some of the `Map` objects methods however, such as `zoomAll`

/cc @mapsam
