### ISSUE TITLE
How to query raster layer's value by location?

### ISSUE THREAD

**Issue by diversoft** [mapnik/node-mapnik#663]
How to query raster layer's value by location?

**Comment by flippmoke** [comment]
@diversoft http://mapnik.org/node-mapnik/documentation/3.5/#Image.getPixel

**Comment by diversoft** [comment]
thank you flippmoke, 
i want to query function like gdallocaioninfo's function of gdal
gdallocationinfo -xml -wgs84 c.tif 115.450556 36.953333

**Comment by diversoft** [comment]
@flippmoke 
thank you flippmoke, 
i want to query function like gdallocaioninfo's function of gdal
gdallocationinfo -xml -wgs84 c.tif 115.450556 36.953333

**Comment by springmeyer** [comment]
@diversoft what you want is `map.queryPoint` or `map.queryMapPoint`. Looks like we are missing docs on this but you can see usage via the tests: https://github.com/mapnik/node-mapnik/blob/9fcdc3fb323dd1a5acca1ee5c6833e2ab8dc2eda/test/query-map.test.js
