### ISSUE TITLE
Install node-mapnik on closed network

### ISSUE THREAD

**Issue by gisuser1024** [mapnik/node-mapnik#665]
I've been struggling trying to install node-mapnik on a closed network.  We have a NPM clone repository setup with mapnik and all the dependencies, however, it keeps failing on node-pre-gyp trying to access outside dependencies.  

I was able to successfully install the software on my home computer with access to the internet. 

Does anyone have any thoughts suggestions on how I can bundle everything up all the necessary software on the outside and create a build script to install with a closed network? 

I am running node-js 4.4.1.   I thought about downloading and installing the header files.  Would this help?  

I'm not really a node JS guy so any help would be appreciated.  Thanks!

I have the latest version of mapnik installed on my server. (3.0.10).  And trying to install latest version of node-mapnik.

**Comment by springmeyer** [comment]
If you need to support multiple operating systems you can fetch all the binaries and then mirror them. Then you can ask node-pre-gyp to get them from your mirror: https://github.com/mapbox/node-pre-gyp#download-binary-files-from-a-mirror (https://github.com/mapbox/node-pre-gyp/pull/170).

Or, if you only need to support one operating system, just run `npm install` on your home computer and then copy `node_modules/mapnik` to your other computer. Just make sure to use the same node version. So use node v4 at home as well as at work.
