### ISSUE TITLE
3.5.13 not published for node v6

### ISSUE THREAD

**Issue by jakepruitt** [mapnik/node-mapnik#671]
Just tried installing the dependencies in https://github.com/mapbox/spritezero, which includes node-mapnik while on node v6, and got the following errors:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/jake/.nvm/versions/node/v6.3.1/bin/node" "/Users/jake/.nvm/versions/node/v6.3.1/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.5.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.5.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.
```

I did a local hotfix by publishing for node v6 from my local machine, but we should confirm v6 is in the publishing matrix. Looks like running `node-pre-gyp info` showed that abi 48 didn't have any published packages.

cc/ @mapsam @springmeyer

**Comment by brendanvinson** [comment]
`v3.5.14` is theoretically coming with node 6 support. However it's been in development for quite awhile now with no firm ETA.

https://github.com/mapnik/node-mapnik/issues/634

**Comment by springmeyer** [comment]
Will land once https://github.com/mapnik/node-mapnik/issues/634#issuecomment-239231520 is done.
