### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by scraigw** [mapnik/node-mapnik#680]
When running npm install:

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com
/mapnik/v3.5.13/Release/node-v14-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.13 and node@0.12.7
(node-v14 ABI) (falling back to source compile with node-gyp)

Then install fails - seems access restrictions have been placed on the amazon hosted binaries?

Thanks

**Comment by brianreavis** [comment]
Apart from there being no binaries, this is likely a problem with node-gyp / node-pre-gyp not node-mapnik. Similar https://github.com/galkahana/HummusJS/issues/93

**Comment by scraigw** [comment]
Thanks for the help on this. Updated nodejs to 4.5.0 and the npm install worked perfectly.
