### ISSUE TITLE
Fix broken docs publishing script

### ISSUE THREAD

**Issue by mapsam** [mapnik/node-mapnik#684]
Currently we get a [cryptic error](https://travis-ci.org/mapnik/node-mapnik/jobs/153006475#L1820) when publishing docs on travis:

```
{"error":"Travis encountered an error, sorry :("}
```

Only research shows that this could be related to a username change, which I don't think is the case: https://github.com/travis-ci/travis-ci/issues/1127

I'm at a loss of what to do here ... @springmeyer

**Comment by springmeyer** [comment]
@mapsam - is this still a problem? If so happy to take a closer look, just let me know.

**Comment by mapsam** [comment]
Ah, nope - that part of the script has been removed since we're building purely from the documentation repo.
