### ISSUE TITLE
Clipper regression

### ISSUE THREAD

**Issue by artemp** [mapnik/node-mapnik#686]
https://github.com/mapnik/node-mapnik/commit/6900101cc4f234683c1351eed5ba2621c7f98b6e#diff-cc0495d94732c1d611a829ac5faa2e75

@flippmoke - 6900101cc4f234683c1351eed5ba2621c7f98b6e commit causes regression in `tilelive-bridge` https://github.com/mapbox/tilelive-bridge/issues/84 

Would you care to explain what this "rare bug" is and how this change exactly fixes it, please?

**Comment by springmeyer** [comment]
My opinion is that we should revert this and release without 6900101cc4f234683c. The code previous to 6900101cc4f234683c has been in production for months without known issues, and 6900101cc4f234683c is risky without clear benefit. I will do this today.

**Comment by springmeyer** [comment]
Reverted in 3f4a2c9f93487c
