### ISSUE TITLE
input_plugins directory is not set correctly

### ISSUE THREAD

**Issue by tjwebb** [mapnik/node-mapnik#690]
The mapnik settings injected into mapnik_settings.js are not consistent with the values provided by mapnik-config.

```
~ $ mapnik-config --fonts
/usr/share/fonts/truetype
~ $ mapnik-config --input-plugins
/app/.apt/usr/lib/mapnik/input
```

Notice that `--input-plugins` returns `/app/.apt/usr/lib/mapnik/input`, which is correct. (this is on Heroku).

But on that same machine, after npm installs node-mapnik and generates the mapnik_settings.js file, `input_plugins` is different:
```
~ $ cat node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik_settings.js
module.exports.paths = {
    'fonts': '/usr/share/fonts/truetype',
    'input_plugins': '/usr/lib/mapnik/input'
};
```

Even though I am calling `mapnik.register_default_input_plugins()`, none are being loaded because this path is wrong, causing errors like this:

```
Error: Could not create datasource for type: 'gdal' (no datasource plugin directories have been successfully registered)
```

**Comment by tjwebb** [comment]
It looks like the error is related to this code: https://github.com/mapnik/node-mapnik/blob/master/gen_settings.py#L27-L31

I have no `MAPNIK_INPUT_PLUGINS` env var set, and my `mapnik-config` returns the values above, so I don't know where this incorrect path is coming from.

**Comment by springmeyer** [comment]
Odd. What I can say is that if you provide the `SYSTEM_FONTS` option to the Mapnik core configuration (`./configure SYSTEM_FONTS=/usr/share/fonts/truetype`) (or use a Mapnik package that was configured this way, which is common) then that path will be respected as absolute by `mapnik-config`. But `mapnik-config` by default tries to report/calculate most paths as relative to its own location. Open up your `mapnik-config` in a text editor to see this. You will see that the `CONFIG_PREFIX` is calculated dynamically: https://github.com/mapnik/mapnik/blob/3741a7f348f936668e2dd195f461ca60df8582fb/utils/mapnik-config/build.py#L53. And the `--input-plugins` is based on that https://github.com/mapnik/mapnik/blob/3741a7f348f936668e2dd195f461ca60df8582fb/utils/mapnik-config/build.py#L132-L134. This is advantageous for making portable Mapnik SDK builds of core that might end up anywhere and avoids hardcoded absolute paths that are wrong when the SDK is moved from one machine to another. I presume what is happening is that the `/usr/lib/mapnik/input` path is being calculated relative to a `mapnik-config` that lives at `/usr/bin/mapnik-config`. If you expect that `/app/.apt/usr/lib/mapnik/input` should be reported then you are expecting that a `mapnik-config` living at `/app/.apt/bin/mapnik-config` is being used. So, the only logical reason for the discrepancy you are seeing is that you have both `/app/.apt/bin/mapnik-config` and `/usr/bin/mapnik-config` (duplicate installs!) and the latter is being found when you build node-mapnik from source.

**Comment by tjwebb** [comment]
> then you are expecting that a mapnik-config living at /app/.apt/bin/mapnik-config is being used

That's right. That's exactly where `mapnik-config` is. There is no `/usr/bin/mapnik-config`, I have added `/app/.apt/bin` to my `PATH`.

If I manually set the `MAPNIK_INPUT_PLUGINS` to point to `/app/.apt/usr/lib/mapnik/input`, everything works perfectly.

**Comment by springmeyer** [comment]
> That's right. That's exactly where mapnik-config is. There is no /usr/bin/mapnik-config, I have added /app/.apt/bin to my PATH.

Okay, then the `/app/.apt/bin/mapnik-config` must not be using a relative path for reporting `--input-plugins`. Can you open up `/app/.apt/bin/mapnik-config` and paste the contents into a https://gist.github.com/ and share the link? Also can you share the `config.py` that is found in your Mapnik core build directory? I think some custom option must be being passed to the Mapnik configure that is customizing the input plugins directory in some unique way.

**Comment by springmeyer** [comment]
Also does `/app/.apt/` happen to be a symlink?

**Comment by tjwebb** [comment]
> Also does /app/.apt/ happen to be a symlink?

Nope. fwiw, I'm using this buildpack on heroku: https://github.com/heroku/heroku-buildpack-apt

> Can you open up /app/.apt/bin/mapnik-config

Like, with a text editor? Sure thing, I'll do that tomorrow.

**Comment by springmeyer** [comment]
> Like, with a text editor? 

Yes, `mapnik-config` is bash script.
