### ISSUE TITLE
Build failing for node v6.5.0 on windows

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#691]
Been trying to get node v6 working on windows. What I've done is:
- Kicked off a node-cpp11 build with visual studio 2015. This pulls directly from nodejs/node rather than the mapbox/node fork because after https://github.com/mapnik/node-mapnik/commit/e94407dd7282bf8979d87e1ecf3e33ada28052ea we no longer need to carry patches against node to compile with visual studio 2015: https://github.com/mapbox/node-cpp11/blob/master/.travis.yml#L43
- node-cpp11 build worked after fixing a few glitches related to node-cpp11 only
- Branch to try to build node-mapnik on node v6 on windows (just comments all other jobs) over at https://github.com/mapnik/node-mapnik/compare/v6-win
- Failing: https://ci.appveyor.com/project/Mapbox/node-mapnik/build/job/nrqy7mt5wax8cyao

Errors are new and curious:

```
mapnik-wkt.lib(mapnik_wkt_generator_grammar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(mapnik_geometry_to_geojson.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(mapnik_json_generator_grammar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(mapnik_json_feature_grammar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(generic_json.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(mapnik_json_geometry_grammar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(mapnik_json_positions_grammar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
libboost_thread-vc140-mt-1_61.lib(tss_pe.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
libboost_thread-vc140-mt-1_61.lib(thread.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
libboost_system-vc140-mt-1_61.lib(error_code.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in mapnik_logger.obj [C:\projects\node-mapnik\build\mapnik.vcxproj]
     Creating library C:\projects\node-mapnik\build\Release\mapnik.lib and object C:\projects\node-mapnik\build\Release\mapnik.exp
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-wkt.lib(mapnik_wkt_generator_grammar.obj) : error LNK2001: unresolved external symbol __imp__modf [C:\projects\node-mapnik\build\mapnik.vcxproj]
mapnik-json.lib(mapnik_json_generator_grammar.obj) : error LNK2001: unresolved external symbol __imp__modf [C:\projects\node-mapnik\build\mapnik.vcxproj]
MSVCRT.lib(_chandler4gs_.obj) : error LNK2001: unresolved external symbol __except_handler4_common [C:\projects\node-mapnik\build\mapnik.vcxproj]
libboost_thread-vc140-mt-1_61.lib(thread.obj) : error LNK2001: unresolved external symbol __imp___gmtime64 [C:\projects\node-mapnik\build\mapnik.vcxproj]
libboost_system-vc140-mt-1_61.lib(error_code.obj) : error LNK2001: unresolved external symbol __imp__strerror [C:\projects\node-mapnik\build\mapnik.vcxproj]
C:\projects\node-mapnik\build\Release\mapnik.node : fatal error LNK1120: 4 unresolved externals [C:\projects\node-mapnik\build\mapnik.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
```

**Comment by springmeyer** [comment]
Oh, this is likely because I'm using upstream node directly and not our fork. Since we've usually changed the runtime to shared in our patches.... like https://github.com/mapbox/node/pull/9/files. Now, for node v4/5 I think I did not change this, or it looks like I may have missed it. So I forgot about it for node v6. So, perhaps we do still need to fork and build with `'RuntimeLibrary': 0` -> `'RuntimeLibrary': 2`...

Looking through the node v6 build scripts it looks like there is `node_shared` variable that toggles this: https://github.com/nodejs/node/blob/dfe1c7e9b809740bbc511a55c668f80a5f5e4c22/common.gypi#L82-L96. Not sure if it does the right thing (might do more than we want) but tried it in: https://github.com/mapbox/node-cpp11/commit/ef06f922592a85dd5fe4f10c58d630961eefe66c


/cc @BergWerkGIS

**Comment by springmeyer** [comment]
hmm, after https://github.com/mapbox/node-cpp11/commit/ef06f922592a85dd5fe4f10c58d630961eefe66c and restarting the appveyor job I'm still seeing the same error... @BergWerkGIS help :)

**Comment by springmeyer** [comment]
made some progress today. Detailed at https://github.com/mapnik/mapnik/issues/3510#issuecomment-245111551. But now blocked on this error I'm unsure the cause of:

```
Error: The specified module could not be found.
[00:04:22] 
[00:04:22] \\?\C:\projects\node-mapnik\lib\binding\node-v48-win32-x64\mapnik.node
[00:04:22] 
```

**Comment by BergWerkGIS** [comment]
> But now blocked on this error I'm unsure the cause of

This [error check](https://github.com/mapnik/node-mapnik/blob/f22f10490130d901956f9f885938be9c3998c489/scripts/build-appveyor.bat#L132) has disabled thus masking that the build has failed and `mapnik.node` does not exist.

**Comment by BergWerkGIS** [comment]
WRT `/MT vs. /MD` for `node.exe/.lib`: This is how its done in `windows-builds`.

[Patching](https://github.com/mapbox/windows-builds/blob/master/patches/node-v6.5.0-MD.diff) the call to `msbuild in node's vsbuild.bat` to include this additional [msbuild config fragment](https://github.com/mapbox/windows-builds/blob/master/patches/node-force-MD.props) which forces `/MD` for the whole `node.sln`.

I suggest we carry the patch and the props file over to https://github.com/mapbox/node-cpp11/blob/master/windows/build_node.bat
What do you think?

**Comment by BergWerkGIS** [comment]
`node-mapnik` build is failing in the early stages already when `npm` is pulling down node headers and `node.lib` as the directory structure is not as expected and SHASUMS do not match:
https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1563#L9050

The directory structure for `node.exe/.lib` on nodejs.org has changed since `node@4`.
This probably would have to be accounted for in https://github.com/mapbox/node-cpp11/blob/7154967dd0b87abefaae3172999b3d38e40ee9a1/windows/build_node.bat#L44-L57

* https://nodejs.org/dist/v6.5.0/
  * `win-x64`
  * `win-x86`

* https://nodejs.org/dist/v0.12.15/
  * `x64`
  * binaries in root of version directory

**Comment by BergWerkGIS** [comment]
`node-mapnik` with `node@6.5.0` builds successfully (all tests pass) using `nodejs`'s node:
https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1565

**Comment by BergWerkGIS** [comment]
A hint that failing `node-mapnik` builds are linked to using Mapbox's node (directory structure SHASUMS).
https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1567

![image](https://cloud.githubusercontent.com/assets/4549888/18308127/c1dfe78c-74e2-11e6-9db3-a0c3b9ca8ad9.png)

**Comment by BergWerkGIS** [comment]
Mixing compiler/runtime versions is generally a bad thing and should be avoided **(*)**.
That's why we also build all dependencies from scratch.

To be investigated:
* why `node-mapnik` (`/MD`) compiles successfully against stock `node.lib` (`/MT`) without `mismatch detected for 'RuntimeLibrary'` error.
* why all `node-mapnik` tests pass when built against stock `node.lib` (`/MT`) as seen [above](https://github.com/mapnik/node-mapnik/issues/691#issuecomment-245243147).

Next steps:
* **shortcut:** create a "stress test" to check if something blows up using stock `/MT node`
* **long route:** Find out if/how CRT objects are passed across module boundaries
  * if yes, then this is a no-go and we have to keep building our own `/MD node`
  * if no, then we can move on with stock `/MT node`

----

**(*)**
except all code that uses CRT objects and is designed in a way that it does not pass these objects across module boundaries.

----

Additional reads about compiler versions and mixing `/MD` with `/MT`:

* [MSDN: The Great C Runtime (CRT) Refactoring](https://blogs.msdn.microsoft.com/vcblog/2014/06/10/the-great-c-runtime-crt-refactoring/)
* [Mixing C runtime library versions](https://greek0.net/blog/2016/01/01/mixing_crt_versions/)
* [Mixing Multiple Visual Studio Versions in a Program is Evil](http://siomsystems.com/mixing-visual-studio-versions/)
* [StackOverflow: Mixing /MD and /MT in single dll](http://stackoverflow.com/a/16891393)

**Comment by springmeyer** [comment]
next action here is to modify the node-cpp11 builds to use the right directory structure for libs and headers that new node-gyp expects. That is the core problem. That was manually fixed by @BergWerkGIS for node v4/5. We should return to this in 2017 and fix node-cpp11 to build the right structure for >= v4 and up automatically. @BergWerkGIS let's hit this in 2017.

**Comment by springmeyer** [comment]
Update: got a branch that confirms what we've seen above: moving back to stock node.exe works (as far as builds and tests) when the `--node-shared=true` flag is passed: https://github.com/mapnik/node-mapnik/pull/758

Next action is to followup on @BergWerkGIS's next steps above:

- **shortcut:** create a "stress test" to check if something blows up using stock `/MT node`
- **long route:** Find out if/how CRT objects are passed across module boundaries
  - if yes, then this is a no-go and we have to keep building our own `/MD node`
  - if no, then we can move on with stock `/MT node`

I vote for the shortcut first :) @BergWerkGIS let's sync up in the morning on this.

**Comment by BergWerkGIS** [comment]
hm, hitting a wall with `node@4.8.1` and `node-mapnik@3.6.0` locally:

<pre>
λ <b>npm install mapnik@3.6.0</b>
npm WARN package.json investigate-gpx@0.0.1 No license field.
-
> mapnik@3.6.0 install c:\mb\investigate-gpx\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.0/node-v46-win32-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.6.0 and node@4.8.1 (node-v46 ABI) (falling back to source compile with node-gyp)
</pre>

But binary package (https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.0/node-v46-win32-x64-Release.tar.gz) does exist.
???

**Comment by BergWerkGIS** [comment]
BTW, same with `gdal`:

<pre>
λ <b>npm install gdal</b>
npm WARN package.json investigate-gpx@0.0.1 No license field.
-
> gdal@0.9.4 preinstall c:\mb\investigate-gpx\node_modules\gdal
> npm install node-pre-gyp

npm WARN engineStrict Per-package engineStrict (found in this package's package.json)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
node-pre-gyp@0.6.34 node_modules\node-pre-gyp
├── semver@5.3.0
├── nopt@4.0.1 (abbrev@1.1.0, osenv@0.1.4)
├── rc@1.2.1 (ini@1.3.4, strip-json-comments@2.0.1, deep-extend@0.4.1, minimist@1.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar-pack@3.4.0 (uid-number@0.0.6, once@1.4.0, debug@2.6.3, fstream@1.0.11, readable-stream@2.2.9, fstream-ignore@1.0.5)
├── rimraf@2.6.1 (glob@7.1.1)
├── npmlog@4.0.2 (set-blocking@2.0.0, console-control-strings@1.1.0, gauge@2.7.3, are-we-there-yet@1.1.2)
├── tar@2.2.1 (inherits@2.0.3, block-stream@0.0.9, fstream@1.0.11)
└── request@2.81.0 (aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, tunnel-agent@0.6.0, is-typedarray@1.0.0, caseless@0.12.0, stringstream@0.0.5, safe-buffer@5.0.1, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, performance-now@0.2.0, uuid@3.0.1, qs@6.4.0, combined-stream@1.0.5, mime-types@2.1.15, tough-cookie@2.3.2, form-data@2.1.4, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)

> gdal@0.9.4 install c:\mb\investigate-gpx\node_modules\gdal
> node-pre-gyp install --fallback-to-build

<b>node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.4/node-v46-win32-x64.tar.gz</b>
node-pre-gyp ERR! Pre-built binaries not found for gdal@0.9.4 and node@4.8.1 (node-v46 ABI) (falling back to source compile with node-gyp)
</pre>

**Comment by springmeyer** [comment]
@BergWerkGIS can you try passing `--loglevel=http` - that should show more detail about what error is happening under the hood. Usually this means there was no response from the server and this path was hit: https://github.com/mapbox/node-pre-gyp/blob/master/lib/install.js#L106-L109

**Comment by BergWerkGIS** [comment]
Finally got [node-mapnik-bench](https://github.com/mapbox/node-mapnik-bench) running.

On my laptop:

```
node bin\bench testcases\geojson\us-counties-polygons.geojson v3.6.0 --minzoom=0 --maxzoom=12
```

results in

```json
{
  "source": "c:\\mb\\node-mapnik-bench\\testcases\\geojson\\us-counties-polygons.geojson",
  "version": "v3.6.0",
  "options": {
    "maxzoom": 12
  },
  "time": {
    "start": 1492707090468,
    "xml": 1492707091320,
    "bridge": 1492707091398,
    "info": 1492707091398,
    "load": 1492707091399,
    "copy": 1492707189108
  },
  "sink": "noop://",
  "memory": {
    "max_rss": "93.54MB",
    "max_heap": "39.49MB",
    "max_heap_total": "57.25MB"
  },
  "tile_count": 312008
}
```

Memory usage gradually increased to ~70MB for `node.exe`, then stayed between ~65MB and ~70MB for the whole time.
Chart looks like a straight line:
![image](https://cloud.githubusercontent.com/assets/4549888/25241933/0e801f50-25f8-11e7-91de-1e50b8d11ae2.png)

**Comment by springmeyer** [comment]
Awesome results @BergWerkGIS! What exact version of node.exe was this with?

**Comment by BergWerkGIS** [comment]
`node@4.8.1` downloaded from nodejs.org

**Comment by springmeyer** [comment]
Awesome and surprising @BergWerkGIS. I presume that node.exe links totally different CRT libs (and library names) since it is built with vs 2013. Do you get the same positive result with node v6?

As far as next steps, I'm thinking your results from node-mapnik-bench are all we need to move forward with this plan besides a gut check on what exactly the `--node-shared=true` does and confirming it feels safe.

**Comment by BergWerkGIS** [comment]
Finally made [node-mapnik-bench](https://github.com/mapbox/node-mapnik-bench) work with **`node@6.10.1`** on Windows.

----

/cc @mapsam probably a blue sky task? 
Make `node-mapnik-bench` a bit less user friendly but with as few dependencies as possible? 
eg provide a pregenerated XML for the test data so that a call to `mapnik-omnivore` is not necessary.

Some of the things I had to do to get going (from the top of my head, unfortunately I didn't take notes):
* manually copy around binary dependencies, eg copy (and sometimes overwrite) mapnik binaries to several places
  * some modules expected them at `lib/binding`
  * others at `lib/binding/node-v48-win32-x64`
  * some modules are referencing `mapnik@3.5.14`
* duplicate `tilelive-bridge`
  * some modules expect it under the `@mapbox` namspace, some don't
* reference the github repos directly as latest versions don't seem to be published to npm yet
tilelive-bridge: no node@6 binaries for referenced mapnik version
tilelive-omnivore: no node@6 binaries for referenced gdal version

Maybe some of the above problems also stem from `npm@3.10.10` flattening the dependencies?

----

Anyway

```
node bin\bench testcases\geojson\us-counties-polygons.geojson v3.6.0 --minzoom=0 --maxzoom=12
```

yielded:

```json
{
  "source": "C:\\b\\testcases\\geojson\\us-counties-polygons.geojson",
  "version": "v3.6.0",
  "options": {
    "maxzoom": 12
  },
  "time": {
    "start": 1493024100177,
    "xml": 1493024100958,
    "bridge": 1493024101015,
    "info": 1493024101016,
    "load": 1493024101016,
    "copy": 1493024152762
  },
  "sink": "noop://",
  "memory": {
    "max_rss": "76.71MB",
    "max_heap": "23.94MB",
    "max_heap_total": "44.04MB"
  },
  "tile_count": 312007
}
```

I didn't notice any weird memory usage related behavior in `Task Manager` during execution of the above command.

**Comment by springmeyer** [comment]
> As far as next steps, I'm thinking your results from node-mapnik-bench are all we need to move forward with this plan besides a gut check on what exactly the --node-shared=true does and confirming it feels safe.

I dug and found this can be reviewed by following https://github.com/nodejs/node/pull/9385#issuecomment-261631675 to https://github.com/nodejs/node/compare/527db40932d479a2e8b7537edac58e8372c9544c...e97723b18c2b0b61245e1a9a7726bacbf0e8957a, which is a backport of https://github.com/nodejs/node/pull/7487 (and a few other followups that landed in master)

My understanding is:

 - The `--node-shared=true` is primarily about building node as a dll correctly by using /MD to link node itself to its deps.
 - We don't care about using node itself as a dll, we only care about linking node-mapnik to libmapnik.dll in a way that allows node-mapnik to work with any node.exe binary (dll/MD or not/MT)
 - In our case - passing  `--node-shared=true` from an addon build when using the stock node.exe we are basically saying:
   - We know that node itself is not built with this flag, but we pass it anyway
   - When passing it we functionally disable the default /MT linking that is inherited from node's gyp and would otherwise impact our addon build
   - So, our addon can be built /MD even though node itself is not

While unconventional, this appears to work great and proves that, at least in the case of node addons like node-mapnik, the boundary crossing issues described at https://www.softwariness.com/articles/visual-cpp-runtime-libraries/ do not apply (nothing like std::string is allocated in node and deallocated by node-mapnik).

**Comment by springmeyer** [comment]
To recap:

 - This ticket started with experiences to built against node v6 long ago
 - The underlying problem is that for node v0.10, v0.12, and v4 we've used customized builds of node (built with /MD) via https://github.com/mapbox/node-cpp11
 - In the process of further testing we've found that we can use the stock node.exe (built with /MT) and we can avoid patching by using the `--node-shared=true` flag with node >= v4.

Working on getting this working at https://github.com/mapnik/node-mapnik/pull/758
