### ISSUE TITLE
Is mapnik.imageType.rgb8 valid image type? How to get png8 palette output?

### ISSUE THREAD

**Issue by gagan-bansal** [mapnik/node-mapnik#703]
I am trying to create `mapnik.Image` as documented [here][1] with `rgb8` option. But is seems its not a valid image type.  Not defined [here][3].

I want to get png8 output, trying to modify the [kosmtik code] [2] 

```javascript
// current
var im = new mapnik.Image(this.height, this.width);
//modified
var im = new mapnik.Image(this.height, this.width, 
  {imageType: 'rgb8'}
);
```
As `rgb8` is not a valid mapnik Image type it throws error.

Whats the proper way to get png8 (Palette) output in node-mapnik?

[1]: https://github.com/mapnik/node-mapnik/blob/c8dee11e7e8f29168cf4e96c46b13d4933246327/src/mapnik_image.cpp#L58
[2]: https://github.com/kosmtik/kosmtik/blob/master/src/back/Tile.js#L33
[3]: https://github.com/mapnik/node-mapnik/blob/c8dee11e7e8f29168cf4e96c46b13d4933246327/src/node_mapnik.cpp#L319

**Comment by talaj** [comment]
You confused in memory representation of an image, which is one of [these](https://github.com/mapnik/node-mapnik/blob/c8dee11e7e8f29168cf4e96c46b13d4933246327/src/node_mapnik.cpp#L320-L331), and output image format, which might be `png8`.

Try something like this:

```js
var im = new mapnik.Image(this.height, this.width);

im.encode('png8', function(err,buffer) {
  if (err) throw err;
  fs.writeFile('map.png',buffer, function(err) {
      if (err) throw err;
      console.log('saved map image to map.png');
  });
});
```

**Comment by gagan-bansal** [comment]
@talaj I got your point. 
Thanks for the solution.

**Comment by gagan-bansal** [comment]
@talaj modified the code as per your suggestion and its working as expected. 
Thanks

**Comment by talaj** [comment]
@gagan-bansal You are welcome. There are many other png output options like `png8:c=128:t=1:m=h`. These options are handled in Mapnik core: [mapnik/src/image_util_png.cpp](https://github.com/mapnik/mapnik/blob/834028db7a6f1070a545d4c20bd7c319754fcc20/src/image_util_png.cpp#L52)

**Comment by gagan-bansal** [comment]
@talaj I'll go through these options.
