### ISSUE TITLE
node-mapnik usage with GDAL

### ISSUE THREAD

**Issue by Arsakes** [mapnik/node-mapnik#704]
How can use this library for rendering BigTIFF image and GDAL plugin?
That is how to define Datasource that explicitely uses GDAL?

I've done it using XML map definition - can I do it using API?

**Comment by talaj** [comment]
It should be possible, take a look at this test:

https://github.com/mapnik/node-mapnik/blob/4d09f0c3b7aef109af3bdae5f93c3437d0105f87/test/datasource.test.js#L238-L243

```js
var options = {
    type: 'gdal',
    file: './test/data/images/sat_image.tif'
};

var ds = new mapnik.Datasource(options);
```

**Comment by Arsakes** [comment]
Yea I was guessing i need to pass something to Datasource - so parametrs are the same as in xml version.
thx
