### ISSUE TITLE
about the style

### ISSUE THREAD

**Issue by mysisi** [mapnik/node-mapnik#712]
Importing xml is the only way to set style for a map. Why not do it like python for mapnik?
It's questioned two years ago, but i don't see any api about symbolizer object

**Comment by springmeyer** [comment]
Several reasons:

  - Exposing an API for each symbolizer and property is a lot of work and hard to maintain. Our experience from python shows this and supporting another language would be 2x as hard
  - It is harder to deprecate and create compatibility
  - Loading all styles at once is faster than via an API
  - Those usecases where you want to change one or two properties dynamically are better served through data-driven usage of expressions http://mapnik.org/news/future_mapnik2
