### ISSUE TITLE
Using OGR extension in node-mapnik with Oracle Spatial

### ISSUE THREAD

**Issue by ardilgulez** [mapnik/node-mapnik#715]
Hey all,

I'm trying to serve tiles from oracle spatial database using tilelive, but I can't connect to my data source using mapnik. My mapnik xml is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map[]>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"
     maximum-extent="-20037508.34,-20037508.34,20037508.34,20037508.34">
  <Parameters>
    <Parameter name="format">png</Parameter>
  </Parameters>
  <Style name="input" filter-mode="first" >
    <Rule>
      <PolygonSymbolizer fill="rgba(192, 168, 150, 1)" />
      <LineSymbolizer stroke="rgba(0, 0, 0, 1)" />
    </Rule>
  </Style>
  <Layer name="input" status="on" srs="+proj=latlong +datum=WGS84">
    <StyleName>input</StyleName>
    <Datasource>
      <Parameter name="type">ogr</Parameter>
      <Parameter name="string">OCI:username/password@database_ip/database_name</Parameter>
      <Parameter name="layer_by_sql">SELECT * FROM MY_TABLE</Parameter>
      <Parameter name="extent">-20037508.34,-20037508.34,20037508.34,20037508.34</Parameter>
    </Datasource>
</Layer>
</Map>
```

My tilelive code is pretty simple too:

``` javascript
var tilelive = require('tilelive');
require('tilelive-mapnik').registerProtocols(tilelive);
var express = require('express');
var app = express();

tilelive.load('mapnik:///home/ardil/Desktop/projeler/tilelive/mapnikxml.xml', function(err, source) {
    if (err) throw err;

    app.get('/:z/:x/:y', function(req, res, next){
      var z = req.params.z,
            x = req.params.x,
            y = req.params.y;

      source.getTile(z, x, y, function(error, tile, headers){
        if(error){
          console.log(error);
          res.status(503).send('An Error Occured!');
          return;
        }
        res.set(returnObject.headers);
        res.status(200).send(returnObject.tile);
      });
    });

    app.listen(3000, function(){
      console.log("Listening on port 3000");
    });
});
```

When I run the above node.js code, I get this:

Error: OGR Plugin: connection failed: OCI:username/password@database_ip/database_name was not found or is not a supported format  encountered during parsing of layer 'input' in Layer

However, when I use:

ogrinfo -ro OCI:username/password@database_ip/database_name -sql "SELECT * FROM MY_TABLE" from command line, I get perfect result.

Can you please tell me what I'm doing wrong and how to do this correctly?

Thanks in advance.

**Comment by flippmoke** [comment]
I am not sure what plugins are built into the default GDAL library built for node-mapnik but it may not include the OCI driver. In order for this to work, you might need to:

* Build GDAL locally with OCI
* Build Mapnik linking that GDAL
* Build Node-Mapnik linking to that Mapnik

**Comment by pnorman** [comment]
> I am not sure what plugins are built into the default GDAL library built for node-mapnik but it may not include the OCI driver. In order for this to work, you might need to:

Yes - you will **need** to build node-mapnik, not use the binary blob.

**Comment by ardilgulez** [comment]
> Build Mapnik linking that GDAL
> Build Node-Mapnik linking to that Mapnik

How do I do these? If I just build GDAL locally with OCI and build mapnik after that, does mapnik build on that GDAL?

And after building mapnik, do I just confirm that the correct mapnik-config is in PATH and build node-mapnik right after that?

**Comment by flippmoke** [comment]
https://github.com/mapnik/mapnik/blob/master/INSTALL.md

https://github.com/mapnik/node-mapnik#source-build

Typically the latest mapnik will work properly with the latest node-mapnik.

**Comment by ardilgulez** [comment]
Thanks for the answer @flippmoke,

I'm trying to build without getting mason packages (which include a gdal that is not built with OCI support) and I'm getting:

Checking for dlfcn.h support ... yes
Checking if compiler (clang++) supports -std=c++14 flag... (cached) yes
Checking for C library freetype... no
Could not find required header or shared library for freetype
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for ICU version >= 4.2... found: icu 55.1
(cached) Checking for C++ library harfbuzz... yes
Checking for HarfBuzz version >= 0.9.34... found: HarfBuzz 1.3.4
Checking for HarfBuzz with freetype support
(cached) no
Searching for boost libs and headers... (cached) 
Found boost libs: /usr/lib
Found boost headers: /usr/include
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.61... yes
Found boost lib version... 1_62
Checking for C++ library boost_system... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_program_options... yes
Checking whether Boost was compiled with C++11 scoped enums ... yes
Checking if boost_regex was built with ICU unicode support... (cached) yes
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... yes
Checking for C library webp... yes
Checking for C library tiff... yes
Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of gdal library... gdal
Checking for C++ library gdal... yes
Checking if gdal is ogr enabled... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of ogr library... gdal
Checking for C++ library gdal... yes
Checking for C library pq... no
Checking for C library pq... no
Checking for C library sqlite3... yes
Checking for sqlite3... yes
Checking if SQLite supports RTREE... (cached) yes
Checking for pg_config... yes
Checking for cairo freetype font support ... no

Despite the fact that I have installed libfreetype6-dev and libpq-dev, I'm not getting freetype or pq support. I have no idea what is wrong. How can I fix that?

Thanks in advance.

**Comment by flippmoke** [comment]
It would be hard to know with out just fighting with it myself, linking libraries and setting up environment properly is something everyone struggles with at some time. 

```
configure --help
```

**Comment by pnorman** [comment]
> Typically the latest mapnik will work properly with the latest node-mapnik.

To be more precise, if a version of node-mapnik works with Mapnik 3.0.x, it will work with any more recent 3.0 version of Mapnik. Mapnik doesn't follow semver, but a patch release can't make a backwards-incompatible change, and if it does, that's a bug that should be raised against Mapnik.

node-mapnik versions changing is [more complex](http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api), but if it's adding new code it's a minor version increment

**Comment by springmeyer** [comment]
> I am not sure what plugins are built into the default GDAL library built for node-mapnik but it may not include the OCI driver.

Correct, the binaries shipped for node-mapnik by default include a GDAL with most drivers disabled. We will never support proprietary drivers like oracle in the default binaries. This is disabled via this patch: https://github.com/mapnik/mapnik-packaging/blob/master/osx/patches/gdal-2.1.1-minimal.diff#L45

> Typically the latest mapnik will work properly with the latest node-mapnik.

It is not recommended to use latest with latest. Instead I recommend choosing your target node-mapnik release and then seeing which Mapnik version was targeted for that release via the changelog: https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#3514. That way you can combine versions in a way that were proven to work via the testing that happens during the binary build process.

> Despite the fact that I have installed libfreetype6-dev and libpq-dev, I'm not getting freetype or pq support. I have no idea what is wrong. How can I fix that?

@ardilgulez that is a Mapnik core build issue. Please file questions about mapnik core at https://github.com/mapnik/mapnik/issues.

Overall oracle support is unrelated to node-mapnik so I'm going to close this issue.
