### ISSUE TITLE
GDAL WMS sources not recognized

### ISSUE THREAD

**Issue by bjornharrtell** [mapnik/node-mapnik#716]
I've been trying to get node-mapnik to work with a GDAL WMS source but having no success. I'm getting `not recognized as a supported file format` (apparently coming from GDAL) when trying to point to a GDAL service description XML. I've also tried accessing via VRT but results in the same error.

I'm running on linux and get the `node-v48-linux-x64` bindings. Perhaps my problems might be caused by the prebuilt GDAL missing support for libcurl as required by WMS?

I've tried to investigate the bindings myself and rebuilding locally, but as of yet I don't understand it well enough.

**Comment by bjornharrtell** [comment]
Sucessfully built node-mapnik (d2a7271f45217257b9656378fd24fc348821081c) using the following:
```sh
git clone https://github.com/mapnik/node-mapnik.git
npm install --build-from-source
```

Running with that built version works fine with regard to this issue.

**Comment by artemp** [comment]
@bjornharrtell - great, closing.

**Comment by tjwebb** [comment]
I am also having this issue, but installing from source did not solve it. It only happens with GDAL sources
