### ISSUE TITLE
build fails for ubuntu / node 7

### ISSUE THREAD

**Issue by killturinG** [mapnik/node-mapnik#717]
`cat /etc/issue`
Ubuntu 14.04.4 LTS

`npm -v`
4.1.1

`node -v`
v7.3.0

I use `git clone https://github.com/mapnik/node-mapnik.git`

`npm install --build-from-source --debug`

> In file included from ../node_modules/nan/nan.h:196:0,
>                  from ../src/utils.hpp:7,
>                  from ../src/mapnik_logger.cpp:1:
> ../node_modules/nan/nan_new.h: In function ‘v8::Loca`l<T> Nan::imp::To(v8::Local<v8::Integer>)` [with T = v8::Int32]’:
> ../node_modules/nan/nan_new.h:29:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> make: *** [Debug/obj.target/mapnik/src/mapnik_logger.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 3.13.0-93-generic
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/wlx/app/node-mapnik/lib/binding/node-v51-linux-x64/mapnik.node" "--module_name=mapnik" "--module_path=/home/wlx/app/node-mapnik/lib/binding/node-v51-linux-x64"
> gyp ERR! cwd /home/wlx/app/node-mapnik
> gyp ERR! node -v v7.3.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/wlx/app/node-mapnik/lib/binding/node-v51-linux-x64/mapnik.node --module_name=mapnik --module_path=/home/wlx/app/node-mapnik/lib/binding/node-v51-linux-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/wlx/app/node-mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> node-pre-gyp ERR! System Linux 3.13.0-93-generic
> node-pre-gyp ERR! command "/usr/local/bin/node" "/home/wlx/app/node-mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /home/wlx/app/node-mapnik
> node-pre-gyp ERR! node -v v7.3.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.32
> node-pre-gyp ERR! not ok 
> 
> npm ERR! Linux 3.13.0-93-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--build-from-source" "--debug"
> npm ERR! node v7.3.0
> npm ERR! npm  v4.1.1
> npm ERR! code ELIFECYCLE
> npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mapnik@3.5.14 install script 'node-pre-gyp install --fallback-to-build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mapnik package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mapnik
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mapnik
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/wlx/app/node-mapnik/npm-debug.log
> 

Is my npm problem？ or gcc problem ?  
thanks :)

**Comment by killturinG** [comment]
`gcc -v`

> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1)

**Comment by springmeyer** [comment]
Please stick with node v4 or v6 for now. The problem you are facing is that we don't provide precompiled binaries for node v7. So the build is falling back to a source compile. Which needs `mapnik` externally compiled and a c++11 capable compiler. I recommend at least gcc 5 or clang++ 3.8.

**Comment by springmeyer** [comment]
The node-mapnik v3.6.0 release now provides binaries for node v7.
