### ISSUE TITLE
Parametric queries in node mapnik

### ISSUE THREAD

**Issue by furstenheim** [mapnik/node-mapnik#718]
Related questions:
#495 and https://github.com/mapnik/mapnik-support/issues/85
What is the status now of prepared statements? This would give more security against [sql injection](http://security.stackexchange.com/questions/15214/are-prepared-statements-100-safe-against-sql-injection) and speed as the query planning would not be repeated each time.

This is blocking our adoption of node-mapnik

**Comment by flippmoke** [comment]
This would be a better question to ask in the mapnik repository rather then here on node-mapnik. Closing because this isn't a node-mapnik issue but an issue in mapnik.
