### ISSUE TITLE
the size of mapnik (v3.5.13 node-v48-darwin-x64.tar.gz) only gets 900KB

### ISSUE THREAD

**Issue by jingsam** [mapnik/node-mapnik#721]
Hi, recently I made a mirror for node-pre-gyp in China. I found that the size of mapnik 3.5.13 on macOS/node 6 is too small (only 900KB), which I expect to be 17MB. Here the link:
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.13/Release/node-v48-darwin-x64.tar.gz

**Comment by flippmoke** [comment]
Does that binary included in the tar-ball actually not work after decompressed?

**Comment by flippmoke** [comment]
Closing because of no response
