### ISSUE TITLE
Pre-built binaries not found

### ISSUE THREAD

**Issue by andrelom** [mapnik/node-mapnik#724]
Hi

I tried installing Mapnik v3.5.14, but I get the above error:

`node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/n ode-v51-darwin-x64.tar.gz`
`node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.4.0 (node-v51 ABI) (falling back t o source compile with node-gyp)`

Maybe the precompiled binaries are not available for this release, or are there any problems with the repository?

UPDATE: The node is v7.4.0, and I tried to install on MacOS and Windows.

**Comment by andrelom** [comment]
I believe it is something related to the host that is used with "node-pre-gyp", because when I try to access the address of the binary it returns the "Access Denied" mesage.

`
<Error> <Code>AccessDenied</Code> <Message>Access Denied</Message> <RequestId>D13A90644875B937</RequestId> <HostId> kJdjXqJeoYrVJnyMJe/kLTC36iUZtNGCME/LilQ9R1DvX0+kx85nwIe0vSHtldKFha2xjfYDQaE= </HostId> </Error>
`

**Comment by flippmoke** [comment]
The problem is that we are not currently building any pre-built binaries for `node@7.4.0` -- try `node@6.9.4` as that is our current latest version of node we are supporting.

**Comment by andrelom** [comment]
That's it, thanks for the help.
