### ISSUE TITLE
trying to install mapnik in windows

### ISSUE THREAD

**Issue by mapsgeek** [mapnik/node-mapnik#727]
i'm so confused about this process and documentation not that great, i installed mapnik 2.2.0 binary and added the path to environment path and i can use mapnik through the cmd

then i try to install mapnik via npm as a depedancy for a project i get this error:

C:\Users\ibrahim>npm install -g mapnik

> mapnik@3.5.14 preinstall C:\Users\ibrahim\AppData\Roaming\npm\node_modules\.st
aging\mapnik-4095ae5e
> npm install node-pre-gyp

C:\Users\ibrahim\AppData\Roaming\npm
`-- node-pre-gyp@0.6.33

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ibrahim\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\ibrahim\AppData\Roaming\npm\node_modules\.staging\mapnik-
4095ae5e
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\ibrahim\AppData\Roaming
\npm\node_modules\.staging\mapnik-4095ae5e'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ibrahim\AppData\Roaming\npm\node_modules\.staging\mapnik-4
095ae5e\npm-debug.log
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ibrahim\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mapnik"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.5.14 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 4294963214
npm ERR!
npm ERR! Failed at the mapnik@3.5.14 preinstall script 'npm install node-pre-gyp
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ibrahim\npm-debug.log

C:\Users\ibrahim>

**Comment by hevilp** [comment]
I got the same error with node 6.9.5

**Comment by flippmoke** [comment]
Node Mapnik currently does not support Mapnik 2.x - You will need to use Mapnik 3.0.x series.

**Comment by flippmoke** [comment]
Re-opening because I realized there is more to this -- node-mapnik installed using npm install will attempt to bring its own prebuilt binary of mapnik. 

I have no idea the current versions that node-pre-gyp supports but this is an issue with node-pre-gyp not with mapnik from what I can see. It appears that node-pre-gyp is not being installed.

**Comment by flippmoke** [comment]
Also please see https://github.com/mapnik/node-mapnik/issues/728#issuecomment-281399620
