### ISSUE TITLE
error: ‘apply_visitor’ is not a member of ‘mapnik::util’

### ISSUE THREAD

**Issue by strk** [mapnik/node-mapnik#731]
The error in summary is thrown when trying to build node-mapnik (running `make` after cloning the repo) with `node-4.2.6`. I've found the problem reported in issue #473 but the issue is closed for unknown reasons.

**Comment by flippmoke** [comment]
@strk what version of mapnik are you using?

**Comment by strk** [comment]
Mapnik is 2.3.0-pre
node-mapnik is master

**Comment by flippmoke** [comment]
@strk you will need a 3.x series mapnik for node-mapnik at this point. I would highly suggest `v3.0.12` with the current master.
