### ISSUE TITLE
fatal error: 'mapnik/value_types.hpp' file not found

### ISSUE THREAD

**Issue by kimmobrunfeldt** [mapnik/node-mapnik#733]
I'm not able to compile node-mapnik on Ubuntu 16.04.1. I got it compiled on my OS X 10.10.5, with the same version of mapnik

`mapnik-config -v` outputs `3.0.12`. I checked out latest master of node-mapnik. When running `npm install --build-from-source` I get an error:

```
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
g++: error: unrecognized command line option ‘-Wc++14-extensions’
mapnik.target.mk:204: recipe for target 'Release/obj.target/mapnik/src/mapnik_logger.o' failed
```

I figured out maybe I should use clang and tried to run `CXX="clang" npm install --build-from-source` but got a new error:

```
In file included from ../src/mapnik_logger.cpp:1:
../src/utils.hpp:16:10: fatal error: 'mapnik/value_types.hpp' file not found
#include <mapnik/value_types.hpp>
         ^
1 error generated.
mapnik.target.mk:204: recipe for target 'Release/obj.target/mapnik/src/mapnik_logger.o' failed
```

Do you know why this is happening? When checking mapnik sources, it doesn't have value_types.hpp file anymore. They have moved it under value/types.hpp or similar. 

*I know there are pre-built binaries for Linux but I'm debugging a problem where the same code in Ubuntu outputs just a gray image where in OS X I get a correct map image*

**Comment by flippmoke** [comment]
Build against the mapnik core `3.0.x` branch or the lastest tag in the `3.0` series. We haven't yet migrated the code here to support the new `3.1.x` series mapnik that is currently in mapnik core.
