### ISSUE TITLE
centos7 build node-mapnik failed

### ISSUE THREAD

**Issue by WeiGuoyingGitHub** [mapnik/node-mapnik#735]
help,I meet with difficulties at the time of building.

# **node version**
[root@localhost lib]# node -v
v0.10.40

I've tried  node v4.4.5 and v0.10.29,but all failed.
# **build**
[root@localhost node-mapnik]# npm install --unsafe-perm
/
> mapnik@3.5.14 preinstall /usr/local/src/node-mapnik/node_modules/mapnik
> npm install node-pre-gyp

npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
node-pre-gyp@0.6.33 node_modules/node-pre-gyp
├── semver@5.3.0
├── nopt@3.0.6 (abbrev@1.1.0)
├── rc@1.1.7 (strip-json-comments@2.0.1, ini@1.3.4, deep-extend@0.4.1, minimist@1.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar@2.2.1 (inherits@2.0.3, block-stream@0.0.9, fstream@1.0.10)
├── rimraf@2.5.4 (glob@7.1.1)
├── tar-pack@3.3.0 (uid-number@0.0.6, once@1.3.3, debug@2.2.0, fstream@1.0.10, readable-stream@2.1.5, fstream-ignore@1.0.5)
├── npmlog@4.0.2 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-there-yet@1.1.2, gauge@2.7.3)
└── request@2.79.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.4.3, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, aws4@1.6.0, uuid@3.0.1, qs@6.3.1, form-data@2.1.2, mime-types@2.1.14, combined-stream@1.0.5, hawk@3.1.3, tough-cookie@2.3.2, http-signature@1.1.1, har-validator@2.0.6)
|
> mapnik@3.5.14 install /usr/local/src/node-mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v11-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@0.10.40 (node-v11 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v11-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@0.10.40 (node-v11 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Linux 3.10.0-327.el7.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64"
gyp ERR! cwd /usr/local/src/node-mapnik/node_modules/mapnik
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node/bin/node /usr/local/node/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node --module_name=mapnik --module_path=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/src/node-mapnik/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.10.0-327.el7.x86_64
node-pre-gyp ERR! command "node" "/usr/local/src/node-mapnik/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/src/node-mapnik/node_modules/mapnik
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/node/bin/node /usr/local/node/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node --module_name=mapnik --module_path=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64' (1)

npm ERR! mapnik@3.5.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.5.14 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-327.el7.x86_64
npm ERR! command "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /usr/local/src/node-mapnik
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
[root@localhost node-mapnik]# gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Linux 3.10.0-327.el7.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/src/node-mapnik/node_modules/mapnik/lib/binding/node-v11-linux-x64"
gyp ERR! cwd /usr/local/src/node-mapnik/node_modules/mapnik
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

**Comment by springmeyer** [comment]
> node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v11-linux-x64.tar.gz

This binary exists. So the failure must have been due to some network problem on your end.
