### ISSUE TITLE
EPSG3857 tile with text symbolizer

### ISSUE THREAD

**Issue by ovord** [mapnik/node-mapnik#741]
Hello guys,

I´m trying to place some textsymbolizers on map tiles and want to place the tiles later on an epsg3857 tilemap. My Problem is in the current output projection all tiles are scaled the same in lat/lon, therefore labels get "squeezed" the further up to the north the map goes. I tried to change the map-projection (see xml), but as soon as i change the "srs" tag, the text symbolizers disappear. Appreciate your help!

Oliver

 

[scripts.zip](https://github.com/mapnik/node-mapnik/files/850709/scripts.zip)

**Comment by brendanvinson** [comment]
I can't seem to open your zip as it keeps looping zip -> cpgz -> zip and so on. The way we implemented it (as we're having to do a re-transform as well) is to remove the datasource completely from the xml, set it directly on the object, and then create a new map instance with the init flag. It looks something like this:

```js
function createTile(datasource) {
    const layer = new mapnik.Layer('contour');
    layer.datasource = new mapnik.Datasource(datasource);
    layer.styles = [datasource.style];
    const tileSize = parseInt(datasource.parameters.size, 10) || 256;
    const map = new mapnik.Map(tileSize, tileSize, '+init=epsg:3857');
    map.bufferSize = tileSize / 2;
    map.load(datasource.stylesheet, { strict: true }, (err, loadedMap) => {
      if (err) throw err;
      loadedMap.add_layer(layer);
    });
  }
```
where `datasource` is a json with the datasource options and `datasource.style` is a link to the xml

**Comment by brendanvinson** [comment]
The other option that you have is to reproject in your query using `ST_Transform()`.
