### ISSUE TITLE
Hiding layers and rerending

### ISSUE THREAD

**Issue by rheh** [mapnik/node-mapnik#742]
Hi All,

I have a need to render an image with several layers (about 20 in all),  then I need to render the same image with three of the 20 layers switched off.  My first attempt at this was to loop around my entire code base passing a Boolean value to instruct the logic to skip the unwanted layers on the second pass.  This works but seems inefficient.

Unfortunately I now need to produce two other images with other layers switched off.  I have spotted the active flag on the Layer object.  Thus, in theory I could simply prepare all the layers, add them to the map and then ask mapnik to render the four images - switching the active flag on the layers as necessary.  The problem being setting the active seems to have no affect.   I've currently doing the layer active setting here:

```
LayerHelper.prototype.getLayer = function(layers, name) {
  if (_.isArray(layers) === false ||
    layers.length === 0) {
    return null;
  }

  if (_.isString(name) === false ||
    layers.length === 0) {
    return null;
  }

  var layer = _.find(layers, {
    name: name
  });

  return layer;
};

LayerHelper.prototype.setActive = function(layers, name, active) {
  var layer = this.getLayer(layers, name);

  if (!layer) {
    return false;
  }

  layer.active = active;

  return true;
};

_.forEach(imagesToRender, function(imageTorender) {

var layersToDisable = imagesToRende.layersToDisable;
for(i = 0; i < layersToDisable .length; i++) {
  var layerToDisable = layersToDisable [i];
  LayerHelper.setActive(map.getLayers(), layerToDisable, false); 
}

map.render(im, {}, function(renderError, im) {
      if (renderError) {
        -- do stuff
        return;
      }
     -- save image .....
}
```

Does this logic look sound?  And, is the active flag called in the correct way?

**Comment by talaj** [comment]
The logic seems OK to me. It should work. Does the `LayerHelper.setActive()` really return `true`?

**Comment by rheh** [comment]
LayerHelper is a module I've create which wraps the functionality, so in this case it returns true.  I guess what I'm asking is "layer.active" propery available in the Node version and when and how should I change it. 

What I have worked out this morning is if I set the active flag prior to "map.add_layer(layer);" then it will be inactive.  What I want to do is set the layer, render one image, switch the layer off by setting the active flag to false and render another image.  If the second set that seem to have no affect on the produced image.

**Comment by rheh** [comment]
Here a gist showing the issue I am having https://gist.github.com/rheh/7440d8ceb7d623beca7cde8c0e55776d

The second image myimage2.jpeg should not have the route layer.

**Comment by talaj** [comment]
Thanks, I used your test case.

It's because `get_layer` [returns new instance](https://github.com/mapnik/node-mapnik/blob/1cad07fe2f2928f2b6f497f5550f3e5f88411d13/src/mapnik_map.cpp#L985) by [copying the layer](https://github.com/mapnik/node-mapnik/blob/40fb7a7cc717bc45ea3dece7523e1743b12e14c4/src/mapnik_layer.cpp#L108) instead of referencing it from the map.

But I'm not sure if it's design decision or a bug. Some node-mapnik expert should step in.

**Comment by rheh** [comment]
@talaj thanks

**Comment by springmeyer** [comment]
@talaj is correct. The layers are copied when added to the map so it is not possible to modify layers inside a map after they are added.

> But I'm not sure if it's design decision or a bug. Some node-mapnik expert should step in.

This is a known limitation that I don't think should be changed. I don't think an API that allows mutating maps in place is within scope. I recommend thinking about map instances as best created once and then rendered one or more times and never modified again.

What I would recommend for your usecase - and what has worked well in my experience - is to generate an XML for all your layers and template the XML to allow you to generate and XML string either with the layers active or not. Then load that templated XML once with them all active and a second time with the specific layers disabled (or completely removed from the XML). XML templating might seem odd, but the behavior is predictable and loading is quite optimized.

**Comment by rheh** [comment]
Thanks guys.  As advised I'll take the approach advised.
