### ISSUE TITLE
Npm install on Windows is broken

### ISSUE THREAD

**Issue by donnyv** [mapnik/node-mapnik#762]
It looks like mapnik for windows is broken.
Getting a 403 on the mapnik windows binaries. 
![image](https://cloud.githubusercontent.com/assets/2224189/25305226/6a784bfe-2745-11e7-8751-9213a7a601c2.png)

**Comment by donnyv** [comment]
I guess no one cares that the windows install is broken?

**Comment by flippmoke** [comment]
This is on my todo list currently, just have had some other things to address currently.

**Comment by springmeyer** [comment]
We don't currently support anything but node v0.10.x, v4, and v5 on windows. You are running node v6. This is documented at https://github.com/mapnik/node-mapnik#depends

Node v6 support on windows will land once #758 lands.
