### ISSUE TITLE
Turn off datasource result caching?

### ISSUE THREAD

**Issue by brendanvinson** [mapnik/node-mapnik#766]
We're running into an issue currently where it appears that mapnik is caching results from the datasource and not updating when the data changes (initially hourly and then getting longer).

Config
Datasource type: Postgis
max_async_connections: 10
max_size: 10
extent_from_subquery: true

Is this something on mapnik's end or do we have an implementation error somewhere on our end?

**Comment by springmeyer** [comment]
> Is this something on mapnik's end

Unlikely. Mapnik does not cache datasource query results.

**Comment by brendanvinson** [comment]
Good to know.

In that case I had a couple questions for things I'm not clear on:

1. What does mapnik.clearCache() do in laymen's terms (if anything)?
2. We currently Cluster and Pool Datasources similar to mapnik-pool, only using pool2 instead of generic-pool. If we don't properly dispose of a mapnik.Map instance, could it prevent new data from being acquired?

**Comment by springmeyer** [comment]
> What does mapnik.clearCache() do in laymen's terms (if anything)?

It clears the "marker cache" which is a global cache of icons loaded during XML parsing. This advantageous because XML styles often contain hundreds of icon references to files. It is easy to run out of file handles if you compound the # of icons * parsing styles per thread. So this allows us to let go of the file handles after reading the data into memory.

It also clears the "mapped memory cache". This is a cache of memory segments that refer to datasources read, like shapfiles, or geojson. This is not used in postgis. You can see which plugins use the memory cache like:

```
~/projects/mapnik/3.0.x[collect-dep-data-paths]$ grep mapped_memory plugins/ src/ include/ -rI
plugins//input/csv/csv_datasource.cpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/csv/csv_datasource.cpp:            mapnik::mapped_memory_cache::instance().find(filename_, true);
plugins//input/csv/csv_featureset.cpp:            mapnik::mapped_memory_cache::instance().find(filename, true);
plugins//input/csv/csv_featureset.hpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/csv/csv_index_featureset.cpp:        mapnik::mapped_memory_cache::instance().find(filename, true);
plugins//input/csv/csv_index_featureset.hpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/geojson/geojson_datasource.cpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/geojson/geojson_datasource.cpp:            mapnik::mapped_memory_cache::instance().find(filename_, false);
plugins//input/geojson/geojson_index_featureset.cpp:        mapnik::mapped_memory_cache::instance().find(filename, true);
plugins//input/geojson/geojson_index_featureset.hpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/ogr/ogr_index_featureset.cpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/ogr/ogr_index_featureset.cpp:    boost::optional<mapnik::mapped_region_ptr> memory = mapnik::mapped_memory_cache::instance().find(index_file, true);
plugins//input/shape/dbfile.cpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/shape/dbfile.cpp:    boost::optional<mapnik::mapped_region_ptr> memory = mapnik::mapped_memory_cache::instance().find(file_name,true);
plugins//input/shape/dbfile.hpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/shape/shapefile.hpp:#include <mapnik/mapped_memory_cache.hpp>
plugins//input/shape/shapefile.hpp:            mapnik::mapped_memory_cache::instance().find(file_name,true);
src//build.py:    mapped_memory_cache.cpp
src//mapped_memory_cache.cpp:#include <mapnik/mapped_memory_cache.hpp>
src//mapped_memory_cache.cpp:template class singleton<mapped_memory_cache, CreateStatic>;
src//mapped_memory_cache.cpp:void mapped_memory_cache::clear()
src//mapped_memory_cache.cpp:bool mapped_memory_cache::insert(std::string const& uri, mapped_region_ptr mem)
src//mapped_memory_cache.cpp:boost::optional<mapped_region_ptr> mapped_memory_cache::find(std::string const& uri, bool update_cache)
src//mapped_memory_cache.cpp:            MAPNIK_LOG_ERROR(mapped_memory_cache)
src//mapped_memory_cache.cpp:        MAPNIK_LOG_WARN(mapped_memory_cache) << "Memory region does not exist file: " << uri;
src//tiff_reader.cpp:#include <mapnik/mapped_memory_cache.hpp>
src//tiff_reader.cpp:         mapnik::mapped_memory_cache::instance().find(filename,true);
include//mapnik/mapped_memory_cache.hpp:class MAPNIK_DECL mapped_memory_cache :
include//mapnik/mapped_memory_cache.hpp:        public singleton<mapped_memory_cache, CreateStatic>,
include//mapnik/mapped_memory_cache.hpp:    friend class CreateStatic<mapped_memory_cache>;
include//mapnik/mapped_memory_cache.hpp:extern template class MAPNIK_DECL singleton<mapped_memory_cache, CreateStatic>;
```

> We currently Cluster and Pool Datasources similar to mapnik-pool, only using pool2 instead of generic-pool (see #449 (comment)). If we don't properly dispose of a mapnik.Map instance, could it prevent new data from being acquired?

Not that I can think of. Unless you are caching data on the postgres side and Mapnik's postgis queries are not getting new data. Mapnik does not do any caching of data from postgis.

**Comment by ccFiona** [comment]
> sing pool2 ins



> > What does mapnik.clearCache() do in laymen's terms (if anything)?
> 
> It clears the "marker cache" which is a global cache of icons loaded during XML parsing. This advantageous because XML styles often contain hundreds of icon references to files. It is easy to run out of file handles if you compound the # of icons * parsing styles per thread. So this allows us to let go of the file handles after reading the data into memory.
> 
> It also clears the "mapped memory cache". This is a cache of memory segments that refer to datasources read, like shapfiles, or geojson. This is not used in postgis. You can see which plugins use the memory cache like:
> 
> ```
> ~/projects/mapnik/3.0.x[collect-dep-data-paths]$ grep mapped_memory plugins/ src/ include/ -rI
> plugins//input/csv/csv_datasource.cpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/csv/csv_datasource.cpp:            mapnik::mapped_memory_cache::instance().find(filename_, true);
> plugins//input/csv/csv_featureset.cpp:            mapnik::mapped_memory_cache::instance().find(filename, true);
> plugins//input/csv/csv_featureset.hpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/csv/csv_index_featureset.cpp:        mapnik::mapped_memory_cache::instance().find(filename, true);
> plugins//input/csv/csv_index_featureset.hpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/geojson/geojson_datasource.cpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/geojson/geojson_datasource.cpp:            mapnik::mapped_memory_cache::instance().find(filename_, false);
> plugins//input/geojson/geojson_index_featureset.cpp:        mapnik::mapped_memory_cache::instance().find(filename, true);
> plugins//input/geojson/geojson_index_featureset.hpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/ogr/ogr_index_featureset.cpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/ogr/ogr_index_featureset.cpp:    boost::optional<mapnik::mapped_region_ptr> memory = mapnik::mapped_memory_cache::instance().find(index_file, true);
> plugins//input/shape/dbfile.cpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/shape/dbfile.cpp:    boost::optional<mapnik::mapped_region_ptr> memory = mapnik::mapped_memory_cache::instance().find(file_name,true);
> plugins//input/shape/dbfile.hpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/shape/shapefile.hpp:#include <mapnik/mapped_memory_cache.hpp>
> plugins//input/shape/shapefile.hpp:            mapnik::mapped_memory_cache::instance().find(file_name,true);
> src//build.py:    mapped_memory_cache.cpp
> src//mapped_memory_cache.cpp:#include <mapnik/mapped_memory_cache.hpp>
> src//mapped_memory_cache.cpp:template class singleton<mapped_memory_cache, CreateStatic>;
> src//mapped_memory_cache.cpp:void mapped_memory_cache::clear()
> src//mapped_memory_cache.cpp:bool mapped_memory_cache::insert(std::string const& uri, mapped_region_ptr mem)
> src//mapped_memory_cache.cpp:boost::optional<mapped_region_ptr> mapped_memory_cache::find(std::string const& uri, bool update_cache)
> src//mapped_memory_cache.cpp:            MAPNIK_LOG_ERROR(mapped_memory_cache)
> src//mapped_memory_cache.cpp:        MAPNIK_LOG_WARN(mapped_memory_cache) << "Memory region does not exist file: " << uri;
> src//tiff_reader.cpp:#include <mapnik/mapped_memory_cache.hpp>
> src//tiff_reader.cpp:         mapnik::mapped_memory_cache::instance().find(filename,true);
> include//mapnik/mapped_memory_cache.hpp:class MAPNIK_DECL mapped_memory_cache :
> include//mapnik/mapped_memory_cache.hpp:        public singleton<mapped_memory_cache, CreateStatic>,
> include//mapnik/mapped_memory_cache.hpp:    friend class CreateStatic<mapped_memory_cache>;
> include//mapnik/mapped_memory_cache.hpp:extern template class MAPNIK_DECL singleton<mapped_memory_cache, CreateStatic>;
> ```
> > We currently Cluster and Pool Datasources similar to mapnik-pool, only using pool2 instead of generic-pool (see #449 (comment)). If we don't properly dispose of a mapnik.Map instance, could it prevent new data from being acquired?
> 
> Not that I can think of. Unless you are caching data on the postgres side and Mapnik's postgis queries are not getting new data. Mapnik does not do any caching of data from postgis.

hey, I ran into the similar problem when using shapefile, where shapefile contents changed but the result remained the same. Is there any way to clear shapefile datasource caches？
I've already called mapnik.clear_cache() before loading xml and rendering.

**Comment by arbrisseaux** [comment]
I'm using node-mapnik with postgis and a generic map pool to serve a dynamic layer.

I just found that I need to manually set the extent 

    <Parameter name="estimate_extent">false</Parameter>
    <Parameter name="extent">1234,5678,2345,6789</Parameter>

because the extent is cached in the map pool unless the map is destroyed.

If I create a feature outside the current extent, the tile will show 204 unless the map in the map pool is destroyed.
