### ISSUE TITLE
Rotation of shield markers around a point

### ISSUE THREAD

**Issue by rheh** [mapnik/node-mapnik#767]
Hi all,

I'm bashing my head against a wall trying to rotate a stick with a flag around a point keeping the stick base at the point.  I am using the shield symbolizer to load an svg and then using the transform and rotate feature.  For some reason I cannot get my head around how these values can be used to rotate the stick but keep the stick base at the point.  The issue I have can bee seen here:

![image](https://cloud.githubusercontent.com/assets/1724245/26016334/18230b86-3754-11e7-886b-2f52f5b1e054.png)

I'm pretty sure it is me not understanding how the transform and rotation value work rather than a mapnik issue.  I'm just hoping you guys know from experience what I am doing wrong.  To help you understand here is a gist of my progress:

https://gist.github.com/rheh/8ae5865cfa353ae2850cd66a48db9d46

Thanks

Ray

**Comment by talaj** [comment]
The trick is to set center of rotation:

```
transform="translate(8, -30) rotate([direction], -8, 30)"
```

![grib-1000-1000-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/26026985/4616ddd0-3806-11e7-99a3-43d1ccc0701e.png)

**Comment by rheh** [comment]
@talaj I see.  Thank you.
