### ISSUE TITLE
Build for node v8

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#774]
We need to start building binaries for node v8 in the next release. We've started doing this for windows already, but mac is blocked by https://github.com/mapnik/node-mapnik/issues/773. Once https://github.com/mapnik/node-mapnik/issues/773 is done then we need to:

 - [ ] Enable node v8 for linux
 - [ ] Enable node v8 for mac
 - [ ] Ensure all tests pass

**Comment by fernandocanizo** [comment]
Does attached 
[2017.06.02,mapnik.build.failed.txt](https://github.com/mapnik/node-mapnik/files/1049153/2017.06.02.mapnik.build.failed.txt)

failed build log has anything to do with this issue?

While we wait for the binaries, how can I fix this so it gets built?

**Comment by wemcdonald** [comment]
@springmeyer I'm just jumping in here from the outside, but I see that #773 is now closed. Does that mean that v8 should work now?

**Comment by springmeyer** [comment]
@wemcdonald almost. node-mapnik v3.6.1 will be released soon with node v8 support.

**Comment by springmeyer** [comment]
@flippmoke can this be closed?

**Comment by fernandocanizo** [comment]
I don't know about all the items you listed in your first message, but I can confirm now Mapnik installs fine both in Node 8.0.0 and v8.1.1

**Comment by springmeyer** [comment]
> @flippmoke can this be closed?

@flippmoke bump

**Comment by vjpr** [comment]
Works for me.
