### ISSUE TITLE
Building on Mac for node 7.10.0

### ISSUE THREAD

**Issue by davenquinn** [mapnik/node-mapnik#783]
Does the most recent version (3.6.2) of node-mapnik still support Mapnik core 3.0.13?

I'm building from source in a cloned directory on node 7.10.0, and I get the following error

```
error: no matching constructor for initialization of
      'mapnik::raster'
              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
```

late in the install process.

The mason build with `make` appears to work, but I can't rebuild for electron (node version 7.9) due to the same error.

**Comment by davenquinn** [comment]
Same thing on 7.9.0 with slightly more context:

```
In file included from /Users/Daven/.node-gyp/7.9.0/include/node/node.h:42:
In file included from /Users/Daven/.node-gyp/7.9.0/include/node/v8.h:21:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2206:15: error: no matching constructor for initialization of
      'mapnik::raster'
              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
              ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by davenquinn** [comment]
And actually the mason build fails at runtime

**Comment by davenquinn** [comment]
OK I got this to build by downgrading node-mapnik to 3.6.0 (b4823cd). So I guess 3.6.2 is only compatible with the latest 3.0.x mapnik core, 3.0.15?

Incidentally, I had to disable the node-gyp postinstall script (which tries to link a bunch of mason packages) to get the building to work while building with a Homebrew-installed mapnik.

I am just beginning to pull apart what is needed for the mason build vs. building against external mapnik, but it seems that there is no clear dividing line in general...

**Comment by springmeyer** [comment]
> Does the most recent version (3.6.2) of node-mapnik still support Mapnik core 3.0.13?

It does not. The mapnik version tracked is declared in the `package.json` file: https://github.com/mapnik/node-mapnik/blob/fe80ce5d79c0e90cfbb5a2b992bf0ae2b8f88198/package.json#L8. So, the cause for your compile error is that you need Mapnik v3.0.15.

WRT to electron builds - I've been thinking about providing binaries (learning from https://github.com/mapbox/node-sqlite3/pull/811). Is this something you would be interested in working on?

> Incidentally, I had to disable the node-gyp postinstall script (which tries to link a bunch of mason packages)

Apologies. This is my unfinished work. It should be clear how to build against mason packages or build against an external mapnik. I've ticketed fixing this up at #784

**Comment by davenquinn** [comment]
Electron binaries would be amazing. My main mapnik use-case is using it as a proto-GIS for building paper figures. All of that occurs in the electron runtime, so it would hugely demystify some of that work. Looking forward, I am hoping to wrap up a package including a mapnik renderer, and having it build reliably is a concern. I can definitely do some work towards this.

**Comment by springmeyer** [comment]
@davenquinn checking in on electron again - interested in helping get binaries building on travis? Should be doable similar to mapbox/node-sqlite3#811

**Comment by davenquinn** [comment]
Sorry – just noticed this query @springmeyer.  This fell by the wayside for me and I can't give much time right now because I am trying to shove my PhD thesis out the door. I'm going to keep using my hacked-together setups for now, but come ~March I might be able to spend some time on this. Anyway, I'll keep thinking about it, since mapnik built for electron is at the core of my house-of-cards software pipeline.

**Comment by springmeyer** [comment]
Best wishes for your PhD - see you in ~march if you have an opening.
