### ISSUE TITLE
Building from source against external mapnik

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#784]
We need to support both:

 - a. Installing from binaries (which are originally built from source against mason deps)
 - b. Building from source against mason deps
 - c. Building from source against an external mapnik

c. regressed after #738, unintentionally. This issue is to track fixing this by:

 - [ ] removing a few hardcoded flags
 - [ ] selectively running `postinstall.sh`
 - [ ] adding documentation to the readme for how to install against external mapnik (default will be against mason package)

**Comment by davenquinn** [comment]
As part of this, it would be helpful to have a blurb in the docs or a failable check against `mapnik-config` output at compile time that warns at buildtime against using the wrong mapnik version for source builds. I think a little more explanation here would have helped me...

```
To build from source you need:

Mapnik >= v3.0.10
```

**Comment by springmeyer** [comment]
Great idea.

**Comment by springmeyer** [comment]
Overall problem solved in #797 thanks to @Algunenano .

> As part of this, it would be helpful to have a blurb in the docs or a failable check against mapnik-config output at compile time that warns at buildtime against using the wrong mapnik version for source builds. I think a little more explanation here would have helped me...

Added in https://github.com/mapnik/node-mapnik/commit/55fc4d4452e0dd873b2952e7e7892f3ac1ea6d1a. @davenquinn that look good?
