### ISSUE TITLE
mapnik as a graphing tool?

### ISSUE THREAD

**Issue by rheh** [mapnik/node-mapnik#785]
This could be a silly question, but, can mapnik be used to generate simple 2D line graphs with an x, y axis?

Something like this:

![image](https://user-images.githubusercontent.com/1724245/28078295-4507c6d2-665c-11e7-8f08-3a92bd2be03b.png)

**Comment by talaj** [comment]
Surely it can, you just need to supply necessary geometries. By why not to use some dedicated tool for that?

**Comment by rheh** [comment]
I have started the project using d3 library.  The project has to be server-side and the more I use the library the more it feels like a client tool ported to node.  What's simple in mapnik (saving a PNG) is a pain in d3.  For example it renders a SVG to a virtual DOM.  Converting this to a PNG requires headless browers or unix command line exec calls which both feel wrong to me..  And the conversion then fails when the SVG gets complex (embedded assets)  I guess I'm just use to using mapnik for the last six months.  Anyways thanks for you feedback.  I'll close this ticket, but, if anyone has any opinions on gracefully solving this problem please feel free to share.
