### ISSUE TITLE
Add interface to grab features from node-mapnik

### ISSUE THREAD

**Issue by tmcw** [mapnik/node-mapnik#79]
Just recording this wishlist task: grabbing features from a mapnik.Map object, ideally clipped to an extent would be extremely useful and axe dependency on the (shockingly) sub-par nodejs PostGIS driver implementation.

**Comment by springmeyer** [comment]
Ticket cleanup: feature.toJSON / vtile.toGeoJSON have been offering this for a while, so closing.

example/test at https://github.com/mapnik/node-mapnik/blob/master/test/shp2geojson.test.js
