### ISSUE TITLE
Rendering a path over the Pacific ocean

### ISSUE THREAD

**Issue by rheh** [mapnik/node-mapnik#794]
I am working an a mapping project that map flight paths around the globe.  I have hit a issue where that paths that cross the international dateline do not render as one would expect.  My first effort resulted in the path wrapping around the world e.g.

![image](https://user-images.githubusercontent.com/1724245/28834122-55c9b934-76d9-11e7-9ff1-faf4f8ee8f7a.png)

I then solved that issue by splitting my geojson line-string at the international dateline.  This fixes the wrapping issue e.g.

![image](https://user-images.githubusercontent.com/1724245/28834182-818fdc38-76d9-11e7-93b7-43fa9eb31189.png)

As you can see the whole world is displayed.  I believe this is due to the extents on the path layers have an extent of [ -179.90000000000373, 33.94333, 179.90000000000373, 53.905 ]. 

I then did some reading on render maps over the 180 and to be honest got more confused than I was originally.  Though I did think I was onto something when I read the proj4 documentation http://proj4.org/parameters.html#lon-wrap-over-longitude-wrapping which includes the settings +lon_0     .  This let you control the "Central meridian".  Setting this to -180 the produces the following:

![image](https://user-images.githubusercontent.com/1724245/28834562-78fabc40-76da-11e7-9f8f-97c455d4daf8.png)

Although a mess the route path is centred nicely.  But, as you can see the land boundaries now wrapped :-(

I am hoping I am missing something obvious as what I am trying to achieve doesn't see that tricky.  The end product would be something like this:

![image](https://user-images.githubusercontent.com/1724245/28834648-bf75bb66-76da-11e7-8dcc-c0f396cc3d2a.png)

I hope that explains enough for someone to point me in the right direction.  To help I have also created a Gist to replicate the issues I  am having. https://gist.github.com/rheh/ceb91287001b97c9f0495083412b4ed6

Code in render.js file

Thanks in Advance

Ray

**Comment by springmeyer** [comment]
> But, as you can see the land boundaries now wrapped :-(

Do avoid them being wrapped and resulting in the unwanted lines across the map, you'll need to clip them. In this case not at the dateline, but in the middle of the atlantic. I would recommend looking into whether you can achieve this using the `ogr2ogr` `-clipsrc` command. http://www.gdal.org/ogr2ogr.html

**Comment by rheh** [comment]
@springmeyer thanks for the suggestion.  Amazing what a good nights sleep does.  You suggestion prompted me to look at a projection that is more suitable.  Such as http://epsg.io/3832 which does indeed use the lon_0 trick

`<?xml version="1.0" encoding="utf-8"?>
<Map srs="+proj=merc +lon_0=150 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs">
	<Layer srs="+proj=merc +lon_0=150 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs">
	</Layer>
</Map>
`
Thus, I'm now rendering something close

![image](https://user-images.githubusercontent.com/1724245/28870935-253eaec2-777a-11e7-8b05-c27202bb353f.png)


For future reference this link helps to tackle the 180 / Pacific issue https://gis.stackexchange.com/questions/138735/appropriate-map-projection-for-the-pacific-ocean/138745

In my opinion this ticket can be closed, unless you guys can think of any action points help others in the future?

**Comment by springmeyer** [comment]
Looks great - awesome work @rheh! Before closing the only think I can think of would be adding a testcase to mapnik core for this usage: it could include a bit of public sample data a mapnik XML. This would ensure that this usecase never breaks in the future as mapnik development happens, and you could link to it from here so interested developers could see an working example. See https://github.com/mapnik/mapnik/wiki/A-perfect-testcase for how to do this.

**Comment by springmeyer** [comment]
No response on the testcase idea, so closing.

**Comment by 1jpaulo** [comment]
q
