### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by raxim1** [mapnik/node-mapnik#796]
../node_modules/mapnik-vector-tile/src/vector_tile_geometry_clipper.hpp:10:40: fatal error: mapbox/geometry/geometry.hpp: No such file or directory

**Comment by talaj** [comment]
It's a git submodule, [see](https://github.com/mapnik/node-mapnik/tree/13005d429883cb3372db5b9bd56470c1c5ac174a/deps). Try `git submodule update --init`.

**Comment by raxim1** [comment]
Thanks a lot. Git has some feature what i'm not aware of. I need to read the manual. (I used mostly svn)

It's a very basic question: (I have no idea about phyton)
Any idea, how to build "osm" plugin to node-mapnik. I cannot run "phyton build.py".
NameError: name 'Import' is not defined

**Comment by talaj** [comment]
Mapnik osm plugin [is considered unmaintained and deprecated](https://github.com/mapnik/mapnik/issues/2980). OSM is being usually rendered, at least what I know, from postgis, but this is beyond scope of node-mapnik binding issues.

> I cannot run "phyton build.py".

If you have problems building Python bindings, file an issue in [python-mapnik](https://github.com/mapnik/python-mapnik).
