### ISSUE TITLE
Release planning for v3.7.x and v4.0.x

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#808]
I propose two upcoming milestones:

 - [v3.6.3](https://github.com/mapnik/node-mapnik/milestone/39) - next stable release supporting C++11 only and mapnik v3.0.x series
 - [v3.7.0](https://github.com/mapnik/node-mapnik/milestone/40) - first release in v3.7.x series, supporting C++14  and Mapnik 3.1 (https://github.com/mapnik/mapnik/milestone/26)*

* Note: if anything is majorly breaking about Mapnik 3.1 then we could call the node-mapnik release 4.x. But that is weird: the idea is to have node-mapnik and mapnik versioned independently (for flexibility) but still keep the major versions the same. So ideally Mapnik 3.1 is minimally breaking.

Before each of these releases we should move on formatting the codebase with `clang-format` 4.x to ensure that whitespace and formatting is not a blocker to cherry-picking between the branches (when needed). Refs https://github.com/mapnik/node-mapnik/issues/807

Also, after:

 - `v3.6.3` is released
 - Mapnik 3.1.x is released

I propose branching a node-mapnik `v3.6.x` branch and then making `master` target Mapnik 3.1.

/cc @talaj @artemp

**Comment by springmeyer** [comment]
> Before each of these releases we should move on formatting the codebase with clang-format 4.x to ensure that whitespace and formatting is not a blocker to cherry-picking between the branches (when needed). Refs #807

I now think we should not apply clang-format to both the release series branches (to much work). Rather we should only apply clang-format (adapting my work at #841) to master, and plan to run with using clang-format in master.

**Comment by springmeyer** [comment]
Because windows is broken and my only option is to remove support (https://github.com/mapnik/node-mapnik/issues/848) I'm feeling that the next release should be 4.0.0 since it will be a breaking change for windows users. /cc @flippmoke @mapsam 

Note: For a while now we tried to keep the major version between node-mapnik and mapnik the same, but I think it is the wrong approach, so I'd like to decouple them. This way we can properly represent breaking changes in the node-mapnik API separately from mapnik core. So I think we should the v3.6.3 release to be 4.0.0. And then the 3.7.x release (supporting c++14) can be 5.0.0.

**Comment by flippmoke** [comment]
The next two releases I think should be:

`3.7.0` and `4.0.0`

`3.7.0` should be a release of all existing changes in the pipeline plus be the first version that no longer supports windows binaries. This is in line with many of the other minor version bumps we have made in the past and keeps with the traditional versioning system of node-mapnik. 

`4.0.0` should be the first release supporting C++14 fully and requires the as yet unreleased mapnik `3.1.x` or `4.x`? `TBD?`

I am hoping that we can have mapnik with C++14 and various other large changes be `4.0.0` rather then `3.1.x`. This could allow us to keep with the same major version between node-mapnik and mapnik as well. I think the more alike we can make these version the less confusion we can keep in the community.

**Comment by springmeyer** [comment]
> 4.0.0 should be the first release supporting C++14 fully and requires the as yet unreleased mapnik 3.1.x or 4.x? TBD?

👍 I've not cut v4.0.0 using latest mapnik 3.1.x HEAD (likely to be actually tagged as mapnik core 4) https://github.com/mapnik/node-mapnik/issues/880
