### ISSUE TITLE
Projection in mapnik

### ISSUE THREAD

**Issue by exotfboy** [mapnik/node-mapnik#811]
Hi:

I am using  node-mapnik 3.6.2 to generate vector tiles with wgs84 projection.

However I found that all the tiles are empty, and then I  found this [issue](https://github.com/mapnik/node-mapnik/issues/693). 

It seems that `node-mapnik` will check the  bounds for a tile, and exclude the features outside the bounding. While the bounds are calculated with projection `3857`, so the features may be filtered .

So I wonder if it is possible to make `mapnik` use different projection?

Furthermore, I wonder if it is  `mapnik`'s responsibility to do the check and transform job? Since the `MAPBOX VECTOR TILE SPECIFICATION` only says that the coordinates should be projected which does not say from which the coordinate should be projected from. It is user's job to do the projection.

Anyway, is it possible to solve my current problem?

**Comment by springmeyer** [comment]
For clarity lets start by distinguishing between `source` projection and `target` projection. The `source` projection is the projection of the geodata being read. The `target` projection is the projection that a vector tile encoder will project into before translating the data into integer tile coordinates.

The vector tile specification does not specify the `target` projection (https://github.com/mapbox/vector-tile-spec/tree/master/2.1#3-projection-and-bounds) other than mentioning it is the "reference". So this is what most encoders, including node-mapnik, target. Therefore, the node-mapnik encoder only supports web mercator (aka `epsg:3857`) for the `target` projection.

https://github.com/mapnik/node-mapnik/issues/693 is a problem where the data projection was incorrect.

> I am using node-mapnik 3.6.2 to generate vector tiles with wgs84 projection.

This is not possible without changing node-mapnik.
