### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by sommerluk** [mapnik/node-mapnik#814]
Hello.

I've tried to install kosmtik in npm, which seems to have mapnik as dependency. Now the installation fails. I've tried in openSUSE 42.3 and Kubuntu 16.04, with the same result. Here is the attached log:

[npm-debug.log](https://github.com/mapnik/node-mapnik/files/1382108/npm-debug.log)

**Comment by springmeyer** [comment]
You are hitting a bad interaction between the latest npm `3.5.x` and older node-mapnik releases (released well before npm 3.5.x came out). 

The diagnostic error is:

> 9387 warn enoent ENOENT: no such file or directory, open '/home/sommerluk/Dokumente/OSM/kosmtik/package.json'

Which indicates to be that the following workarounds will likely fix the problem:

 - Downgrade npm to 2.x
 - Upgrade node-mapnik to the latest 3.6.x release

refs https://github.com/mapbox/node-pre-gyp/issues/260
