### ISSUE TITLE
Option to get GeoJSON features unescaped

### ISSUE THREAD

**Issue by charandas** [mapnik/node-mapnik#815]
While I understand, that mapnik is primarily to serve Maps, and I am using it for that with Postgis in one of my services, I do also like the possibility of using Mapnik just to get GeoJSON from my Postgis tables.

`node-gdal` does not come with postgis support out of the box, and I really think its simple with `mapnik`:

```js
const datasource = new mapnik.Datasource(sourceOpts)
  const features = []
  const featureset = datasource.featureset()
  let feature = featureset.next()

  while (feature) {
    features.push(feature)
    feature = featureset.next()
  }

  const result = {
    type: 'FeatureCollection',
    crs: { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } },
    features
  }
// persist to file.geojson
```

Everything is well except that features aren't legal JSON. I needed this to get it to be recognized by supercluster/mapbox-gl:

```
sed -i -e 's/\\"/"/g'  "file.geojson"
sed -i -e 's/"{/{/g'  "file.geojson"
sed -i -e 's/}"/}/g'  "file.geojson"
```

Then it works! I can also do these replacements in nodejs, but it seems fragile. Any recommendations?

I know node-mapnik is a binding for a c++ module, and hence perhaps is escaping JSON, but is there a possibility currently or if not, can it be implemented in node-mapnik to return legal GeoJSON to the user?

**Comment by springmeyer** [comment]
You need to call `JSON.parse(feature.toJSON())` to get the actual GeoJSON for a given feature. Then add that to your `features` array. More details: http://mapnik.org/documentation/node-mapnik/3.6/#Feature.toJSON

**Comment by charandas** [comment]
Thanks @springmeyer. I will close this issue.

While I have your attention, can I take the opportunity one more of my lingering doubts.

Does the dataSource being garbage collected at JS scope cleanup the underlying database resources mapnik instantiates for getting the features?

I couldn’t find a close/cleanup method on the interface a dataSource exposes.

**Comment by springmeyer** [comment]
> Does the dataSource being garbage collected at JS scope cleanup the underlying database resources mapnik instantiates for getting the features?

Not by default. Connections to the database, by default, are kept open by Mapnik for best performance. If you don't want these connections active and you want to disable this behavior you can either:

1. Add `persist_connection:false` to your `sourceOpts` (datasource options)
1. Turn your postgres database to automatically cleanup tcp connections like https://github.com/mapnik/mapnik-support/issues/44#issuecomment-117777926

> I couldn’t find a close/cleanup method on the interface a dataSource exposes

The reason the close method is not programmatically available is that most Mapnik usage is via programs loading mapnik.Map objects via mapnik XML stylesheets. So, we default to keeping things open for best performance in that case.

**Comment by charandas** [comment]
Lastly, will `persist_connection: false` actually close the DB connection between each of these`.next()` calls:

```
 while (feature) {
    features.push(feature)
    feature = featureset.next()
  }
```

**Comment by springmeyer** [comment]
No, `persist_connection: false` will close the DB connection after `datasource` goes out of scope (the `mapnik.Datasource`) and after the V8 garbage collector runs. So, `persist_connection: false` makes it possible for the connection to be released but does not guarantee it will be.
