### ISSUE TITLE
Support FreeBSD

### ISSUE THREAD

**Issue by tsgan** [mapnik/node-mapnik#818]
Please add /usr/local/include to include_dirs, that way it can be installed on FreeBSD.
thanks,

**Comment by springmeyer** [comment]
You can add `/usr/local/include` yourself by doing:

```
export CXXFLAGS="-I/usr/local/include"
```

And then following the source build instructions: https://github.com/mapnik/node-mapnik#source-build

Also, if you have correctly installed mapnik, then `mapnik-config` should be reporting all the include paths needed for it and its dependencies, so you should not need to set `CXXFLAGS` yourself in normal cases.

**Comment by tsgan** [comment]
On Fri, Nov 17, 2017 at 6:52 AM, Dane Springmeyer <notifications@github.com>
wrote:

> You can add /usr/local/include yourself by doing:
>
> export CXXFLAGS="-I/usr/local/include"
>
> And then following the source build instructions:
> https://github.com/mapnik/node-mapnik#source-build
>

It won't work that way if I use "npm install"

Ganbold

**Comment by springmeyer** [comment]
> Yes, as I understand npm install looks for binary package first and if not found it tries to build from source.

Correct.

> In that case include_dirs still needs to have /usr/local/include

Not normally. The include dirs will be pulled from `mapnik-config --cflags`, which should include the directory where mapnik and its dependencies will be found.

**Comment by tsgan** [comment]
Does 'npm install' do 'mapnik-config --cflags'??? Why? Is it hard for you to include /usr/local/include in case of FreeBSD for include_dirs?
