### ISSUE TITLE
v3.0.x passing against mapnik v3.0.17

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#820]
Now that Mapnik v3.0.16 is out (http://mapnik.org/pages/downloads.html) the node-mapnik v3.0.x branch needs to be:

 - [x] create a mason package of mapnik v3.0.16 (@artemp) - https://github.com/mapbox/mason/issues/514
 - [ ] Update the https://github.com/mapnik/node-mapnik/blob/v3.0.x/install_mason.sh to point to the latest mapnik package and the mason gitsha (@artemp)
 - [x] ensure all the tests are passing (@artemp)

Note: this ticket only concerns the stable v3.0.x series: master's test should be passing after #817

**Comment by kocio-pl** [comment]
Just to make things clear: does it mean node-mapnik still tries to use Mapnik 3.0.15? How should I compile it with v3.0.16 then - using B) from https://github.com/mapnik/node-mapnik/blob/master/README.md#source-build?

Currently when using  v3.0.x branch and a command `make release` I get:

```
NOTICE: to build from source you need mapnik >= v3.0.16 
Looking for mapnik-config on your PATH...
mapnik-config -v
3.0.15
```

**Comment by kocio-pl** [comment]
I have also tried B) using packages built from Debian repo:

```bash
git clone git://anonscm.debian.org/pkg-grass/mapnik.git
cd mapnik 
git describe --abbrev=0 --tags # it gives me: debian/3.0.16+ds-1_exp1
dpkg-buildpackage -B
```

and after installing them by dpkg the proper Mapnik version is used:

```
$ make release_base
NOTICE: to build from source you need mapnik >= v3.0.16 
Looking for mapnik-config on your PATH...
mapnik-config -v
3.0.16
```

but I get errors like:

```
/media/hdd/home/kocio/.node-gyp/8.9.1/include/node/v8.h:9097: undefined reference to `v8::V8::ToLocalEmpty()'
```

I'm writing about it here because I'm not sure what issue it might be.

**Comment by kocio-pl** [comment]
Probably setting compiler options to use Clang instead of GCC helped me, but I'm not sure. However I was able to compile it using Mapnik from system packages (B source build).

**Comment by springmeyer** [comment]
> but I get errors like:
> /media/hdd/home/kocio/.node-gyp/8.9.1/include/node/v8.h:9097: undefined reference to `v8::V8::ToLocalEmpty()'

That looks like an issue with the latest node.js v8.x version. Stick with node v6 or v4 or avoid that problem for now. I presume it will be fixed once we upgrade Nan, which is in process at #824

**Comment by kocio-pl** [comment]
Oh, maybe that was what helped me - now I use standard nodejs/npm from Ubuntu 17.10.

**Comment by kocio-pl** [comment]
BTW - I don't know yet what could be the problem and it needs some investigating, but 3.0.16 package built from Debian and used by compiled node-mapnik resulted in loosing road shields outline and the the background (the ref number was still there) in the osm-carto. Mapnik 3.0.15 from npm does not have this problem.

**Comment by springmeyer** [comment]
We are now green and building okay (all tests passing) against mapnik v3.0.17 mason package in the v3.0.x branch. So I'm going to close this. @kocio-pl please re-open a different issue if you still are seeing problems on your end.
