### ISSUE TITLE
error compiling against mapnik 3.0.16

### ISSUE THREAD

**Issue by pfps** [mapnik/node-mapnik#825]
I'm getting 
../src/utils.hpp:16:10: fatal error: mapnik/value/types.hpp: No such file or directory
when compiling the current node-mapnik against mapnik 3.0.16

Is this a real problem or is there something else that I should be compiling against instead?

**Comment by flippmoke** [comment]
This should be addressed by the recent changes to master -- please `v3.0.x` branch for 3.0.x branches of mapnik. Current master should be used with current master of mapnik.
