### ISSUE TITLE
Which projection is used when transform longitude & latitude to tile coordinate(pixel cooridnate)

### ISSUE THREAD

**Issue by exotfboy** [mapnik/node-mapnik#830]
Hi:

I tried to use `node-mapnik` to generate some mapbox-vector-tile, and we need render the map by EPSG:4326 projection, and we have our own client to make that.

However I found that mapnik use the `web mercator` to calculate the coordinates relative to the vector tile:
https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_vector_tile.cpp#L1989

Is that possible to generate EPSG:4326 based vector tiles?

**Comment by springmeyer** [comment]
> Is that possible to generate EPSG:4326 based vector tiles?

Not with node-mapnik. You can try tippecanoe: https://github.com/mapbox/tippecanoe/pull/253

**Comment by exotfboy** [comment]
@springmeyer  Maybe I have not make myself clear enough. I do not need projections for input data but the output.

Suppose for a given point `(90,45)` at zoom `1`:
The tile coordinate is `1,1,0` in web mercator tile system, and the coordinate of this point relative to the tile is `128,128`.

The tile coordinate is `1,2,0` in web wgs 84 tile system, and the coordinate of this point relative to the tile is `256,128`.

Mapnik use the `web mercator` while I'd prefer to `wgs84`.

However I still check `tippecanoe`, while it is used to generate tiles for a large set of geojson. I'd like to retrieve data for a tile from database and transform it to vector tile directly.


Furthermore, since the Vector Tile Specification does not cover how the geometry should be transformed. And as a popular gis library, is it a better idea to provide the ability for the user to choice their own transformation algorithm?

**Comment by springmeyer** [comment]
@exotfboy yes, I understood you. Also #811. I think your request is reasonable and makes sense, however we have no plans to add support to node-mapnik for the coordinates to be in `wgs84`. So, if you want to try to add support yourself, please feel free, but this is not something I plan to work on.

**Comment by exotfboy** [comment]
Sorry I forget I have post that issue :(
