### ISSUE TITLE
Upgrade mapnik-vector-tile

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#843]
@flippmoke is planning a release of mapnik-vector-tile targeting mapnik v3.0.x and including https://github.com/mapbox/mapnik-vector-tile/pull/262.

This ticket is to track that v3.6.3 will wait on this release and mapnik master should also be updated with a corresponding mapnik-vector-tile version.

**Comment by sebastic** [comment]
It looks like mapnik-vector-tile 1.6.0 includes those changes, node-mapnik needs to be fixed to build successfully with v1.6.0.
