### ISSUE TITLE
Upgrade to mapnik v3.0.18

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#844]
Mapnik v3.0.18 is set to come out soon. @artemp - please plan to upgrade the v3.0.x branch of node-mapnik to it once you've cut the release and built binaries.

**Comment by sebastic** [comment]
Mapnik 3.0.18 was released a week or so ago, and 239e6db92bd93730b1ea1ed9d8c0d17f0e9d2871 updated the mapnik version in `package.json`.

**Comment by tomhughes** [comment]
It would be nice to have a proper release of node-mapnik that works with a recent mapnik for sure...

**Comment by artemp** [comment]
👍

**Comment by tomhughes** [comment]
Well what do we need to do to make it happen @artemp ;-)

**Comment by artemp** [comment]
This is my plan:

* release mapnik 3.0.19 including grid-text-placement fix (/cc @talaj )
* release node-mapnik https://github.com/mapnik/node-mapnik/milestone/39 

/cc @tomhughes

**Comment by artemp** [comment]
and : 
* ensure mapnik/node-mapnik combo works on aws lambda

**Comment by tomhughes** [comment]
Looks like it needs updating for the latest mapnik-vector-tile as well - the v3.0.x branch currently wants 1.4.0 and won't build against 1.6.0 by the looks of it.

**Comment by artemp** [comment]
@tomhughes - yep, indeed ^

**Comment by flippmoke** [comment]
I was in the process of working on this last week before I started my vacation. I am digging into one reprojection bug in `mapnik-vector-tile` right now. Checkout the https://github.com/mapnik/node-mapnik/tree/v3.0.x_changes branch for now. It has the v3.0.18 release in it along with `v1.6.0` of node-mapnik.
