### ISSUE TITLE
Binding folder is missing

### ISSUE THREAD

**Issue by volkanunsal** [mapnik/node-mapnik#845]
Here is a simple Dockerfile to replicate it

```Dockerfile
FROM mhart/alpine-node:8.8.1

RUN echo "@testing http://dl-3.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && sed -i -e 's/v3\.[0-9]/edge/g' /etc/apk/repositories
RUN apk update
RUN apk add bash
RUN apk add mapnik@testing --update-cache
RUN mkdir /webapp
WORKDIR /webapp

RUN npm install mapnik

CMD ["node", "-p", "require('mapnik')"]
```

```bash
docker build -t foo ./ && docker run --rm foo
```

```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /webapp/node_modules/mapnik/lib/binding/mapnik.node)
```

**Comment by tomhughes** [comment]
Actually from that error it looks like the binding folder (and the `mapnik.node` shared library inside it) exists just fine but that it can't find the ELF interpreter `ld-linux-x86-64.so.2` which would normally be found in `/lib64` or maybe `/lib` depending on the linux distribution.

**Comment by tomhughes** [comment]
I see alpine linux uses musl rather than glibc so I wonder if the ELF interpreter has a different name? Though I thought that was fixed in the ELF ABI... If you run `ldd /bin/uname` or something you should be able to see - it should look something like:

```
linux-vdso.so.1 (0x00007ffe431cc000)
libc.so.6 => /lib64/libc.so.6 (0x00007f194c04f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f194c63b000)
```
In any case the answer may well be that you'll need to build from source rather than downloading a prebuilt `mapnik.node` that was probably build for a different distro.

**Comment by volkanunsal** [comment]
I tried building from source using Ubuntu as well. Got the same error, I think. (I wish I'd saved the error message.) Here is the Dockerfile for that.

https://gist.github.com/volkanunsal/afc67d600d4b741327090d1240f94462

It requires some more work to get it up and running. It assumes a package.json file, but otherwise it's not different from the other one.

**Comment by volkanunsal** [comment]
@tomhughes It looks like I had made an error. When calling yarn, I usually use `--ignore-scripts --ignore-optionals` flags. I guess node-mapnik needs to use the scripts to generate this folder?

Here is my updated and working Dockerfile for Alpine Linux, in case anyone needs it:

```Dockerfile
FROM mhart/alpine-node:8.9.4

RUN echo "@testing http://dl-3.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && sed -i -e 's/v3\.[0-9]/edge/g' /etc/apk/repositories
RUN apk update
RUN apk add bash
RUN apk add mapnik@testing --update-cache
RUN mkdir /webapp
WORKDIR /webapp

## node-mapnik dependencies.
RUN apk add --virtual build-dependencies alpine-sdk util-linux tar unzip python python-dev libexecinfo-dev

# Install packages using Yarn
ADD webapp/package.json  webapp/yarn.lock /tmp/
RUN cd /tmp && yarn install
RUN ln -s /tmp/node_modules

COPY webapp /webapp/

# Cleanup
RUN yarn cache clean && apk del build-dependencies

CMD ["bash"]
```
