### ISSUE TITLE
Not a map file. Node 'Map' not found.

### ISSUE THREAD

**Issue by MilanVilov** [mapnik/node-mapnik#853]
I cannot seem the open the .osm file i downloaded from open street map.
https://api.openstreetmap.org/api/0.6/map?bbox=11.54,48.14,11.543,48.145

When i run this code i get the error from subject.
```
app.get('/api/map', (req, res) => {
  var map = new mapnik.Map(256, 256);
  console.log(path.join(__dirname, './mapnik/map.osm'))
  map.load(path.join(__dirname, './mapnik/map.osm'), function(err,map) {
    if (err) throw err;

    map.zoomAll();
    var im = new mapnik.Image(256, 256);
    map.render(im, function(err,im) {
      if (err) throw err;
      im.encode('png', function(err,buffer) {
          if (err) throw err;
          fs.writeFile('map.png',buffer, function(err) {
              if (err) throw err;
              console.log('saved map image to map.png');
          });
      });
    });
});
```

And i cannot install libxml2, because the npm cannot find it.
Thank you.

**Comment by talaj** [comment]
It is not possible to call `map.load` with an `.osm` file. [`map.load`](http://mapnik.org/documentation/node-mapnik/3.6/#Map.load) loads Mapnik stylesheet whereas `.osm` is a geographic data format.
