### ISSUE TITLE
Window 10 x64, cannot install

### ISSUE THREAD

**Issue by sewerrat** [mapnik/node-mapnik#867]
Hi!
I'm using windows 10 x64. 
My node version is 6.9.4.
I tried to install mapnik 

> npm install tilelive-mapnik --save

but it gives me error

> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.1/node-v48-win32-x64-Release.tar.gz

Is version for windows not ready?
Thanks!

**Comment by ink-su** [comment]
Looks like you would have to build it yourself if it's not prebuild: 
https://github.com/mapnik/node-mapnik/issues/728

**Comment by flippmoke** [comment]
We dropped support for pre-built binaries for windows, I am sorry our reasons are explained in #848
