### ISSUE TITLE
Render map as svg

### ISSUE THREAD

**Issue by eNepper** [mapnik/node-mapnik#868]
I have seen an example in python that renders a map as svg by calling mapnik.render_to_file instead of using the image render. Is this also possible when using node-mapnik? I'm not talking about rendering vector tiles but full maps as svg.

-- Esben N.

**Comment by talaj** [comment]
Yes, this is possible. You need node-mapnik compiled with Cairo backend. Then you can set `svg` to the `format` parameter:

```javascript
map.renderFileSync(filename, {format:'svg'});
```

```javascript
map.renderFile(im, {format:'svg'}, function(err, im) {});
```


This is test case for rendering from vector tile to SVG:
https://github.com/mapnik/node-mapnik/blob/fed5a1c0e67c8458045f56df49b2254cc618ca40/test/vector-tile.test.js#L2673-L2697

**Comment by eNepper** [comment]
It seems unclear to me how I can build node-mapnik with Cario. Can you give me some instructions for this?

**Comment by talaj** [comment]
[`HAVE_CAIRO`](https://github.com/mapnik/node-mapnik/blob/7dfb6971cda5682b44e8f18b06f8b4bc95bde7bf/src/mapnik_cairo_surface.hpp#L14) has to be defined. That means Mapnik needs to be compiled with Cairo. You can check that flag by

```console
$ mapnik-config --cflags | grep -o HAVE_CAIRO                                                                                                                                                     
HAVE_CAIRO
```

**Comment by eNepper** [comment]
When I run $ mapnik-config --cflags | grep -o HAVE_CAIRO   
I get HAVE_CAIRO as output so Mapnik is compiled with cairo, but do I need to compile node-mapnik manually for it to work?

**Comment by talaj** [comment]
I think there is no binary compatibility between different versions of Mapnik and node-mapnik so if your node-mapnik was not compiled against that Mapnik with `HAVE_CAIRO` they will not work together.

You can use `mapnik.supports` API to check what your node-mapnik supports:

```console
 $ node
> var mapnik = require('mapnik')
undefined
> mapnik.supports
{ grid: true,
  svg: true,
  cairo: true,
  cairo_pdf: true,
  cairo_svg: true,
  png: true,
  jpeg: true,
  tiff: true,
  webp: true,
  proj4: true,
  threadsafe: true }
>
```

**Comment by eNepper** [comment]
I have now successfully saved an SVG file from mapnik, but can I skip the part where I save the SVG as a file and instead get the output as a buffer?

**Comment by talaj** [comment]
@eNepper Unfortunately, I haven't found rendering to a buffer in the node-mapnik interface.

**Comment by talaj** [comment]
@janzankowski See https://github.com/mapnik/mapnik/issues/3749.

**Comment by eNepper** [comment]
What changes would it require to be able to output SVG to a buffer?
