### ISSUE TITLE
Outdated build instructions for AWS Lambda?

### ISSUE THREAD

**Issue by gopokyo-colinn** [mapnik/node-mapnik#873]
I'm trying to rebuild mapnik and node-mapnik so that it loads quicker on AWS Lambda.  My strategy is to strip out image and database support that we do not use.

I have mapnik built, but am not sure how to build node-mapnik in a lambda environment.  As you are well aware, it does not have a recent enough GCC to compile.

I'm looking at the following instructions: https://github.com/mapnik/mapnik/wiki/AWS-Lambda

These instructions require that I switch to a clang-5 branch in node-mapnik, but git is unable to find this branch:

`bash-4.2# git checkout clang-5
error: pathspec 'clang-5' did not match any file(s) known to git.
`

Would greatly appreciate any hints on how to proceed.

**Comment by mapsam** [comment]
I believe @artemp built on lambda most recently - any thoughts here?

**Comment by artemp** [comment]
@gopokyo-colinn 
try `git checkout v3.0.x` instead and post here results.

**Comment by gopokyo-colinn** [comment]
Here is what I get.  Note that I did some fiddling to make sure the code I had was up to date with the head of v3.0.x

`bash-4.2# git checkout v3.0.x
Branch v3.0.x set up to track remote branch v3.0.x from origin.
Switched to a new branch 'v3.0.x'
bash-4.2# git submodule update
bash-4.2# make
CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" PATH="./mason_packages/.link/bin/:/usr/local/lib64/node-v4.3.x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" make release_base
make[1]: Entering directory `/var/task/node-mapnik'
NOTICE: to build from source you need mapnik >= v3.0.20 
Looking for mapnik-config on your PATH...
mapnik-config -v
3.1.0
V=1 CXXFLAGS="-fno-omit-frame-pointer -g" ./node_modules/.bin/node-pre-gyp configure build --ENABLE_GLIBC_WORKAROUND=true --enable_sse=true --loglevel=error --clang
make[2]: Entering directory `/var/task/node-mapnik/build'
  /usr/bin/c++ '-DNODE_GYP_MODULE_NAME=mapnik' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DMAPNIK_GIT_REVISION="v3.0.12-750-ga2f5969"' '-DSSE_MATH' '-DBUILDING_NODE_EXTENSION' '-DNDEBUG' -I/root/.node-gyp/4.3.2/include/node -I/root/.node-gyp/4.3.2/src -I/root/.node-gyp/4.3.2/deps/uv/include -I/root/.node-gyp/4.3.2/deps/v8/include -I../mason_packages/.link/include -I../mason_packages/.link/include/freetype2 -I../mason_packages/.link/include/cairo -I../src -I../node_modules/nan -I../deps/geometry/include -I../deps/wagyu/include -I../node_modules/protozero/include -I../node_modules/mapnik-vector-tile/src  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -std=c++11 -std=c++11 -I/var/task/node-mapnik/mason_packages/.link/include -I/var/task/node-mapnik/mason_packages/.link/include/mapnik/agg -I/var/task/node-mapnik/mason_packages/.link/include/mapnik -I./mason_packages/.link/include -I./mason_packages/.link/include/freetype2 -I./mason_packages/.link/include/libpng16 -I./mason_packages/linux-x86_64/libgdal/2.1.3/include -I./mason_packages/.link/include/cairo -I./mason_packages/.link/include/pixman-1 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DMAPNIK_NO_ATEXIT -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DSVG_RENDERER -std=c++14 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -O3 -MMD -MF ./Release/.deps/Release/obj.target/mapnik/src/mapnik_logger.o.d.raw -fno-omit-frame-pointer -g -c -o Release/obj.target/mapnik/src/mapnik_logger.o ../src/mapnik_logger.cpp
c++: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [Release/obj.target/mapnik/src/mapnik_logger.o] Error 1
make[2]: Leaving directory `/var/task/node-mapnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/local/lib64/node-v4.3.x/bin/node" "/usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--ENABLE_GLIBC_WORKAROUND=true" "--enable_sse=true" "--loglevel=error" "--clang" "--module=/var/task/node-mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/var/task/node-mapnik/lib/binding"
gyp ERR! cwd /var/task/node-mapnik
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/lib64/node-v4.3.x/bin/node /usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --ENABLE_GLIBC_WORKAROUND=true --enable_sse=true --loglevel=error --clang --module=/var/task/node-mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/var/task/node-mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/task/node-mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.10.0-38-generic
node-pre-gyp ERR! command "/usr/local/lib64/node-v4.3.x/bin/node" "/var/task/node-mapnik/node_modules/.bin/node-pre-gyp" "configure" "build" "--ENABLE_GLIBC_WORKAROUND=true" "--enable_sse=true" "--loglevel=error" "--clang"
node-pre-gyp ERR! cwd /var/task/node-mapnik
node-pre-gyp ERR! node -v v4.3.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/lib64/node-v4.3.x/bin/node /usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --ENABLE_GLIBC_WORKAROUND=true --enable_sse=true --loglevel=error --clang --module=/var/task/node-mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/var/task/node-mapnik/lib/binding' (1)
make[1]: *** [release_base] Error 1
make[1]: Leaving directory `/var/task/node-mapnik'
make: *** [release] Error 2
bash-4.2# git branch --list
  master
* v3.0.x
bash-4.2# git pull origin
Already up-to-date.
bash-4.2# git update
git: 'update' is not a git command. See 'git --help'.

The most similar command is
	update-ref
bash-4.2# git pull origin/v3.0.x
fatal: 'origin/v3.0.x' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
bash-4.2# git pull origin v3.0.x
From https://github.com/mapnik/node-mapnik
 * branch              v3.0.x     -> FETCH_HEAD
Already up-to-date.
bash-4.2# make
CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" PATH="./mason_packages/.link/bin/:/usr/local/lib64/node-v4.3.x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" make release_base
make[1]: Entering directory `/var/task/node-mapnik'
NOTICE: to build from source you need mapnik >= v3.0.20 
Looking for mapnik-config on your PATH...
mapnik-config -v
3.1.0
V=1 CXXFLAGS="-fno-omit-frame-pointer -g" ./node_modules/.bin/node-pre-gyp configure build --ENABLE_GLIBC_WORKAROUND=true --enable_sse=true --loglevel=error --clang
make[2]: Entering directory `/var/task/node-mapnik/build'
  /usr/bin/c++ '-DNODE_GYP_MODULE_NAME=mapnik' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DMAPNIK_GIT_REVISION="v3.0.12-750-ga2f5969"' '-DSSE_MATH' '-DBUILDING_NODE_EXTENSION' '-DNDEBUG' -I/root/.node-gyp/4.3.2/include/node -I/root/.node-gyp/4.3.2/src -I/root/.node-gyp/4.3.2/deps/uv/include -I/root/.node-gyp/4.3.2/deps/v8/include -I../mason_packages/.link/include -I../mason_packages/.link/include/freetype2 -I../mason_packages/.link/include/cairo -I../src -I../node_modules/nan -I../deps/geometry/include -I../deps/wagyu/include -I../node_modules/protozero/include -I../node_modules/mapnik-vector-tile/src  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -std=c++11 -std=c++11 -I/var/task/node-mapnik/mason_packages/.link/include -I/var/task/node-mapnik/mason_packages/.link/include/mapnik/agg -I/var/task/node-mapnik/mason_packages/.link/include/mapnik -I./mason_packages/.link/include -I./mason_packages/.link/include/freetype2 -I./mason_packages/.link/include/libpng16 -I./mason_packages/linux-x86_64/libgdal/2.1.3/include -I./mason_packages/.link/include/cairo -I./mason_packages/.link/include/pixman-1 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DMAPNIK_NO_ATEXIT -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DSVG_RENDERER -std=c++14 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -O3 -MMD -MF ./Release/.deps/Release/obj.target/mapnik/src/mapnik_logger.o.d.raw -fno-omit-frame-pointer -g -c -o Release/obj.target/mapnik/src/mapnik_logger.o ../src/mapnik_logger.cpp
c++: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [Release/obj.target/mapnik/src/mapnik_logger.o] Error 1
make[2]: Leaving directory `/var/task/node-mapnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/local/lib64/node-v4.3.x/bin/node" "/usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--ENABLE_GLIBC_WORKAROUND=true" "--enable_sse=true" "--loglevel=error" "--clang" "--module=/var/task/node-mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/var/task/node-mapnik/lib/binding"
gyp ERR! cwd /var/task/node-mapnik
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/lib64/node-v4.3.x/bin/node /usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --ENABLE_GLIBC_WORKAROUND=true --enable_sse=true --loglevel=error --clang --module=/var/task/node-mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/var/task/node-mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/task/node-mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.10.0-38-generic
node-pre-gyp ERR! command "/usr/local/lib64/node-v4.3.x/bin/node" "/var/task/node-mapnik/node_modules/.bin/node-pre-gyp" "configure" "build" "--ENABLE_GLIBC_WORKAROUND=true" "--enable_sse=true" "--loglevel=error" "--clang"
node-pre-gyp ERR! cwd /var/task/node-mapnik
node-pre-gyp ERR! node -v v4.3.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/lib64/node-v4.3.x/bin/node /usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --ENABLE_GLIBC_WORKAROUND=true --enable_sse=true --loglevel=error --clang --module=/var/task/node-mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/var/task/node-mapnik/lib/binding' (1)
make[1]: *** [release_base] Error 1
make[1]: Leaving directory `/var/task/node-mapnik'
make: *** [release] Error 2
bash-4.2# 
`

**Comment by springmeyer** [comment]
See #863, please discuss there.
