### ISSUE TITLE
3.7.1 & 3.7.2 changelog?

### ISSUE THREAD

**Issue by mapsam** [mapnik/node-mapnik#876]
It appears 3.7.1 and 3.7.2 are released on NPM, but I can't seem to find any history about the changes/releases. Can we get these documented in the CHANGELOG?

cc @flippmoke @artemp

**Comment by mapsam** [comment]
Ah, found the 3.7.2 commit here: https://github.com/mapnik/node-mapnik/pull/869/files

@GretaCB would you mind updating the CHANGELOG when you have a chance?

**Comment by Algunenano** [comment]
Those releases were made from the 3.0.x branch. 3.7.1 has a [changelog](https://github.com/mapnik/node-mapnik/blob/v3.0.x/CHANGELOG.md#371) but 3.7.2 doesn't.

**Comment by mapsam** [comment]
Thanks @Algunenano - will be good to get these in sync, since `3.0.x` branch naming scheme doesn't match `3.7.x`.
