### ISSUE TITLE
move semantics for the buffer inside mapnik.VectorTile

### ISSUE THREAD

**Issue by springmeyer** [mapnik/node-mapnik#881]
The `getData()` call copies the entire, uncompressed, vector tile buffer. This can be expensive. 

We should add support for a `takeData()` or `release()` function which returns a node.Buffer which owns the underlying memory (the original `mapnik.VectorTile` object would then be empty).

This will allow for much more efficient passing of data to other node C++ addons like https://github.com/mapbox/vtcomposite and https://github.com/mapbox/vtquery.

/cc @mapbox/core-tech @flippmoke 

refs https://github.com/mapbox/node-cpp-skel/issues/69 and https://github.com/mapbox/node-cpp-skel/issues/67

**Comment by springmeyer** [comment]
I was assuming that they buffer type was stored on the node-mapnik object and would be easy to change into a `std::unique_ptr<std::string>` to allow passing ownership around. But, turns out the underlying type of the buffer is a `std::string` deep inside `mapnik-vector-tile`. I'm therefore reluctant to change this given the greater time expensive to modifying both libraries. So, I'm punting on this and will achieve the performance needs I have by avoiding node-mapnik usage over at  https://github.com/mapbox/tilelive-vector/pull/155

**Comment by flippmoke** [comment]
Took at shot at this with #889 and https://github.com/mapbox/mapnik-vector-tile/pull/285

**Comment by flippmoke** [comment]
Released in `4.0.1`
