### ISSUE TITLE
403 Permission Denied when installing on Ubuntu 18

### ISSUE THREAD

**Issue by ISNIT0** [mapnik/node-mapnik#888]
```
> npm i mapnik
```
Output:
```
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason

> mapnik@3.7.2 install /home/user/weather-mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-linux-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.5.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-linux-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.5.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/user/weather-mapnik/node_modules/mapnik/build'
make: Entering directory '/home/user/weather-mapnik/node_modules/mapnik/build'
...
```

It seems the url (https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-linux-x64-Release.tar.gz) is not available to the public?

Happy to provide more info if necessary.

**Comment by Algunenano** [comment]
Looks like you are using node 10 but node-mapnik 3.7.2 doesn't have support for it. You could either use a previous node release, the dev 3.7.3-svg1 release or build directly from github (branch v3.0.x for Mapnik 3.0.X or master for current Mapnik master).

**Comment by flippmoke** [comment]
I believe there will be node 10 prebuilt binaries in the upcoming new versions of node-mapnik, but binaries have not been built for 10 yet.

**Comment by ISNIT0** [comment]
We may be thinking of different node versions here(?), but:
`node --version` outputs `v8.4.0` which is the latest stable release of node

**Comment by springmeyer** [comment]
mapnik@v4.0.0 is now published with node v8 and v10 support
