### ISSUE TITLE
Question on mapbox-node-binary.s3.amazonaws.com/mapnik

### ISSUE THREAD

**Issue by pausto** [mapnik/node-mapnik#891]
Is it possible to lay out the index of the contents of this folder to understand for which version there are compiled files, for example,
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.2/Release/node-v48-win32-x64.tar.gz
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.2/Release/node-v48-win32-x64.tar.gz
Where can I see what files are on this server? And knowing them, put the right version of mapnik

**Comment by Algunenano** [comment]
Windows prebuilt binaries are no longer supported (https://github.com/mapnik/node-mapnik/issues/848) but compilation should still work.

The last published binaries were for [3.6.2](https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1882) but I see they were uploaded with a different format (`https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.2/node-v48-win32-x64-Releasev140.tar.gz`)

3.6.1 is in https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.1/node-v48-win32-x64-Release.tar.gz so there might be a difference in the url were the binaries were published and how they are looked for. I'd investigate that.

**Comment by pausto** [comment]
Thank you
