### ISSUE TITLE
GeoJSON to MVT: line deleted when bufferSize>0

### ISSUE THREAD

**Issue by fredericbonifas** [mapnik/node-mapnik#892]
I'm experiencing a problem when converting a GeoJSON of lines to MVT. Some lines are removed during the conversion when the `bufferSize` option is greater than 0.
The different files are attached to this issue: [geojson2mvt.zip](https://github.com/mapnik/node-mapnik/files/2189004/geojson2mvt.zip)

I am using node-mapnik `v4.0.0` and mapnik-vector-tile `v2.1.1`

My source GeoJSON looks like this, represented with the tile boundary (`21/1092278/729478`):
![source](https://user-images.githubusercontent.com/1278216/42640283-4392e42e-85f2-11e8-9c30-674450c15b45.png)

I convert the GeoJSON to MVT using the following script. The `toGeoJSON` method is not faulty here as this problem occurs when serving directly the vector tile.
``` javascript
var mapnik = require('mapnik')
var path = require('path')
var fs = require('fs')

mapnik.register_datasource(path.join(mapnik.settings.paths.input_plugins, 'geojson.input'));

fs.readFile('source.geojson', function (err, data) {
  var vtile = new mapnik.VectorTile(21, 1092278, 729478);
  vtile.addGeoJSON(JSON.stringify(JSON.parse(data)), 'VectorTile')
  vtile.toGeoJSON('VectorTile', function(err, geojson) {
    if (err) throw err;
    fs.writeFile("mvt_buffer128.geojson", geojson, function(err) {
      if (err) throw err;
    })
  });
});
```
I get this GeoJSON, please note the missing line on the left:
![buffer128](https://user-images.githubusercontent.com/1278216/42640584-eaef63b4-85f2-11e8-9c0d-90afd6f57b97.png)

When setting the option `vtile.bufferSize=0`, the line is not missing:
![buffer0](https://user-images.githubusercontent.com/1278216/42640597-f12e940c-85f2-11e8-9558-901f876ac1ed.png)

Do you know where this problem can come from and how to get both a buffer and all the lines?
Thanks

**Comment by flippmoke** [comment]
@fredericbonifas thanks for the report, digging into this right now

**Comment by flippmoke** [comment]
This should be fixed in master now. Will work on getting a new version of node-mapnik released soon.

**Comment by fredericbonifas** [comment]
Thanks a lot for fixing this bug so fast @flippmoke !

**Comment by flippmoke** [comment]
`4.0.1` is released with this fix.

**Comment by fredericbonifas** [comment]
I confirm that it solved my problem.
