### ISSUE TITLE
doc example: vector tile z x y order

### ISSUE THREAD

**Issue by arbrisseaux** [mapnik/node-mapnik#896]
In the vector tile doc, http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile

Given the VectorTile constructor: VectorTile(z, x, y):

`var vt = new mapnik.VectorTile(9,112,195);`

Is this line should be
`console.log(vt.z, vt.x, vt.y); // 9, 112, 195`
instead of :
`console.log(vt.x, vt.y, vt.z); // 9, 112, 195`
?

**Comment by talaj** [comment]
Yes, you can fix here:
https://github.com/mapnik/node-mapnik/blob/e9d355fb054e43a450ca1a6ff4e349548c75545f/src/mapnik_vector_tile.cpp#L250

**Comment by springmeyer** [comment]
closed by #897 with this caveat: https://github.com/mapnik/node-mapnik/pull/897#issuecomment-431636836
