### ISSUE TITLE
Whether the latest node-mapnik is supported mapnik3.0.21 ??

### ISSUE THREAD

**Issue by yh371174229** [mapnik/node-mapnik#902]
I have install mapnik 3.0.21,when i directly use  "npm install mapnik" ,it's failed.
Now I want to install node-mapnik from source code, I see this :"The master branch of node-mapnik is not compatible with 3.0.x series of Mapnik. To build again Mapnik 3.0.x, use v3.0.x branch.",but i don't know whether the latest mapnik is supported  by v3.0.x branch.
Any help will appreciated！

**Comment by talaj** [comment]
Master branch of node-mapnik should work with master branch of Mapnik. The master branch is development branch, v3.0.x branch is release branch currently.
