### ISSUE TITLE
is this not support node v11?

### ISSUE THREAD

**Issue by petitlen** [mapnik/node-mapnik#916]
is this not support node v11?
install error as following:
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by rheh** [comment]
Good question.  We are on node v8 LTS which will be marked end-of-line December 2019.  node-mapnik currently works with v8, is there a plan to support 10.x  as this is the current LTS? And of course 11?

**Comment by Algunenano** [comment]
The project is currently being built for node 4, 6, 7, 8, 9, 10 and [12](https://github.com/mapnik/node-mapnik/blob/d323d5c9959430546256e83da4265dde5a890737/.travis.yml#L83) so it should be compatible with node 11 too, but there isn't a published prebuilt for it.

**Comment by rheh** [comment]
Thanks for the reply.  Does that mean when npm installing you need some pre-requisites for it to kick off a build?

**Comment by springmeyer** [comment]
node v11 is supported - even node v14 now. See the latest release: v4.5.1
