### ISSUE TITLE
Index file not working

### ISSUE THREAD

**Issue by sommerluk** [mapnik/node-mapnik#917]
When using Kosmtik + node-map 4.2.1 and rendering a style that has .index files for its shape files, these shape files do not render. No error message. When I delete the .index files, everything works fine. If I re-create them using shapeindex, again no rendering of the shape files.

Note that on the same computer, using python-mapnik, everything works fine for the same index files.

**Comment by springmeyer** [comment]
I think you have a mismatch between the mapnik version used inside node-mapnik and the mapnik version used inside shapeindex. I think it was https://github.com/mapnik/mapnik/pull/3742 that changed the index format such that it is not compatible across mapnik versions. So, this can be resolve by ensuring you have the same mapnik version used by node-mapnik as python-mapnik.

**Comment by sommerluk** [comment]
Okay. So probably the Mapnik package version of the Linux distribution I am using missmatches with the node-mapnik version used by kosmtik.

Thanks for explication!

Closing.
