### ISSUE TITLE
Pre-built binaries not found for mapnik@4.2.1 and node@10.15.3 

### ISSUE THREAD

**Issue by clarkx86** [mapnik/node-mapnik#918]
Hello :-)!
I was developing an application on Ubuntu with node 8 and just now tried to `npm install` on Windows 10 using node 10, and I'm getting thrown the following error:
```
> mapnik@4.2.1 install C:\Users\clark\Desktop\<Project>\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.2.1/node-v64-win32-x64-Release.tar.gz
node-pre-gyp WARN Pre-built binaries not found for mapnik@4.2.1 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.2.1 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gyp ERR! configure error
```

Where can I aquiere the binaries for node 10? I just tried, and I get pretty much the same error for node 8...

I hope you have an amazing day and thank you in advance,
clarkx86 :-)

**Comment by Algunenano** [comment]
Windows prebuilts are no longer [maintained](https://github.com/mapnik/node-mapnik/issues/848). You can either use the last release built for Windows (`3.6.2`) or build from [source](https://github.com/mapnik/node-mapnik#source-build).

**Comment by clarkx86** [comment]
Oh, okay! Could've figured that myself, I guess :D! Thank you very much!
