### ISSUE TITLE
N-API vs NAN

### ISSUE THREAD

**Issue by Algunenano** [mapnik/node-mapnik#921]
This isn't an issue, but I'm not sure where would be the right place to ask? Feel free to close it if it's inadequate.

I have a patch updating node-mapnik to current NAN with support for node 11 and 12, and addressing all warnings about deprecations, but I was wondering if there are any plans about n-api which AFAIK would make the patch unnecessary.

Since the patch was created over our v3.0.0x I can't simply cherry pick the changes, but it should be pretty straightforward to spot and address the differences and open a PR. Should I?

**Comment by flippmoke** [comment]
I know that @springmeyer has been thinking about n-api support, but I am not sure how long it would take to get that setup in node-mapnik. My guess would be that we should just address our issues with NAN as you probably already did in your patch for now.

**Comment by springmeyer** [comment]
HI @Algunenano - thanks for asking. At this time I don't know of anyone that has attempted an N-API port, but it would surely be a good thing to move to N-API. In the meantime, catching up with NAN seems reasonable. If anyone has interest or time to port to N-API, feel free to comment on this ticket.

**Comment by Algunenano** [comment]
Ok, thanks both for the information.

I've created a PR which updates Nan its latest release and addresses all errors and warnings under node 12.

**Comment by springmeyer** [comment]
It seems like its time to port to N-API, given the node-addon-api is mature and most modules I see are moving to it. This will be a big lift however, probably good to have multiple people collaborate on it. I think @artemp may have some time in the coming month to work on this. Anyone else able to help or review?

**Comment by Algunenano** [comment]
I don't think I'm going to have time in the short term to help, but I might be able to get some time to review or test things out (or get someone else involved in it).

**Comment by springmeyer** [comment]
@artemp did this. It was a MASSIVE effort - thank you @artemp 👏 - v4.5.1 therefore now works on node v14 and beyond.

**Comment by Algunenano** [comment]
Thanks a lot @artemp. Really appreciate it.
