### ISSUE TITLE
Drop support for Node versions < 10

### ISSUE THREAD

**Issue by jseppi** [mapnik/node-mapnik#930]
Node v4's end-of-life was 2018-04-30 (ref https://github.com/nodejs/Release#end-of-life-releases).

Can we drop support for it? cc @springmeyer

**Comment by springmeyer** [comment]
👍 to removing from .travis.yml and making mention in the readme (+ incrementing at least minor version)

**Comment by jseppi** [comment]
@springmeyer As of the start of this year, Node 8 has also been marked as end-of-life. Can we drop support for all versions < 10 at this point?

**Comment by artemp** [comment]
@springmeyer - while we at it, how about dropping more `end-of-life` versions ?
