### ISSUE TITLE
how to print sql query log

### ISSUE THREAD

**Issue by steeeeps** [mapnik/node-mapnik#932]
I am using  node-mapnik@4.3.1 to serve vector tile , and I want to know how to print mapnik  sql query log when mapnik query data from postgis.

thanks

**Comment by lightmare** [comment]
afaik the only way currently is to enable query logging in postgresql server
https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT

**Comment by steeeeps** [comment]
@lightmare  thank you so much
