### ISSUE TITLE
Upgrade to Node.js ≥ 12

### ISSUE THREAD

**Issue by guimard** [mapnik/node-mapnik#941]
Hi,

I tried to upgrade node-mapnik to be used with Node.js ≥ 12. Here is my work, 2 errors remaining.

Cheers,
Xavier

[node-12-partial-patch.zip](https://github.com/mapnik/node-mapnik/files/4113515/node-12-partial-patch.zip)

**Comment by artemp** [comment]
@guimard - thanks for contributing! The patch doesn't apply cleanly, could you fork and create a branch with your changes and post a link, please ? Cheers.

**Comment by springmeyer** [comment]
node-mapnik v4.5.1 should support node v12 without problems. Please create new issues if you encounter any problems.
