### ISSUE TITLE
Please add binary for arm64

### ISSUE THREAD

**Issue by gaoq0707** [mapnik/node-mapnik#945]
I'm trying to use this module on some arm64 devices and our build times are really long because there is no prebuilt binary for us.

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v57-linux-arm64-Release.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
```

I'm using the new LTS version of node.

**Comment by Fi1osof** [comment]
Got same error on ubuntu-18 node-10.
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-linux-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.20.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

**Comment by kueda** [comment]
Binaries for M1 Macs would also be much appreciated. I'm currently getting 403 errors when trying to retrieve one for mapnik@4.5.9 and node@16.13.2:

```
npm ERR! path /Users/kueda/projects/elasticmaps/node_modules/mapnik
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
npm ERR!   CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
npm ERR! Failed to execute '/Users/kueda/.nvm/versions/node/v16.13.2/bin/node /Users/kueda/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/kueda/projects/elasticmaps/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/kueda/projects/elasticmaps/node_modules/mapnik/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! node-pre-gyp info using node@16.13.2 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/kueda/projects/elasticmaps/node_modules/mapnik/lib/binding/mapnik.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/darwin-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.5.9 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/darwin-arm64.tar.gz 
```

When it tries to build from source I'm having other problems, but they're probably separate issues.

**Comment by pascaloliv** [comment]
Hi !
Yes, binaries for M1 Macs would be great ! 
I also have the same 403 issue at installation and the node-gyp compilation as fallback is failing too.
Do you guys have any workaround ? Thanks :+1:

```
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for mapnik@4.5.9 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/mapnik/v4.5.9/Release/darwin-arm64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.14.2 | darwin | arm64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.14.2 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
```

**Comment by artemp** [comment]
@pm0u - arm64 binaries are planned for next `node-mapnik` release. Meanwhile, you can build mapnik/node-mapnik on darwin-arm64 from source.

**Comment by pm0u** [comment]
That's great news, thank you for the update!

I know that is possible, but I am trying to use this as a dependency in a node project that will be edge deployed and tbh making that work would be over my head.

so I will wait patiently 🙏 

Thank you for all your work on this awesome library.

**Comment by JaylanChen** [comment]
> @pm0u - arm64 binaries are planned for the next `node-mapnik` release. Meanwhile, you can build `mapnik/node-mapnik` on darwin-arm64 from source.

Are there any plans to release `linux-arm64` binaries ?

**Comment by artemp** [comment]
> Are there any plans to release `linux-arm64` binaries ?

You could try latest dev package which has `linux-arm64` binaries  - 

npm install @mapnik/mapnik@4.6.5-experimental 

HTH

**Comment by artemp** [comment]
Latest packages support arm64 on linux and darwin platforms.

**Comment by JaylanChen** [comment]
> @pm0u @JaylanChen
> 
> > Are there any plans to release `linux-arm64` binaries ?
> 
> You could try latest dev package which has `linux-arm64` binaries -
> 
> `npm install @mapnik/mapnik@4.6.5-experimental`
> 
> HTH

`npm install @mapnik/mapnik@4.6.5-experimental`

```
npm error code 1
npm error path /app-test/node_modules/@mapnik/mapnik
npm error command failed
npm error command sh -c ./scripts/preinstall.sh
npm error MODULE_PATH:/app-test/node_modules/@mapnik/mapnik/prebuilds/linux-arm64
npm error MAPNIK_CORE_PATH:/app-test//node_modules/@mapnik/core-linux-arm64
npm error  Missing Mapnik Core package - @mapnik/core-linux-arm64-4.0.2-experimental
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-16T03_38_32_171Z-debug-0.log
```

**Comment by pm0u** [comment]
Is this expected to be available from npm registry or am I missing some setup step?

```
npm install @mapnik/mapnik@4.6.5-experimental


npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mapnik%2fmapnik - Not found
npm ERR! 404
npm ERR! 404  '@mapnik/mapnik@4.6.5-experimental' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by artemp** [comment]
> Is this expected to be available from npm registry or am I missing some setup step?

Yes ^ 

`@mapnik/mapnik` packages are on **github** NPM registry. Consult documentation below - 

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry
https://github.com/mapnik/node-mapnik/pkgs/npm/mapnik

**Comment by JaylanChen** [comment]
> @JaylanChen - Could you try running
> 
> ```shell
> npm install --foreground-script --verbose @mapnik/mapnik@4.6.5-experimental
> ```
> 
> and post stderr here together with some info about your setup, pls.

root@02162b3f66ea:/test# npm install --foreground-script --verbose @mapnik/mapnik@4.6.5-experimental
npm verbose cli /usr/bin/node /usr/bin/npm
npm info using npm@10.7.0
npm info using node@v18.20.4
npm verbose title npm install @mapnik/mapnik@4.6.5-experimental
npm verbose argv "install" "--foreground-script" "--loglevel" "verbose" "@mapnik/mapnik@4.6.5-experimental"
npm verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-10-17T08_04_09_886Z-
npm verbose logfile /root/.npm/_logs/2024-10-17T08_04_09_886Z-debug-0.log
npm http fetch GET 200 https://npm.pkg.github.com/@mapnik%2fmapnik 9786ms (cache updated)
npm http fetch GET 200 https://registry.npmmirror.com/node-addon-api 140ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/prebuildify 160ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/node-gyp-build 186ms (cache revalidated)
npm http fetch GET 403 https://npm.pkg.github.com/@mapnik%2fcore-linux-arm64 399ms (cache skip)
npm http fetch GET 200 https://npm.pkg.github.com/@mapnik%2fcore-darwin-x64 696ms (cache updated)
npm http fetch GET 200 https://npm.pkg.github.com/@mapnik%2fcore-darwin-arm64 1186ms (cache updated)
npm http fetch GET 200 https://npm.pkg.github.com/@mapnik%2fcore-linux-x64 2095ms (cache updated)
npm http fetch GET 200 https://registry.npmmirror.com/minimist 52ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/mkdirp-classic 74ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/node-abi 83ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/pump 131ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/tar-fs 138ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/npm-run-path 207ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/end-of-stream 50ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/once 51ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/tar-stream 78ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/chownr 86ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/path-key 110ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/semver 169ms (cache updated)
npm http fetch GET 200 https://registry.npmmirror.com/wrappy 36ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/readable-stream 32ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/inherits 43ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/fs-constants 87ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/bl 90ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/util-deprecate 47ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/string_decoder 49ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/buffer 84ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/base64-js 74ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/ieee754 80ms (cache revalidated)
npm http fetch GET 200 https://registry.npmmirror.com/safe-buffer 38ms (cache revalidated)
npm verbose reify failed optional dependency /test/node_modules/@mapnik/core-linux-x64
npm verbose reify failed optional dependency /test/node_modules/@mapnik/core-darwin-x64
npm verbose reify failed optional dependency /test/node_modules/@mapnik/core-darwin-arm64
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 34ms
npm http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 51ms
npm verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick - [NOT_IMPLEMENTED] /-/npm/v1/security/* not implemented yet
npm verbose audit error     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verbose audit error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verbose audit error     at async [getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:336:21)
npm verbose audit error     at async AuditReport.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
npm verbose audit error   headers: [Object: null prototype] {
npm verbose audit error     server: [ 'Tengine' ],
npm verbose audit error     date: [ 'Thu, 17 Oct 2024 08:04:23 GMT' ],
npm verbose audit error     'content-type': [ 'application/json' ],
npm verbose audit error     'transfer-encoding': [ 'chunked' ],
npm verbose audit error     connection: [ 'keep-alive' ],
npm verbose audit error     'strict-transport-security': [ 'max-age=5184000' ],
npm verbose audit error     via: [ 'kunlun5.cn2490[,404666]' ],
npm verbose audit error     'timing-allow-origin': [ '*' ],
npm verbose audit error     eagleid: [ '249ee01917291522631698885e' ],
npm verbose audit error     'x-fetch-attempts': [ '1' ]
npm verbose audit error   },
npm verbose audit error   statusCode: 404,
npm verbose audit error   code: 'E404',
npm verbose audit error   method: 'POST',
npm verbose audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
npm verbose audit error   body: {
npm verbose audit error     error: '[NOT_IMPLEMENTED] /-/npm/v1/security/* not implemented yet'
npm verbose audit error   },
npm verbose audit error   pkgid: undefined
npm verbose audit error }
npm http fetch GET 200 https://pkg-npm.githubusercontent.com/npmregistryv2prod/blobs/318055/mapnik/4.6.5-experimental/***?se=2024-10-17T08%3A09%3A23Z&sig=UVvjDwp8n8QbycuM6VfAca3G5%2F7fgGw8%2FEIqRcW2loE%3D&sp=r&spr=https&sr=b&sv=2019-12-12 310601ms (cache miss)
npm info run @mapnik/mapnik@4.6.5-experimental preinstall node_modules/@mapnik/mapnik ./scripts/preinstall.sh

> @mapnik/mapnik@4.6.5-experimental preinstall
> ./scripts/preinstall.sh

MODULE_PATH:/test/node_modules/@mapnik/mapnik/prebuilds/linux-arm64
MAPNIK_CORE_PATH:/test//node_modules/@mapnik/core-linux-arm64
 Missing Mapnik Core package - @mapnik/core-linux-arm64-4.0.2-experimental
npm info run @mapnik/mapnik@4.6.5-experimental preinstall { code: 1, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verbose stack     at ChildProcess.emit (node:events:517:28)
npm verbose stack     at maybeClose (node:internal/child_process:1098:16)
npm verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm verbose pkgid @mapnik/mapnik@4.6.5-experimental
npm verbose cwd /test
npm verbose Linux 4.19.90-2309.3.0.0218.kb11.ky3_4.aarch64
npm verbose node v18.20.4
npm verbose npm  v10.7.0
npm error code 1
npm error path /test/node_modules/@mapnik/mapnik
npm error command failed
npm error command sh -c ./scripts/preinstall.sh
npm verbose exit 1
npm verbose code 1

npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-17T08_04_09_886Z-debug-0.log

[2024-10-17T08_04_09_886Z-debug-0.log](https://github.com/user-attachments/files/17408805/2024-10-17T08_04_09_886Z-debug-0.log)

**Comment by artemp** [comment]
@JaylanChen - Thanks for testing. My bad, `@mapnik/core-linux-arm64@4.0.2-experimental ` had a `private` visibility. 
I changed it to `public`, please give a try and let me know, cheers.

**Comment by pm0u** [comment]
Didn't try to use it, but install seems to have succeeded

```
npm install @mapnik/mapnik@4.6.5-experimental



added 28 packages, and audited 29 packages in 6s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
tree -L 2 node_modules
node_modules
├── @mapnik
│   ├── core-darwin-arm64
│   └── mapnik
├── base64-js
│   ├── LICENSE
│   ├── README.md
│   ├── base64js.min.js
│   ├── index.d.ts
│   ├── index.js
│   └── package.json
├── bl
│   ├── BufferList.js
│   ├── LICENSE.md
│   ├── README.md
│   ├── bl.js
│   ├── package.json
│   └── test
├── buffer
│   ├── AUTHORS.md
│   ├── LICENSE
│   ├── README.md
│   ├── index.d.ts
│   ├── index.js
│   └── package.json
├── chownr
│   ├── LICENSE
│   ├── README.md
│   ├── chownr.js
│   └── package.json
├── end-of-stream
│   ├── LICENSE
│   ├── README.md
│   ├── index.js
│   └── package.json
├── fs-constants
│   ├── LICENSE
│   ├── README.md
│   ├── browser.js
│   ├── index.js
│   └── package.json
├── ieee754
│   ├── LICENSE
│   ├── README.md
│   ├── index.d.ts
│   ├── index.js
│   └── package.json
├── inherits
│   ├── LICENSE
│   ├── README.md
│   ├── inherits.js
│   ├── inherits_browser.js
│   └── package.json
├── minimist
│   ├── CHANGELOG.md
│   ├── LICENSE
│   ├── README.md
│   ├── example
│   ├── index.js
│   ├── package.json
│   └── test
├── mkdirp-classic
│   ├── LICENSE
│   ├── README.md
│   ├── index.js
│   └── package.json
├── node-abi
│   ├── LICENSE
│   ├── README.md
│   ├── abi_registry.json
│   ├── index.js
│   └── package.json
├── node-addon-api
│   ├── LICENSE.md
│   ├── README.md
│   ├── common.gypi
│   ├── except.gypi
│   ├── index.js
│   ├── napi-inl.deprecated.h
│   ├── napi-inl.h
│   ├── napi.h
│   ├── node_addon_api.gyp
│   ├── node_api.gyp
│   ├── noexcept.gypi
│   ├── nothing.c
│   ├── package-support.json
│   ├── package.json
│   └── tools
├── node-gyp-build
│   ├── LICENSE
│   ├── README.md
│   ├── SECURITY.md
│   ├── bin.js
│   ├── build-test.js
│   ├── index.js
│   ├── node-gyp-build.js
│   ├── optional.js
│   └── package.json
├── npm-run-path
│   ├── index.d.ts
│   ├── index.js
│   ├── license
│   ├── package.json
│   └── readme.md
├── once
│   ├── LICENSE
│   ├── README.md
│   ├── once.js
│   └── package.json
├── path-key
│   ├── index.d.ts
│   ├── index.js
│   ├── license
│   ├── package.json
│   └── readme.md
├── prebuildify
│   ├── LICENSE
│   ├── README.md
│   ├── bin.js
│   ├── index.js
│   └── package.json
├── pump
│   ├── LICENSE
│   ├── README.md
│   ├── SECURITY.md
│   ├── index.js
│   ├── package.json
│   ├── test-browser.js
│   └── test-node.js
├── readable-stream
│   ├── CONTRIBUTING.md
│   ├── GOVERNANCE.md
│   ├── LICENSE
│   ├── README.md
│   ├── errors-browser.js
│   ├── errors.js
│   ├── experimentalWarning.js
│   ├── lib
│   ├── package.json
│   ├── readable-browser.js
│   └── readable.js
├── safe-buffer
│   ├── LICENSE
│   ├── README.md
│   ├── index.d.ts
│   ├── index.js
│   └── package.json
├── semver
│   ├── LICENSE
│   ├── README.md
│   ├── bin
│   ├── classes
│   ├── functions
│   ├── index.js
│   ├── internal
│   ├── package.json
│   ├── preload.js
│   ├── range.bnf
│   └── ranges
├── string_decoder
│   ├── LICENSE
│   ├── README.md
│   ├── lib
│   └── package.json
├── tar-fs
│   ├── LICENSE
│   ├── README.md
│   ├── index.js
│   ├── package.json
│   └── test
├── tar-stream
│   ├── LICENSE
│   ├── README.md
│   ├── extract.js
│   ├── headers.js
│   ├── index.js
│   ├── pack.js
│   ├── package.json
│   └── sandbox.js
├── util-deprecate
│   ├── History.md
│   ├── LICENSE
│   ├── README.md
│   ├── browser.js
│   ├── node.js
│   └── package.json
└── wrappy
    ├── LICENSE
    ├── README.md
    ├── package.json
    └── wrappy.js

42 directories, 149 files

```

**Comment by JaylanChen** [comment]
> @JaylanChen - Thanks for testing. My bad, `@mapnik/core-linux-arm64@4.0.2-experimental ` had a `private` visibility. I changed it to `public`, please run `npm install` again and let me know, cheers.
> 
> PS. You might need to clear your cache or use temp cache (`--cache /tmp/empty-cache`) not sure

I attempted linux-64 and linux-arm64, and both were installed successfully. A simple test has been conducted and it can operate normally.

Thank you so much.

map4326.xml
```xml
<Map srs="epsg:4326">
  <Style name="My Style">
    <Rule>
      <PolygonSymbolizer fill="#f2eff9" />
      <LineSymbolizer stroke="rgb(50%,50%,50%)" stroke-width="0.1" />
    </Rule>
  </Style>
  <Layer name="world" srs="epsg:4326">
    <StyleName>My Style</StyleName>
  </Layer>
</Map>
```
test code
```javascript
const mapnik = require('@mapnik/mapnik');

const map = new mapnik.Map(256, 256);

map.load('./map4326.xml', function (err, _map) {
  if (err) throw err;
  _map.zoomToBox([112.5, 22.5, 118.125, 28.125]);
  console.log(`\r\n${_map.srs}\r\n`, _map.scale(), _map.scaleDenominator());
});
```
