### ISSUE TITLE
quality in Mapnik.blend no longer defaults correctly

### ISSUE THREAD

**Issue by calvinmetcalf** [mapnik/node-mapnik#957]
passing undefined or null as the quality to Mapnik.Blend does not have the same effect as omitting the quality parameter from the options object. This looks to be a regression as that was not previously the case.  Probably related to https://github.com/mapnik/node-mapnik/commit/80848951d5fc2ad46e39717fbf66208ffd5b5216#diff-ca958ba4607badc60fbfe6b08ce05c4fL528 which is no longer checking if the value is empty.

**Comment by springmeyer** [comment]
Thanks for the report @calvinmetcalf. /cc @artemp

**Comment by artemp** [comment]
@calvinmetcalf - https://github.com/mapnik/node-mapnik/commit/7d318520329a5e51f0921954f0399947fbe2b342 fixes setting default `quality` parameter for webp format. Is this what you were experiencing ?  Could you post minimal JS code manifesting this issue for you?

**Comment by artemp** [comment]
landed in [`v4.5.3`](https://github.com/mapnik/node-mapnik/tree/v4.5.3)
