### ISSUE TITLE
Can't install on Ubuntu 18.04

### ISSUE THREAD

**Issue by memarv** [mapnik/node-mapnik#958]
`npm install mapnik`

```
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v57-linux-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@8.15.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
```

https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/ 
There is only binary file for Windows. Last modified time is 2020-09-11.

**Comment by gravitystorm** [comment]
The pre-built binary link works for me. I've just successfully installed node-mapnik@3.7.2 on a VM running node 8. Addtionally, the link to the s3 download works for me. Could you try it again?

**Comment by springmeyer** [comment]
Agree with @gravitystorm - please try again. Ideally with the latest releases and create a new ticket if you are still having issue.
