### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by SkyLimited** [mapnik/node-mapnik#962]
Hi! I'm trying to install mapnik for node js witch command like

`npm install -g mapnik@1.x`

i'm getting error
`Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js rebuild --name=mapnik --configuration=Release --module_name=mapnik --version=1.4.17 --major=1 --minor=4 --patch=17 --runtime=node --node_abi=node-v48 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/lib/node_modules/mapnik/lib/binding/node-v48-linux-x64 --module=/usr/lib/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik.node --remote_path=./mapnik/v1.4.17/ --package_name=node-v48-linux-x64.tar.gz --staged_tarball=build/stage/mapnik/v1.4.17/node-v48-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/node-v48-linux-x64.tar.gz' `

And the problem as far as i know is with S3 service returning something like
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BXETFT1Y1Q6W4MCJ</RequestId>
<HostId>7s1Oc3OID49R9T6qZXX67KSZIcl4xjTUgiCprp5ebLwtG+bTEm9f/2bYr78uC+hZQzgUkYRv46E=</HostId>
</Error>`

for every file.
Is there any solution to install mapnik? 
Thank you

**Comment by artemp** [comment]
@SkyLimited  - I'll need to investigate why 1.x tarballs are not available, thanks for reporting. 
Meanwhile you can install latest (v4.5.3) node-mapnik like `npm install mapnik`

**Comment by springmeyer** [comment]
Yes, solution is to install `mapnik@latest` and not the 1.x series. The 1.x series is not supported - as installed from binaries - since the s3 location is no long present (I think I hosted the binaries in a now defunct location). But source compiles of 1x likely still work if your node version is old enough (changelog would reveal which node versions worked with 1x).
