### ISSUE TITLE
node-mapnik segfaults on node 20.12 onwards

### ISSUE THREAD

**Issue by tstibbs** [mapnik/node-mapnik#995]
### Problem description

In the latest minor release of the current active LTS version (node 20), mapnik causes a segfault.

it's broken in: 
* 20.x (which is the 'active' LTS branch) from 20.12.0 onwards
* 21.x from 21.7.0 onwards
* 22.x from 22.2.0 onwards (thanks @Phyks for reporting this) 

it's not broken in 
* 18.x

Other environment notes: Reproduced in ubuntu and debian; in github actions, docker and WSL.

### To reproduce

Create file `package.json`:
```
{
	"dependencies": {
		"mapnik": "4.5.9"
	}
}
```

Create file `test.js`:
```
require('mapnik').register_default_input_plugins()
```

Run the following:
```
npm install
node test.js
```

Expected output: none

Actual output: aborts execution, prints "Segmentation fault", sets non-zero exit code.

**Comment by artemp** [comment]
@Phyks @tstibbs  - `v4.6.0-rc1` should work with all node versions >= 18 
 
https://github.com/mapnik/node-mapnik/pkgs/npm/mapnik

**Comment by snorkysnark** [comment]
@artemp, is it private tho? How can I get access?

**Comment by artemp** [comment]
@tstibbs  Closing as fixed
