### ISSUE TITLE
Polar Projection issues - missing countries

### ISSUE THREAD

**Issue by rayhammond** [mapnik/node-mapnik#997]
I use mapnik (v4.5.8) for plotting flights paths.  I am trying to use a projection to show flight's path over the North Pole.  The projection I am using is Polar Stereographic (epsg:3995).  When mapnik renders the image some countries are missing (Iceand being the most noticeable). The graticule is also cropped.  Example image following

![image](https://github.com/mapnik/node-mapnik/assets/108461485/b3458414-8ea2-4728-a51e-fbd1d637ac60)

I have created a gist to assist https://gist.github.com/rayhammond/7590c558fcd7bcf4c1a65200de4746c4

Oddly, if we add each polygon to a seperate layer of their own the they render.  But, this is very inefficient and not viable.  
Can anyone advise if I am doing anything wrong?  Or whether there is an alternates projection that I should be using?

**Comment by rayhammond** [comment]
Thanks @artemp we'll try that version and feedback

**Comment by rayhammond** [comment]
@artemp the link provided returns a 404.  I dug a little in the project but I cannot work out how I get my hands on v4.6.0-rc1.  Any assistance would be greatly appreciated.

**Comment by rayhammond** [comment]
@artemp many thanks for the information.  I've manage to get 4.6.0-rc1 installed.  And I've changed the code as suggested, 
 The proj init string I am using now is the one cited here 'https://proj.org/en/9.4/operations/projections/stere.html'.  I've got an image being produced but now it has no content (just a white image)

**Comment by artemp** [comment]
@rayhammond I'll take a look, thanks for testing.

**Comment by artemp** [comment]
I see Iceland is missing, so this issue persists in 4.6.0-rc1 and needs fixing.

**Comment by rayhammond** [comment]
@artemp I've uploaded the graticule to dropbox link [here](https://www.dropbox.com/scl/fi/056v4chol9uk9vtf3it2d/graticule.zip?rlkey=3nwnq8vj4jy65o8b0shcf95mi&st=zdeb8jpv&dl=0). It's only 1.5Mb.  If you cannot access that link please let me know and I'll supply the file another way.

**Comment by artemp** [comment]
@rayhammond thanks ^ I can't access dropbox link without sign-in but no worries I found plenty of graticules on https://www.naturalearthdata.com/   This is not a node-mapnik but rather mapnik core issue. Specifically how bounding boxes are calculated when re-projected I think.

**Comment by artemp** [comment]
> @artemp That change looks like it fixes the issue! Many thanks. Do you know when that will be available to use in npm?

@rayhammond This PR needs some more work and testing. Then I'll release mapnik `v4.0.1` and `node-mapnik v4.6.0-rc2`.
So hopefully next week 🤞

**Comment by artemp** [comment]
@rayhammond  https://github.com/mapnik/node-mapnik/pkgs/npm/mapnik/251924981 
Could you give it a go? (TIP: use `epsg:4326` as geographic projection)

**Comment by rayhammond** [comment]
@artemp I will try tomorrow and feedback.  Thanks for message.

**Comment by rayhammond** [comment]
[graticule.zip](https://github.com/user-attachments/files/16467925/graticule.zip)
Good morning @artemp here is the result of running that RC
![image](https://github.com/user-attachments/assets/f48fa34f-959f-4af7-ad75-7911c45522b3)

The land looks great, but, as you can see the graticule is a little odd.  I've zipped and attached our graticule for reference.  I believe the graticule is valid as it loads in QGIS without issue.

**Comment by artemp** [comment]
@rayhammond Could you try replacing 

`srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"` to `src="epsg:4326"` for graticule layer. It should fix the issue with missing lines ^^

**Comment by artemp** [comment]
@rayhammond - I also notices your graticule has -179deg and 179deg which result in visible arrtifacts 

![image](https://github.com/user-attachments/assets/8b48af51-33af-4595-ada3-bf65d11ce6db)

**Comment by rayhammond** [comment]
> @rayhammond Could you try replacing
> 
> `srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"` with `src="epsg:4326"` for graticule layer. It should fix the issue with missing lines ^^
> 
> You can also use `srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +type=crs"` <-- note `+type=crs`

It does indeed fix the missing line issue

![image](https://github.com/user-attachments/assets/2413a3c8-ec7c-4255-ad3f-a27909a92083)

**Comment by rayhammond** [comment]
> @rayhammond - I also notices your graticule has -179deg and 179deg which result in visible arrtifacts
> 
> ![image](https://private-user-images.githubusercontent.com/59056/354541778-8b48af51-33af-4595-ada3-bf65d11ce6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTA0NjUsIm5iZiI6MTcyMjU5MDE2NSwicGF0aCI6Ii81OTA1Ni8zNTQ1NDE3NzgtOGI0OGFmNTEtMzNhZi00NTk1LWFkYTMtYmY2NWQxMWNlNmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA5MTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZjhkN2NiYzI1ZTg5ZTE4YjdmZTU1YmIxZTg2MmMzMDM3MzZjN2U3YzYwOThkZTVjYWRlZDBlY2ZjMzg4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2nqMgIeule9gXkOCSV18q6M7b1cmqj54qURBEBGKJzY)

Never noticed that before and we've used that graticule for years :-)

**Comment by rayhammond** [comment]
> `srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"` with `src="epsg:4326"` for graticule layer. It should fix the issue with missing lines ^^

I have a question on this, I was having a think over the weekend and I must be miss-understanding how this works.  I thought the srs we set on the XML for the layer was the format of the data within the layers source file.  With your request to change this to epsg:4326, does this means the srs is the format we are projecting too?

**Comment by artemp** [comment]
@rayhammond
> I have a question on this, I was having a think over the weekend and I must be miss-understanding how this works. I thought the srs we set on the XML for the layer was the format of the data within the layers source file. 

Yes, `Layer.srs` is a reference system for the `<Layer>` data. If not specified it inherits it's value from `Map.srs`.

> With your request to change this to epsg:4326, does this means the srs is the format we are projecting too?

In this case `epsg:4326` is SRS of your data (e.g **source**). `epsg:3995` is `Map.srs` is a **destination** SRS
As I mentioned Mapnik is using [`proj v9.4.0`](https://proj.org/en/9.4/) which encourages use of `ESPG` codes to define SRS but you can use full expanded strings just make sure they are compatible with libproj 9.

`epsg:4326` == `"+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +type=crs"`

Internally Mapnik uses libproj APIs to construct proj_transform object  -> https://proj.org/en/9.4/development/reference/functions.html#c.proj_create_crs_to_crs
HTH

**Comment by rayhammond** [comment]
@artemp many thanks for fixing this.  I am not entirely sure how the eco system works with core mapnik.  Does this mean the fix will be available via installing node-mapnik from npm?  Or, do we need to wait for something to be published?

**Comment by artemp** [comment]
@rayhammond - I'm planning to go ahead with [GiHub npm package registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry) for  `>=v4.6.0`. 

Use  [npmjs](https://www.npmjs.com/) for  `node-mapnik <= v4.5.9` e.g. 

```
npm install mapnik@4.5.9
```

otherwise 
 
```
npm install @mapnik/mapnik@4.6.0
``` 
^ when it will be released

Meanwhile I suggest you use RC2
```
npm install @mapnik/mapnik@4.6.0-rc2
```
