### ISSUE TITLE
Core dump in 4.6.0 using node v22 on Debian bookworm

### ISSUE THREAD

**Issue by four43** [mapnik/node-mapnik#998]
Using the Docker image node:22-bookworm and installing the latest 4.6.0 on x86_64 I get a 
```
free(): invalid pointer
Aborted (core dumped)
```

Let me know how I can provide further debug into. Thanks for the help.

**Comment by artemp** [comment]
@four43 yes, please :)

**Comment by artemp** [comment]
@four43 - I just tried

```
podman pull node:22-bookworm
podman run -it docker.io/library/node:22-bookworm   bash
```
```
root@aca67243e479:/# uname -a
Linux aca67243e479 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 GNU/Linux
npm install @mapnik/mapnik 
node
```
```
> var mapnik = require('@mapnik/mapnik');
> mapnik.register_default_fonts();
> mapnik.register_default_input_plugins();
```

Please, provide more info on how to replicate your issue.

**Comment by four43** [comment]
Oh boy, so it is more of a just me thing then. I'll poke around. Thanks for the confirmation it was working.
